#!/usr/bin/env python3
"""Exact differential input, encoded-name and intent-store validation.

Run through atelier.safety. Expected output is produced by unchanged skate-core
from the pinned reference revision. Only this probe target is added to its Cargo
manifest; no implementation is copied into the corpus generator.
"""
import argparse
from collections import Counter
import hashlib
import itertools
import json
from pathlib import Path
import random
import struct
import subprocess
from reference_build import build_probe

PLUGIN = Path(__file__).resolve().parents[1]


class Record:
    def __init__(self):
        self.data = bytearray()

    def word(self, value):
        self.data.extend(struct.pack('<I', value & 0xffffffff))

    def words(self, values):
        for value in values:
            self.word(value)

    def scalar(self, value):
        self.data.extend(struct.pack('<f', value))

    def scalars(self, values):
        for value in values:
            self.scalar(value)

    def raw(self, value):
        if isinstance(value, str):
            value = value.encode()
        self.word(len(value))
        self.data.extend(value)

    def optional(self, value):
        self.word(value is not None)
        if value is not None:
            self.scalar(value)

    def graph(self, count, first=0., last=1., values=None):
        keys = [first + (last-first)*i/(count-1) for i in range(count)]
        self.scalars(keys)
        self.scalars(keys if values is None else values)

    def remap(self, variant):
        self.graph(16, 0., 3.1415927410125732, [1.+variant*i/150 for i in range(16)])
        self.graph(16, 0., 3.1415927410125732)
        self.scalar(variant*.12)


def fbits(value):
    return struct.unpack('<I', struct.pack('<f', value))[0]


def from_bits(value):
    return struct.unpack('<f', struct.pack('<I', value))[0]


def corpus():
    rng = random.Random(0x494e5054)
    cases = []
    parts = []

    def add(op, kind, build):
        row = Record()
        row.word(op)
        build(row)
        cases.append(dict(command=len(cases), operation=op, kind=kind, input_bytes=len(row.data)))
        parts.append(bytes(row.data))

    # Original constructors and listener emissions supply this authored name set.
    stock_names = ('Brake NewPush RightPush Pushing LeftPush BodySpin PhysBodySpin KickTurn '
                   'HardTurnCrouch HardTurn Crouch Turn RightSlideStart LeftSlideStart LeftSlide RightSlide '
                   'GrabWorld AnticMag AnticAngle Manual ManualBrake LeftGroundGrab LeftAirGrab RightGroundGrab '
                   'RightAirGrab Dismount NewDismount DarkCatch NewDarkCatch BoardAdjustAngle BoardAdjustMag '
                   'TweakX TweakY HandPlantTweakX HandPlantTweakY HandPlantDismount HandPlantOneFootRight '
                   'HandPlantOneFootLeft GrindBalanceX PhysGrindTranslation PhysGrindStabilityNudge PhysGrindUpDown '
                   'WipeoutGestureX WipeoutGestureY WipeoutControlX WipeoutControlY WipeOutRecover WipeOutRequest '
                   'WipeOutPushOff OB_Jump OB_LookAtX OB_LookAtY OB_DropBoard OB_ThrowBoard OB_RetrieveBoard '
                   'OB_DoAirBodyTweak OB_AirBodyTweakX OB_AirBodyTweakY NewToggleOffBoardState ToggleOffBoardState '
                   'OB_Sprint OB_Mag OB_BipedWorldZ OB_BipedWorldX OB_BipedStickMag negate abs oneMinus clamp '
                   'angleFlip angleRot90 angleRotN90 none').split()
    raw_names = [name.encode() for name in stock_names]
    raw_names += [b'', bytes(range(256))]
    for byte in range(256):
        for count in (1, 5, 6, 7, 29, 30, 31, 35, 36, 37, 64):
            raw_names.append(bytes([byte])*count)
    for count in range(66):
        raw_names.extend((b'a'*count+b'Ztail', b'abc\0def'*count))
    raw_names += [bytes(rng.randrange(256) for _ in range(rng.randrange(90))) for _ in range(8192)]
    for name in raw_names:
        add(0, 'authored/boundary/generated byte name', lambda w, name=name: w.raw(name))

    aliases = []
    for name in stock_names + ['', 'a'*30, 'a'*36, 'a'*37, 'éö字🙂', 'Aa:_[]`{~09']:
        aliases.extend([name, name.upper(), name.lower(), name+'\0ignored', name[:36]+'tail'])
    aliases += [''.join(rng.choice('aAZ09_:[]éö字') for _ in range(rng.randrange(65))) for _ in range(2048)]
    for index, name in enumerate(aliases):
        for action in (0, 1, 3, 0, 1, 2, 1):
            def build(w, action=action, name=name, index=index):
                w.word(action)
                w.raw(name)
                if action == 0:
                    w.word((0x80000000, 0, 0x3f800000, 0x7fc12345, 0xbf800000)[index % 5])
            add(1, 'canonical alias and last write/removal', build)
        if index % 29 == 0:
            add(1, 'clear', lambda w: (w.word(4), w.raw('')))

    pad_levels = [0., -0., .5, from_bits(0x3f000001), 1., -1., from_bits(0x7fc12345)]
    for case in range(128):
        def build(w, case=case):
            stored = case % 25
            count = (case*7) % (stored+1)
            w.words((stored, count))
            for slot in range(stored):
                w.words((fbits(pad_levels[(slot+case) % len(pad_levels)]), rng.getrandbits(32),
                         (0, 1, 12, 24, 0xffffffff)[slot % 5], (0, 1, 2, 3, 0xffffffff, 0x80000000)[slot % 6]))
            w.word(160)
            for tick in range(160):
                # Three-call suppression, 24/12 repeat, resize growth/reset and
                # shorter polls with retained native initialized storage.
                size = 24 if tick < 90 else (0, 4, 24, 8, 24, 1)[tick % 6]
                w.word(size)
                w.scalars([pad_levels[((tick//(4+slot%5))+slot+case) % len(pad_levels)] for slot in range(size)])
        add(2, 'button suppression/repeat/wrapping and retained storage', build)

    axes = (-32768, -32767, -8193, -8192, -8191, -33, -32, -1, 0, 1, 32, 33, 8191, 8192, 8193, 32766, 32767)
    xbox_states = [(buttons, lt, rt, lx, ly, rx, ry, device)
                   for buttons in (0, 0xffff, 0x03ff, 0xf000, 0x0c00)
                   for lt, rt in ((0, 0), (1, 254), (127, 128), (255, 255))
                   for lx, ly in itertools.product(axes, repeat=2)
                   for rx, ry, device in ((lx, ly, 0), (-lx if lx != -32768 else 32767, -ly if ly != -32768 else 32767, 1))]
    xbox_states += [(rng.randrange(65536), rng.randrange(256), rng.randrange(256),
                     *(rng.randrange(-32768, 32768) for _ in range(4)), rng.choice((0, 1, 255))) for _ in range(8192)]
    for state in xbox_states:
        add(3, 'Xbox button/trigger/deadzone/device endpoint', lambda w, state=state: w.words(state))

    dt_values = (0., -0., 1/60, 1/120, .1, .007)
    levels = (-1., -.9, -.5, -0., 0., .25, .5, .9, 1., 1.0000001192092896)
    for case in range(96):
        def build(w, case=case):
            words = [fbits(rng.uniform(-2, 2)) for _ in range(26)]
            words[6] = rng.getrandbits(32)
            words[13] = rng.getrandbits(32)
            w.words(words)
            w.word(case % 2)
            w.word(128)
            for tick in range(128):
                w.scalar(dt_values[tick % len(dt_values)])
                w.words((tick % 2, (tick//2) % 2))
                w.optional(None if tick % 3 == 0 else (.25, .5, 1., from_bits(0x7fc12345))[tick % 4])
                w.scalar(.3)
                w.scalars([rng.choice(levels) for _ in range(18)])
                w.scalars([rng.choice(levels) for _ in range(18)])
                w.words([rng.choice((0, 1, 2, 3, 255, 256, 257)) for _ in range(18)])
        add(4, 'controller startup/timers/arbitration/query order', build)

    # Original Rust tests' cardinal, tail/nose, automatic-push, diagonal and
    # full/partial-trigger scenarios, followed by deterministic generated state.
    authored_sticks = [(0., 0.), (1., 0.), (-1., 0.), (0., 1.), (0., -1.), (.25, -.5),
                       (-.75, 0.), (.75, 0.), (.7, -.9), (.8, -.6), (.95, .2)]
    producer_inputs = []
    for left, right in itertools.product(authored_sticks, repeat=2):
        for actor in (0, 1, 0x40, 0x80, 0x100, 0x200, 0x400, 0x800, 0xfff):
            for trigger in (0., .25, 1.):
                producer_inputs.append((left, right, actor, trigger))
    producer_inputs += [((rng.choice(levels), rng.choice(levels)), (rng.choice(levels), rng.choice(levels)),
                         rng.randrange(4096), rng.choice(levels)) for _ in range(4096)]
    for index, (left, right, actor, trigger) in enumerate(producer_inputs):
        def build(w, index=index, left=left, right=right, actor=actor, trigger=trigger):
            words = [fbits(rng.choice(levels)) for _ in range(26)]
            words[6], words[13] = rng.getrandbits(32), rng.getrandbits(32)
            words[7:11] = [fbits(v) for v in (*left, *right)]
            words[11] = fbits(trigger)
            words[12] = fbits((0., .25, 1.)[index % 3])
            w.words(words)
            w.words((actor, (0, 0x40, 0x80, 0x100, 0x1c0)[index % 5], index % 2, (index//2) % 2, index % 3 == 0))
            w.scalars((.25, .75, .95, -.0))
            w.word(index % 2)
            if index % 2:
                w.scalars((-.75, .2, .5, 0.))
            w.scalars(left)
        add(5, 'authored and generated ordered controller intentions', build)

    filter_values = [-0., 0., -4., -3.1415927410125732, -1.5707963705062866, -1., .001, .5, 1., 1.5707963705062866, 3.1415927410125732, 4., from_bits(0x7fc12345)]
    for case in range(512):
        def build(w, case=case):
            w.scalar(filter_values[case % len(filter_values)])
            w.words([(case//(i+1)) % 11 for i in range(4)])
            w.word(case % 5)
            w.word(case % 2)
            w.optional(None if case % 4 else .25)
            w.scalar((-1., .5, 1.)[case % 3])
            w.word(case % 2)
            w.word(15)
            for tick in range(15):
                w.word((0, 1, 1, 1, 2)[tick % 5])
                w.optional(None if tick % 3 == 0 else rng.choice(levels))
                w.word(tick % 5)
            w.scalars((.1, -.25, .9))
            w.words([case % 8, (case//2) % 8, (case//4) % 8, (case//8) % 8])
            w.optional(None if case % 3 == 0 else (-0., 0., .01, .25, -1.)[case % 5])
            w.scalars((.15, .07))
            w.optional(None if case % 4 == 0 else .2)
            w.optional(None if case % 3 == 0 else .125)
            w.optional(None if case % 2 == 0 else .025)
            w.scalars((.0, -.03, .4))
            w.word(case % 2)
            w.word(96)
            for tick in range(96):
                w.optional(None if tick % 7 == 0 else rng.choice(levels))
                w.scalar(dt_values[tick % len(dt_values)])
                w.word(1+tick % 4)
        add(6, 'intent filters/lifecycles/ramp signed-bit bounds', build)

    for case in range(32):
        def build(w, case=case):
            w.word(192)
            for tick in range(192):
                drain = tick % (2+case % 7) == 0 or tick in (0, 31, 61, 191)
                w.word(int(drain))
                if not drain:
                    count = (tick+case) % 5
                    w.word(count)
                    for device in range(count):
                        size = (tick+device) % 25
                        w.word(size)
                        w.scalars([rng.choice(pad_levels) for _ in range(size)])
                        w.word((tick+device) % 11 == 0)
        add(7, 'history overwrite/wrap/latest/missing device polls', build)

    for case in range(32):
        def build(w, case=case):
            w.scalars([rng.uniform(-1, 1) for _ in range(8)])
            for _ in range(3):
                w.scalars([rng.uniform(-1, 1) for _ in range(9)])
            for i in range(3):
                w.scalars((.03+i*.02, .02, .1, .4))
            w.graph(8, values=[.4+i*.08 for i in range(8)])
            w.graph(8)
            w.graph(8, 0., 15., [1-i*.05 for i in range(8)])
            w.graph(4, 0., 1., [.1, .2, .4, .8])
            w.scalars((.025, .8, .05, .02, .01, .03, .02, .15, .7, .1, 5., 15., 1.))
            w.word(128)
            for tick in range(128):
                w.word(tick % 37 == 0)
                w.scalars((rng.uniform(0, 20), rng.uniform(-.5, 1.5), rng.uniform(-6, 6), rng.choice(levels)))
                w.words((tick % 3, (tick//3) % 3))
        add(8, 'steering nine-word filters and complete history', build)

    for case in range(48):
        def build(w, case=case):
            w.remap(case % 3)
            w.remap(-(case % 3))
            w.graph(8, 0., 15., [i*.05 for i in range(8)])
            w.graph(8, 0., .5, [i/7 for i in range(8)])
            w.scalars((2., .04, .9, .2, -.3))
            w.word(case % 5)
            w.words([rng.getrandbits(32) for _ in range(5)])
            w.word(160)
            for tick in range(160):
                phase = tick % 13 if tick % 13 < 8 else 8
                if tick % 17 == 0:
                    phase = 8
                w.words((phase, tick % 2, (tick//2) % 2))
                w.scalar(dt_values[tick % len(dt_values)])
                if phase == 8:
                    w.scalars((rng.choice(levels), rng.choice(levels), rng.random(), rng.choice(levels), rng.random(), rng.uniform(-15, 15)))
                    w.word(1+tick % 4)
                    for i in range(3):
                        w.optional(None if (tick+i) % 4 == 0 else rng.choice(levels))
        add(9, 'turn vector remap/slide retained owner/SetTurning', build)

    for case in range(32):
        def build(w, case=case):
            w.word(256)
            for tick in range(256):
                w.scalars((.15+(case % 3)*.05, .2+(case % 2)*.1))
                w.words((tick % 31 == 0, tick % 19 == 0, tick % 23 == 0, (tick//11) % 4))
                w.scalar(dt_values[tick % len(dt_values)])
        add(10, 'ordered body flip gesture/takeoff windows', build)

    for case in range(64):
        def build(w, case=case):
            w.scalars((.2, .1, -.2))
            w.word(rng.getrandbits(32))
            w.words([rng.getrandbits(32) for _ in range(5)])
            w.scalars((2., .15))
            w.graph(4, -1., 1., [.05, .1, .15, .3])
            w.graph(4, 0., 15., [.0, .1, .3, .6])
            w.graph(4, -1., 1., [.5, .1, .1, .5])
            w.word(128)
            for tick in range(128):
                w.word(1 if tick % 19 < 15 else tick % 4)
                w.scalar(rng.choice((0., 2., 2.000001, 8., 15.)))
                w.optional(None if tick % 7 == 0 else rng.choice(levels))
                w.optional(None if tick % 9 == 0 else rng.choice(levels))
                w.words((tick % 3 == 0, tick % 5 == 0))
                w.scalar(rng.choice(levels))
                w.scalars([dt_values[(tick+i) % len(dt_values)] for i in range(3)])
                w.word(tick % 5 != 0)
                if tick % 5 != 0:
                    w.scalars([rng.uniform(-2, 2) for _ in range(4)])
                    w.scalars((.25, .75, .5, 0.))
                    w.word(tick % 3)
        add(11, 'PowerSliding timing queries/alignment/latches', build)

    for case in range(1024):
        def build(w, case=case):
            w.word(case % 256)
            w.words([rng.getrandbits(32) for _ in range(2)])
            w.words([(case+i) % 256 for i in range(3)])
            w.words([rng.getrandbits(32) for _ in range(20)])
            w.word((case*7) % 256)
            w.words([rng.getrandbits(32) for _ in range(2)])
            w.word((case*13) % 256)
            w.words([rng.getrandbits(32) for _ in range(2)])
        add(12, 'packet publication bits and uninterpreted words', build)

    for case in range(1024):
        def build(w, case=case):
            current = [fbits(rng.choice(levels)) for _ in range(6)] + [rng.getrandbits(32)]
            previous = [fbits(rng.choice(levels)) for _ in range(6)] + [rng.getrandbits(32)]
            w.words(current)
            w.words(previous)
            w.words((case % 2, (case//2) % 2))
            w.scalars([rng.choice(levels) for _ in range(18)])
            w.scalars([rng.choice(levels) for _ in range(18)])
            w.words([rng.choice((0, 1, 2, 3, 255)) for _ in range(18)])
        add(13, 'raw flags destination retention and previous arbitration', build)

    data = struct.pack('<I', len(parts)) + b''.join(parts)
    offset = 4
    for case in cases:
        case['input_offset'] = offset
        offset += case['input_bytes']
    return data, cases


def build_probes(output, target_dir):
    native = PLUGIN/'Source/AtelierSkate/Private/Native'
    cpp = output/'input-cpp'
    sources = [native/f'{name}.cpp' for name in ('NativeMath', 'AnimationName', 'Intents', 'Input', 'InputIntentions')]
    subprocess.run(['clang++', '-std=c++17', '-O2', '-ffp-contract=off', '-fno-fast-math', '-Wall', '-Wextra', '-Werror',
                    '-I', str(native), *(str(source) for source in sources), str(PLUGIN/'Tests/Native/input_probe.cpp'), '-o', str(cpp)], check=True)
    rust = build_probe(output, 'input-reference', PLUGIN/'Tests/Reference/input_probe.rs', target_dir)
    return cpp, rust


def first_failing_command(cpp, rust, inputs, cases):
    # Replay prefixes only after failure to report the concrete triggering case.
    lower, upper = 1, len(cases)
    while lower < upper:
        middle = (lower+upper)//2
        end = cases[middle-1]['input_offset'] + cases[middle-1]['input_bytes']
        prefix = struct.pack('<I', middle) + inputs[4:end]
        expected = subprocess.check_output([str(rust)], input=prefix)
        actual = subprocess.check_output([str(cpp)], input=prefix)
        if actual == expected:
            lower = middle+1
        else:
            upper = middle
    return cases[lower-1]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, required=True)
    parser.add_argument('--target-dir', type=Path, required=True)
    args = parser.parse_args()
    output = args.output.resolve()
    output.mkdir(parents=True, exist_ok=True)
    cpp, rust = build_probes(output, args.target_dir)
    inputs, cases = corpus()
    (output/'input.bin').write_bytes(inputs)
    (output/'cases.json').write_text(json.dumps(cases, indent=2)+'\n')
    expected = subprocess.check_output([str(rust)], input=inputs)
    actual = subprocess.check_output([str(cpp)], input=inputs)
    (output/'reference.bin').write_bytes(expected)
    (output/'cpp.bin').write_bytes(actual)
    if actual != expected:
        first = next((i for i, (a, b) in enumerate(zip(actual, expected)) if a != b), min(len(actual), len(expected)))
        report = dict(passed=False, first_byte=first, reference_length=len(expected), cpp_length=len(actual),
                      triggering_command=first_failing_command(cpp, rust, inputs, cases),
                      reference_hex=expected[max(0, first-16):first+32].hex(), cpp_hex=actual[max(0, first-16):first+32].hex())
        (output/'first-divergence.json').write_text(json.dumps(report, indent=2)+'\n')
        raise AssertionError(report)
    report = dict(passed=True, commands=len(cases), operations=dict(Counter(case['operation'] for case in cases)),
                  output_bytes=len(expected), comparison='all published values and retained controller/filter/latch words; exact bits, no tolerance',
                  inputs_sha256=hashlib.sha256(inputs).hexdigest(), outputs_sha256=hashlib.sha256(expected).hexdigest(),
                  reference_provenance='input-reference-provenance.json')
    (output/'result.json').write_text(json.dumps(report, indent=2)+'\n')
    print(json.dumps(report, indent=2), flush=True)


if __name__ == '__main__':
    main()
