// Generated by gen-types.mjs from platform/web/board/api/board-api.schema.json. Do not edit.

/**
 * A file named in a message's attachment trailer.
 * 
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "Attachment".
 */
export type Attachment = (File | {
missing: boolean
name: string
})
/**
 * Who a reply goes to: `*` for the whole board, or these agents.
 * 
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "ReplyAudience".
 */
export type ReplyAudience = (string | string[])
/**
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "Recipient".
 */
export type Recipient = (string | string[])

/**
 * Every shape in one document, so one schema file names them all.
 */
export interface Contract {
state: State
threads: Threads
activity: Activity
thread: Thread
document: Document
upload: Upload
sent: Sent
send_request: SendRequest
preview_request: PreviewRequest
preview: Preview
read_request: ReadRequest
read: Read
seen_request: SeenRequest
seen: Seen
star_request: StarRequest
starred: Starred
dismiss_request: DismissRequest
dismissed: Dismissed
remove_request: RemoveRequest
removed: Removed
push_subscribe_request: PushSubscribeRequest
push_unsubscribe_request: PushUnsubscribeRequest
subscribed: Subscribed
delivered: Delivered
push_key: PushKey
problem: Problem
ok: Ok
}
/**
 * `GET /api/state`: the feed page, the agents, the render board and everything the header shows.
 * 
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "State".
 */
export interface State {
time: number
/**
 * Newest first. Every copy of a web send on the page is included, even past the page's limit.
 */
messages: Message[]
has_more: boolean
agents: Agent[]
total: number
/**
 * The operator's open tasks, oldest first.
 */
tasks: OperatorTask[]
/**
 * The render board's Holding, Waiting, Handoffs and Log sections (Log cut to the newest `log` entries).
 */
schedule: {
[k: string]: string | undefined
}
log_total: number
inbox: InboxSummary
holders: Holders
sessions: Session[]
resources: Resources
/**
 * Send it back as `X-Board-CSRF` on every POST.
 */
csrf: string
/**
 * The name the board posts as.
 */
sender: string
}
/**
 * A message as the board shows it.
 * 
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "Message".
 */
export interface Message {
id: number
/**
 * Seconds since the Unix epoch.
 */
created: number
sender: string
/**
 * An agent's name, or `*` for the whole board.
 */
recipient: string
topic: string
body: string
reply_to?: (number | null)
/**
 * `web-broadcast:{uuid}:{agent}`, `web-broadcast:{uuid}~m:{agent}` (a mention group) or
 * `web-direct:{uuid}:{agent}` for the addressed copies of one web send; other keys are the sender's own.
 */
dedup?: (string | null)
/**
 * 1 when its sender asked for a phone notification to the operator.
 */
notify: number
/**
 * Everyone the message reached: `["*"]` for the whole board, every addressed copy's recipient for a web send.
 */
audience: string[]
/**
 * The body without its attachment trailer, rendered as safe HTML.
 */
body_html: string
attachments: Attachment[]
/**
 * Its recipient replied with an acknowledgement.
 */
acknowledged: boolean
}
/**
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "File".
 */
export interface File {
id: string
name: string
mime: string
size: number
/**
 * Where the board serves it (with byte ranges, for video).
 */
url: string
/**
 * A photo's or video's pixel size, when the uploader knew it.
 */
width?: (number | null)
height?: (number | null)
/**
 * Markdown or text small enough to open in the board's reader (`/api/document/{id}`).
 */
readable: boolean
}
/**
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "Agent".
 */
export interface Agent {
agent: string
/**
 * The newest message delivered to the agent.
 */
cursor: number
pid?: (number | null)
heartbeat?: (number | null)
/**
 * The folder name of the agent's checkout.
 */
checkout?: (string | null)
stop: number
/**
 * Its listener runs as a launchd service.
 */
supervised: boolean
/**
 * Its one-line status; `idle` when it has none.
 */
task?: (string | null)
task_at?: (number | null)
/**
 * Whether the agent's own session is `busy` or `idle`, since `session_since`.
 */
session?: (string | null)
session_since?: (number | null)
/**
 * A listener is armed and sent a heartbeat in the last 90 seconds.
 */
listening: boolean
/**
 * Messages addressed to it that it has not received yet.
 */
pending: number
/**
 * Its listener's last delivery failed.
 */
delivery_error: boolean
/**
 * The newest message it sent the board's sender (0 for none).
 */
last_to_me: number
/**
 * Its direct messages to the board's sender that are still unread, by the board's one read state.
 */
unread: number
/**
 * It has render work in flight (named on the render board, or holding a render lock).
 */
engaged: boolean
}
/**
 * An agent blocked on the operator.
 * 
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "OperatorTask".
 */
export interface OperatorTask {
id: number
created: number
agent: string
/**
 * The ask's message, the root of the task's thread.
 */
message: number
closed?: (number | null)
closed_by?: (string | null)
note?: (string | null)
edited?: (number | null)
/**
 * The ask (its newest wording once edited).
 */
body: string
body_html: string
asked: number
replies: number
last_reply?: (LastReply | null)
}
/**
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "LastReply".
 */
export interface LastReply {
sender: string
body: string
created: number
}
/**
 * The Threads and Activity tabs' unread badges.
 * 
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "InboxSummary".
 */
export interface InboxSummary {
threads: number
activity: number
}
/**
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "Holders".
 */
export interface Holders {
big?: (Holder | null)
small?: (Holder | null)
}
/**
 * A live render lock holder.
 * 
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "Holder".
 */
export interface Holder {
purpose: unknown
kind: unknown
/**
 * The folder name of the checkout running the job.
 */
checkout: string
time: unknown
}
/**
 * A remote agent session the watchdog reports on.
 * 
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "Session".
 */
export interface Session {
name: unknown
url: string
health: unknown
connection: unknown
fresh: boolean
}
/**
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "Resources".
 */
export interface Resources {
/**
 * The machine's resource report is under two minutes old.
 */
fresh: boolean
cpu?: (number | null)
available_gib?: (number | null)
}
/**
 * `GET /api/threads`: the conversations the reader is part of, unread first, then by newest reply.
 * 
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "Threads".
 */
export interface Threads {
threads: ThreadItem[]
total: number
unread: number
/**
 * How many threads the reader starred (`?starred=1` lists only those).
 */
starred: number
}
/**
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "ThreadItem".
 */
export interface ThreadItem {
/**
 * The root message's id.
 */
id: number
/**
 * The thread's read-state key.
 */
key: string
root: Card
/**
 * The newest replies, oldest first.
 */
latest: Card[]
replies: number
/**
 * Unread replies.
 */
unread: number
participants: string[]
reply_audience: ReplyAudience
last_activity: number
newest: number
starred: boolean
}
/**
 * A message as the inbox shows it.
 * 
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "Card".
 */
export interface Card {
id: number
created: number
sender: string
recipient: string
topic: string
reply_to?: (number | null)
dedup?: (string | null)
body: string
body_html: string
attachments: Attachment[]
acknowledged: boolean
/**
 * One line of plain text, at most 160 characters and an ellipsis.
 */
snippet: string
audience?: (string[] | null)
unread?: (boolean | null)
}
/**
 * `GET /api/activity`: what involves the reader, newest first.
 * 
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "Activity".
 */
export interface Activity {
items: ActivityItem[]
total: number
unread: ActivityCounts
}
/**
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "ActivityItem".
 */
export interface ActivityItem {
/**
 * `mention`, `reply`, `dm` or `ack`.
 */
kind: string
id: number
created: number
unread: number
count: number
/**
 * The thread's root message id.
 */
thread: number
replies: number
message?: (Card | null)
senders: string[]
reply_audience: ReplyAudience
/**
 * The thread's root, when it is not the message itself.
 */
root?: (Card | null)
/**
 * For an acknowledgement, the reader's message it acknowledges.
 */
target?: (Card | null)
}
/**
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "ActivityCounts".
 */
export interface ActivityCounts {
all: number
mention: number
reply: number
dm: number
ack: number
}
/**
 * `GET /api/thread?id=`: a whole conversation, oldest first.
 * 
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "Thread".
 */
export interface Thread {
/**
 * The root: every addressed copy of a web send.
 */
root: Message[]
replies: Message[]
/**
 * The thread's read-state key.
 */
key: string
starred: boolean
}
/**
 * `GET /api/document/{id}`: a Markdown or text attachment, rendered for the reader.
 * 
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "Document".
 */
export interface Document {
name: string
url: string
size: number
html: string
}
/**
 * `POST /api/upload` (the raw file as the body, `X-File-Name`, and optionally `X-Media-Width`/`X-Media-Height`).
 * 
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "Upload".
 */
export interface Upload {
id: string
name: string
mime: string
size: number
width?: (number | null)
height?: (number | null)
}
/**
 * `POST /api/send` and `/api/broadcast`.
 * 
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "Sent".
 */
export interface Sent {
/**
 * One addressed copy per recipient.
 */
messages: Row[]
recipients: string[]
}
/**
 * A stored message, exactly as the mailbox holds it.
 * 
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "Row".
 */
export interface Row {
id: number
/**
 * Seconds since the Unix epoch.
 */
created: number
sender: string
/**
 * An agent's name, or `*` for the whole board.
 */
recipient: string
topic: string
body: string
reply_to?: (number | null)
/**
 * `web-broadcast:{uuid}:{agent}`, `web-broadcast:{uuid}~m:{agent}` (a mention group) or
 * `web-direct:{uuid}:{agent}` for the addressed copies of one web send; other keys are the sender's own.
 */
dedup?: (string | null)
/**
 * 1 when its sender asked for a phone notification to the operator.
 */
notify: number
}
/**
 * `POST /api/send`. `/api/broadcast` takes the same without `recipient` and reaches every listening agent.
 * 
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "SendRequest".
 */
export interface SendRequest {
body: string
/**
 * A fresh UUID per message: a retry with the same one never sends twice.
 */
request_id: string
/**
 * Defaults to `request`.
 */
topic?: (string | null)
/**
 * One agent, the agents a message @mentions, or `*`.
 */
recipient?: (Recipient | null)
reply_to?: (number | null)
/**
 * Upload ids, at most 10.
 */
attachments?: (string[] | null)
}
/**
 * `POST /api/preview`.
 * 
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "PreviewRequest".
 */
export interface PreviewRequest {
/**
 * At most 8000 characters.
 */
body: string
}
/**
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "Preview".
 */
export interface Preview {
html: string
}
/**
 * `POST /api/read`: mark a thread read (up to `through`, else its newest message), follow or unfollow it, or mark
 * everything read with `all`.
 * 
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "ReadRequest".
 */
export interface ReadRequest {
id?: (number | null)
through?: (number | null)
all?: (boolean | null)
follow?: (boolean | null)
}
/**
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "Read".
 */
export interface Read {
/**
 * The thread's key, or `*` for everything.
 */
read: string
}
/**
 * `POST /api/seen`: the messages the reader has had on screen. Each one's thread is read up to the newest of them.
 * 
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "SeenRequest".
 */
export interface SeenRequest {
/**
 * At most 500.
 */
ids: number[]
}
/**
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "Seen".
 */
export interface Seen {
/**
 * The threads whose read mark moved forward.
 */
threads: number
}
/**
 * `POST /api/star`: star or unstar the thread a message is in.
 * 
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "StarRequest".
 */
export interface StarRequest {
id: number
starred: boolean
}
/**
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "Starred".
 */
export interface Starred {
/**
 * The thread's key.
 */
key: string
starred: boolean
}
/**
 * `POST /api/task/dismiss`.
 * 
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "DismissRequest".
 */
export interface DismissRequest {
id: number
note?: (string | null)
}
/**
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "Dismissed".
 */
export interface Dismissed {
dismissed: number
/**
 * It had been dismissed before.
 */
already: boolean
}
/**
 * `POST /api/remove`.
 * 
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "RemoveRequest".
 */
export interface RemoveRequest {
agent: string
}
/**
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "Removed".
 */
export interface Removed {
removed: string
}
/**
 * `POST /api/push/subscribe`: a browser's PushSubscription as JSON. `/api/push/unsubscribe` takes `{endpoint}`.
 * 
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "PushSubscribeRequest".
 */
export interface PushSubscribeRequest {
subscription: PushSubscription
}
/**
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "PushSubscription".
 */
export interface PushSubscription {
endpoint: string
keys: PushKeys
}
/**
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "PushKeys".
 */
export interface PushKeys {
p256dh: string
auth: string
}
/**
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "PushUnsubscribeRequest".
 */
export interface PushUnsubscribeRequest {
endpoint: string
}
/**
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "Subscribed".
 */
export interface Subscribed {
subscribed: boolean
}
/**
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "Delivered".
 */
export interface Delivered {
/**
 * Devices the sample notification reached.
 */
delivered: number
}
/**
 * `GET /api/push/key`: the VAPID public key, for PushManager.subscribe.
 * 
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "PushKey".
 */
export interface PushKey {
key: string
}
/**
 * Every failure: a sentence to show the person.
 * 
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "Problem".
 */
export interface Problem {
error: string
}
/**
 * This interface was referenced by `Contract`'s JSON-Schema
 * via the `definition` "Ok".
 */
export interface Ok {
ok: boolean
}
