// The checker prepends physical owner adapters and unchanged host modules.
use skate_core::{animation::foot_ik as core_ik,physics::{grind_air,skeleton_landing},player::input_phase::PlayerInputState};
fn adjusted_offset(out:&mut Vec<u32>,a:&physics::Animated){let s=&a.board_offset;probe_matrix(out,s.transform);probe_floats(out,[s.orientation_frames,s.height_frames]);out.extend([s.orientation_refreshed as u32,s.height_refreshed as u32]);}
fn adjusted_landing(out:&mut Vec<u32>,a:&physics::Animated){let s=&a.landing;out.extend([s.active as u32,s.kind]);probe_floats(out,[s.time,s.position,s.velocity,s.previous_com_velocity,s.previous_animation_height]);out.push(s.previous_filtered_state);out.push(s.desired_grind_com.to_bits());}
fn adjusted_ik(out:&mut Vec<u32>,ik:&physics::foot_ik::FootIk){let s=&ik.state;out.push(s.feet_enabled() as u32);for l in s.limbs{out.push(l.mode as u32);probe_floats(out,[l.board_blend,l.external_blend,l.target_blend]);out.extend([l.external_target_set as u32,l.local_target_set as u32]);probe_floats(out,l.external_target_local_delta);probe_floats(out,l.part_position);}for l in s.frames{for m in [l.target,l.world,l.external_world,l.board,l.parent_world,l.external_parent_world,l.parent_board]{probe_matrix(out,m);}out.push(l.within_contact_bounds as u32);}for t in s.external_targets{probe_floats(out,t.world_position);probe_floats(out,t.animation_position);probe_floats(out,t.normal);out.extend([t.normal_set as u32,t.normal_blend.to_bits()]);}for c in s.contacts.feet{out.push(c.query_state);probe_floats(out,c.position);probe_floats(out,[c.desired_offset,c.offset]);}out.extend([s.contacts.support_failed as u32,s.contacts.support_failed_this_update as u32]);}
fn adjusted_grind(out:&mut Vec<u32>,s:&grind_air::GrindAir){
 // Derived Debug observes private histories without replacing numeric source,
 // layout casts, or numerical tolerance. Rust's shortest decimal float output
 // round trips to the exact finite f32, including signed zero.
 let text=format!("{s:?}");for field in ["offset_delta","offset","angle_delta","angles"]{let tail=text.split(&format!("{field}: [")).nth(1).unwrap();let v=tail.split(']').next().unwrap().split(',').map(|x|x.trim().parse::<f32>().unwrap().to_bits()).collect::<Vec<_>>();assert_eq!(v.len(),4);out.extend(v);}let selected=text.split("selected_kind: ").nth(1).unwrap();let kind=if selected.starts_with("Some("){Some(selected[5..].split(')').next().unwrap().parse::<u32>().unwrap())}else{None};out.extend([kind.is_some() as u32,kind.unwrap_or(0)]);let h=text.split("headings: [").nth(1).unwrap().split(']').next().unwrap().split(',').map(|x|x.trim().parse::<f32>().unwrap().to_bits()).collect::<Vec<_>>();assert_eq!(h.len(),12);out.extend(h);
}
fn adjusted_queries(out:&mut Vec<u32>,p:&PlayerInputState){for q in [p.hips_line_test_1488,p.left_line_test_1536,p.right_line_test_1584]{out.extend(q.position);out.extend(q.normal);out.extend([q.surface,q.valid as u32]);}}
fn adjusted_out(out:&mut Vec<u32>,a:&physics::Animated,ik:&physics::foot_ik::FootIk,g:&grind_air::GrindAir,p:&PlayerInputState){adjusted_offset(out,a);adjusted_landing(out,a);for m in a.targets.into_iter().chain([a.animation_board,a.unadjusted_board,a.animation_hips,a.motion.trajectory,a.motion.inverse_trajectory,a.motion.next_trajectory]){probe_matrix(out,m);}probe_floats(out,a.motion.velocity_world);out.push(a.board_at_y_delta.to_bits());adjusted_ik(out,ik);adjusted_grind(out,g);adjusted_queries(out,p);}
fn adjusted_loaded(out:&mut Vec<u32>,a:&physics::Animated,ik:&physics::foot_ik::FootIk,g:&grind_air::Settings){
 probe_masses(out,&a.masses);out.extend(a.bone_indices.map(|v|v as u32));for m in a.physics_frames{probe_matrix(out,m);}let(blend,targets,l)=physics::animated_skeleton::observer(a);out.extend(targets.map(|v|v as u32));probe_floats(out,blend.x);probe_floats(out,blend.y);for graph in [&l.manual_blend,&l.grind_blend,&l.coffin_height]{probe_floats(out,graph.x);probe_floats(out,graph.y);}probe_floats(out,[l.minimum_height,l.maximum_velocity,l.manual_damping,l.manual_spring,l.ground_minimum_compression_time,l.ground_damping,l.ground_spring,l.grind_animation_target_time,l.grind_damping,l.grind_spring,l.grind_target_delta,l.desired_com_height,l.coffin_time,l.coffin_maximum_velocity,l.coffin_blend_frames,l.coffin_base_height]);
 let(geometry,q,post,bones)=physics::foot_ik::observer(ik);out.extend(geometry.parents.map(|p|p.map_or(u32::MAX,|v|v as u32)));for m in geometry.inverse_part_frames{probe_matrix(out,m);}probe_floats(out,[q.angle_limits.minimum_degrees,q.angle_limits.maximum_degrees]);probe_floats(out,q.blend.hand_inner_padding);probe_floats(out,q.blend.hand_outer_padding);probe_floats(out,[q.blend.external_blend_step,q.blend.board_blend_step]);for v in [q.post_ik_padding,q.contact_bounds,q.foot_on_deck_padding]{probe_floats(out,v);}probe_floats(out,[q.wipeout_feet_offset,q.deck_half_width,q.deck_half_length,q.deck_total_half_length,q.deck_front_angle_degrees,post.minimum_board_up,post.wipeout_height,post.riding_height]);out.extend(bones.map(|v|v as u32));out.push(g.frames as u32);out.push(g.stomp.to_bits());for v in g.points{probe_floats(out,v);}probe_floats(out,g.ranges);probe_floats(out,g.distances);probe_floats(out,g.yaw_assist);probe_floats(out,[g.max_offset,g.max_delta,g.max_angle]);
}
fn adjusted_hierarchy(e:&animation_pose::PoseEvaluator,kind:u32)->Vec<AnimationPartTransform>{e.hierarchy(&e.evaluate(&[skate_core::animation::playback_tree::PoseCommand::Pose{name:POSES[kind as usize].into()}]).unwrap()).unwrap()}
fn adjusted_error_out(out:&mut Vec<u32>,r:Result<(),String>){out.push(r.is_ok() as u32);probe_error(out,&r.err().unwrap_or_default());}
fn adjusted_owner_error(mode:u32,out:&mut Vec<u32>,p:&mut GamePhysics,s:&mut SkaterRuntime,ik:&mut physics::foot_ik::FootIk,g:&mut grind_air::GrindAir,gs:&grind_air::Settings,e:&mut animation_pose::PoseEvaluator,data:&skate_data::collections::Collections){
 let globals=adjusted_hierarchy(e,0);let a=&mut s.animated_skeleton;let mut f1=0;let mut f2=0;let landing=skeleton_landing::LandingInput{filtered_state:0,flags_2468:0,flags_2472:0,flags_2476:0,balance:0.,physical_com_velocity_along_up:0.,physical_com_height:0.,animation_com_height:0.};
 let result=match mode{
 0..=2=>{let old=a.bone_indices[0];let parents=e.frames.parents.clone();if mode==0{a.bone_indices[0]=usize::MAX;}else if mode==1{e.frames.parents[old]=old as i32;}else{e.frames.parents.fill(-1);}let result=physics::foot_ik::FootIk::load(data,&e.frames,a).map(|_|());a.bone_indices[0]=old;e.frames.parents=parents;result},
 3=>a.process_pose(&[],landing,1./60.,&mut f1,&mut f2,None),4=>{let old=physics::animated_skeleton::replace_target(a,usize::MAX);let result=a.process_pose(&globals,landing,1./60.,&mut f1,&mut f2,None);physics::animated_skeleton::replace_target(a,old);result},
 5=>ik.update(a,&[],physics::foot_ik::PhysicalInput{state_id:201,flags_2468:0,flags_2472:0,flags_2480:0,contact_bone:usize::MAX,physical_board:&IDENTITY,hips_world_position:[0.;4],current_contacts:[None;2]}).map(|_|()),
 6|7=>{let mut input=skate_core::player::input_phase::ProcessedPhysicsInput::default();input.state_2508=500;input.category_2512=500;physics::offboard_pose_adjust::update(a,if mode==6{&[]}else{&globals},[usize::MAX;2],&input)},
 8|9=>{g.target=None;let mut settings=gs.clone();if mode==9{use skate_core::air::trajectory::grind_surface::{LandingOrientation,GeometryType};g.start(grind_air::Target{edge:skate_core::physics::grind_contact::Primitive{start:[0.;4],end:[0.;4],owner:0},primitive_flags:0,orientation:LandingOrientation{kind:GeometryType::ThinRail,garbage:false,boardslide_dir:[0.;4],tipslide_dir:[0.;4],backslash_dir:[0.;4],high_side:[0.;4]}});settings.frames=1;}g.update(grind_air::Input{active:true,board:IDENTITY,velocity:[0.;4],angular_velocity:[0.;4],up:[0.,1.,0.,0.],timestep:1./60.,flags_2468:0,flags_2472:0,flags_2480:0,flags_2484:0},&settings).map(|_|())},
 10=>{let old=a.bone_indices[23];a.bone_indices[23]=usize::MAX;let result=a.process_pose(&globals,landing,1./60.,&mut f1,&mut f2,None);a.bone_indices[23]=old;result},_=>panic!("owner error mode")};adjusted_error_out(out,result);let _=p;
}
fn adjusted_tick(i:&mut ProbeInput,out:&mut Vec<u32>,p:&mut GamePhysics,s:&mut SkaterRuntime,e:&animation_pose::PoseEvaluator,ik:&mut physics::foot_ik::FootIk,g:&mut grind_air::GrindAir,gs:&grind_air::Settings,queries:&mut PlayerInputState){
 let kind=i.word();let dt=i.float();let state=i.word();let category=i.word();let filtered=i.word();let flags2468=i.word();let flags2472=i.word();let flags2476=i.word();let flags2480=i.word();let flags2484=i.word();let contact=i.word();let balance=i.float();let spin=i.float();let lift=i.float();let state_timer=i.float();let wipeout=i.word()!=0;let on_board=i.word()!=0;let offset=i.floats();let time=i.float();let grind_active=i.word()!=0;
 let input=&mut s.player_input.processed;input.timestep_2604=dt;input.state_2508=state;input.category_2512=category;input.player_state_value_2520=filtered;input.flags_2468=flags2468;input.flags_2472=flags2472;input.flags_2476=flags2476;input.flags_2480=flags2480;input.flags_2484=flags2484;input.state_timer_2664=state_timer;input.line_tests_960_1008_1056=[queries.left_line_test_1536,queries.right_line_test_1584,queries.hips_line_test_1488];
 p.board.clear_forces();p.riding.start_wheel_queries(&p.board,&p.world).unwrap();let lines=physics::foot_ik_queries::query(&p.world,&s.skeleton).unwrap();let globals=adjusted_hierarchy(e,kind);let hands=s.animated_skeleton.reparented_hand_indices();physics::offboard_pose_adjust::update(&mut s.animated_skeleton,&globals,hands,&s.player_input.processed).unwrap();
 let input=&mut s.player_input.processed;input.vectors_400_416[0]=four(p.board.bodies()[6].rates.linear_velocity).map(f32::to_bits);input.vectors_720_784_800_816_832_864[0]=four(p.board.bodies()[6].rates.angular_velocity).map(f32::to_bits);input.vectors_544_560_592_608[0]=[0.,1.,0.,0.].map(f32::to_bits);let deck=physics::deck_frame(&p.board);let adjusted=if grind_active{physics::pose_grind_update(g,gs,deck,input,&mut s.animated_skeleton,&globals).unwrap()}else{false};
 let landing=skeleton_landing::LandingInput{filtered_state:filtered,flags_2468:input.flags_2468,flags_2472:input.flags_2472,flags_2476:input.flags_2476,balance,physical_com_velocity_along_up:s.skeleton.record.centre_of_mass_velocity[1],physical_com_height:s.skeleton.record.centre_of_mass[1]-deck[3][1],animation_com_height:0.};let on=on_board.then_some((deck,offset,input.flags_2480,time));s.animated_skeleton.process_pose(&globals,landing,dt,&mut input.flags_2468,&mut input.flags_2472,on).unwrap();s.skeleton_input.deck_velocity=four(p.board.bodies()[6].rates.linear_velocity);for b in s.skeleton.bodies_mut(){if b.state_flags&7==2{b.state_flags=(b.state_flags&8)|4;}b.rates.cool_down=0;}p.riding.finish_wheel_queries().unwrap();
 let input=&mut s.player_input.processed;input.wheel_count_2556=p.riding.ground.wheel_contact_count as u32;input.scalar_2652=p.riding.motion.speed;input.scalar_2616=p.riding.motion.ground_speed;input.vectors_464_480_496_512_528[0]=four(p.riding.ground.wheel_normal).map(f32::to_bits);let dynamic_up=p.riding.ground.overall_normal;p.processed_flags_2468=input.flags_2468;p.riding.update_ground_reckoning(&p.board,physics::riding_outputs::RidingPoseInputs{com_to_deck:s.animated_skeleton.record.com_to_deck(),body_spin:spin},input.flags_2468,balance,false,input);
 let a=&mut s.animated_skeleton;a.board_frames.update_com_lift(&a.roots.animation_to_world,a.animation_hips[3],lift);a.prepare_ground(&p.board,&p.riding.reckoning_frames.system,dt,&mut p.processed_flags_2468);s.skeleton_input.root_velocity=skate_core::physics::skeleton_general::root_velocity(&mut s.skeleton_input.previous_root_position,a.roots.animation_to_world[3],dt);
 let target=s.skeleton_drives.targets.update_positions(SkeletonTargetInput{animation_hips:&a.animation_hips,animation_board:&a.animation_board,animation_to_world:&a.roots.animation_to_world,inverse_board:&a.roots.inverse_board,skate_root:&a.board_frames.skate_root,com_frame:&a.board_frames.com_frame,lifted_com_frame:&a.board_frames.lifted_com_frame,teleporting:false},&mut s.skeleton);s.skeleton_input.animation_board_to_physics=target.animation_board_to_physics;s.skeleton_input.extra_target_positions=[target.positions.com,target.positions.lifted_com,target.positions.following_com];s.pose_errors.set_targets(target.positions);if !target.continuous{reset_physical(p,s);if state!=0&&state!=702{s.skeleton_input.invalid_target_reset=true;}}
 let input=&s.player_input.processed;let physical_board=s.animated_skeleton.board_frames.physical_board;let current_contacts=std::array::from_fn(|foot|(input.line_tests_960_1008_1056[foot].valid!=0).then(||input.line_tests_960_1008_1056[foot].position.map(f32::from_bits)));let drives=ik.update(&s.animated_skeleton,&globals,physics::foot_ik::PhysicalInput{state_id:state,flags_2468:input.flags_2468,flags_2472:input.flags_2472,flags_2480:input.flags_2480,contact_bone:if contact==2{usize::MAX}else{s.animated_skeleton.bone_indices[if contact==0{15}else{19}]},physical_board:&physical_board,hips_world_position:s.skeleton.record.pose[23][3],current_contacts}).unwrap();s.skeleton_input.drive_frames=drives.frames;s.skeleton_drives.update(&drives.frames,s.skeleton_collision.partial_ragdoll,s.collision_feedback.drive_weight);skate_core::physics::skeleton_general::apply_gravity_displacement(&mut s.skeleton,9.81);s.animated_skeleton.finish_ground();lines.publish(queries);
 physics::advance(p,s,[0.;2]).unwrap();let deck=physics::deck_frame(&p.board);let input=&mut s.player_input.processed;
 let toolkit=skate_core::physics::board_toolkit::BoardToolkit::calculate(deck,&p.board.bodies().iter().map(|b|b.inertia.inverse_mass).collect::<Vec<_>>(),0,0.,[0.,1.,0.,0.],[0.,1.,0.,0.]);input.vectors_544_560_592_608[0]=s.animated_skeleton.roots.animation_to_world[1].map(f32::to_bits);input.time_on_ground_2752=p.ticks as f32*dt;p.riding.probes.prepare_wall(input,&toolkit);p.riding.finish_post_physics(&mut p.board,p.board_wiping_out,p.processed_flags_2468,p.settings.step.simulation.time_step).unwrap();let input=&mut s.player_input.processed;input.vectors_464_480_496_512_528[1]=four(p.riding.ground.parts[6].point).map(f32::to_bits);input.vectors_464_480_496_512_528[2]=input.vectors_464_480_496_512_528[1];input.vectors_464_480_496_512_528[4]=four(dynamic_up).map(f32::to_bits);input.vectors_880_896_912_928_944[0]=s.animated_skeleton.animation_hips[3].map(f32::to_bits);input.vectors_880_896_912_928_944[1]=[0.,1.,0.,0.].map(f32::to_bits);physics::publish(p,s);
 let input=&s.player_input.processed;let deck=physics::deck_frame(&p.board);let inverse=s.animated_skeleton.roots.world_to_animation;let post=ik.post_physics(&mut s.skeleton,core_ik::post_physics::Input{state_id:state,category_id:category,board_body_flag_868:p.riding.ground.part_contact_count!=0,wipeout,flags_2468:input.flags_2468,flags_2484:input.flags_2484,value_2664:input.state_timer_2664,state_2520:input.player_state_value_2520,world_to_animation:&inverse,board:&deck});s.skeleton.publish_physical_record(deck);out.extend(post.map(u32::from));for v in ik.physical_toe_positions(&s.skeleton.record){probe_floats(out,v);}out.extend([lines.hips.hit as u32,lines.feet[0].hit as u32,lines.feet[1].hit as u32,adjusted as u32]);p.ticks+=1;
}
fn main(){
 let args=std::env::args().collect::<Vec<_>>();let assets=std::path::Path::new(&args[1]);let data=skate_data::collections::Collections::load(assets).unwrap();let mut e=animation_pose::PoseEvaluator::from_banks(&skate_data::animation_banks::AnimationBanks::load(assets).unwrap()).unwrap();let stock=physics::settings::PhysicsSettings::load(&data).unwrap();let gs=physics::pose_grind_settings(&data).unwrap();let mut bytes=Vec::new();std::io::stdin().read_to_end(&mut bytes).unwrap();let mut i=ProbeInput{words:bytes.chunks_exact(4).map(|b|u32::from_le_bytes(b.try_into().unwrap())).collect(),at:0};let mut out=Vec::new();let cases=i.word();
 for c in 0..cases{let spawn=i.affine();let world=i.world(stock.floor_material);let seams=i.word()!=0;let(mut p,mut s)=make(&data,assets,&e,spawn,world);if seams{p.world.enable_imported_floor_seams();}let mut ik=physics::foot_ik::FootIk::load(&data,&e.frames,&s.animated_skeleton).unwrap();let mut grind=grind_air::GrindAir::default();let mut queries=PlayerInputState::default();let n=i.word();out.extend([c,n,0]);let mark=out.len()-1;let initial=out.len();out.push(0);snapshot(&mut out,&mut p,&mut s);adjusted_loaded(&mut out,&s.animated_skeleton,&ik,&gs);adjusted_out(&mut out,&s.animated_skeleton,&ik,&grind,&queries);out[initial]=(out.len()-initial-1)as u32;
 for _ in 0..n{let op=i.word();out.extend([op,0]);let at=out.len()-1;match op{
 0=>adjusted_tick(&mut i,&mut out,&mut p,&mut s,&e,&mut ik,&mut grind,&gs,&mut queries),1=>ik.enable_feet(i.word()!=0),2=>ik.state.reset(),3=>s.animated_skeleton.board_offset.refresh_transform(i.matrix()),4=>{let h=i.float();let frames=i.float();s.animated_skeleton.board_offset.refresh_height(h,frames);},5=>s.animated_skeleton.finish_ground(),6=>s.animated_skeleton.motion.reset_board_orientation_history(),
 7=>{let limb=i.word()as usize;let mode=i.word();let v:[f32;8]=i.floats();let l=&mut ik.state.limbs[limb];let t=&mut ik.state.external_targets[limb];l.target_blend=v[0];l.external_target_set=mode==1;l.local_target_set=mode==2;t.world_position=[v[1],v[2],v[3],0.];t.animation_position=t.world_position;t.normal=[v[4],v[5],v[6],v[7]];t.normal_set=true;t.normal_blend=0.6;},
 8=>{use skate_core::air::trajectory::grind_surface::{LandingOrientation,GeometryType};let start=i.floats();let end=i.floats();let owner=u64::from(i.word());let primitive_flags=i.word();let kind=match i.word(){0=>GeometryType::ThinRail,1=>GeometryType::FatRail,2=>GeometryType::Ledge,3=>GeometryType::Impossible,_=>panic!("orientation kind")};let garbage=i.word()!=0;let orientation=LandingOrientation{kind,garbage,boardslide_dir:i.floats(),tipslide_dir:i.floats(),backslash_dir:i.floats(),high_side:i.floats()};grind.start(grind_air::Target{edge:skate_core::physics::grind_contact::Primitive{start,end,owner},primitive_flags,orientation});},9=>p.world=i.world(p.settings.floor_material),10=>{s.animated_skeleton.roots.supplied_prediction=Some(i.floats());ik.state.mark_support_failed_this_update();},
 11=>{let root=i.floats();let middle=i.floats();let end=i.floats();let mut solved=i.floats();let mut target=i.floats();let limits=core_ik::two_bone::AngleLimits{minimum_degrees:i.float(),maximum_degrees:i.float()};let override_maximum=i.word()!=0;let budget=i.word();out.push(core_ik::two_bone::solve(root,middle,end,&mut solved,&mut target,limits,override_maximum,budget)as u32);probe_floats(&mut out,solved);probe_floats(&mut out,target);},
 12=>{let parents=std::array::from_fn(|_|{let p=i.word();(p!=u32::MAX).then_some(p as usize)});let frames=i.matrices();let geometry=core_ik::drive::Geometry::new(parents,&frames);out.push(geometry.is_ok()as u32);probe_error(&mut out,geometry.as_ref().err().map(String::as_str).unwrap_or(""));if let Ok(g)=geometry{out.extend(g.parents.map(|p|p.map_or(u32::MAX,|v|v as u32)));for m in g.inverse_part_frames{probe_matrix(&mut out,m);}adjusted_error_out(&mut out,g.validate_limbs(&core_ik::state::LIMBS));}},13=>{let mode=i.word();adjusted_owner_error(mode,&mut out,&mut p,&mut s,&mut ik,&mut grind,&gs,&mut e,&data);},_=>panic!("adjusted command")};snapshot(&mut out,&mut p,&mut s);adjusted_out(&mut out,&s.animated_skeleton,&ik,&grind,&queries);out[at]=(out.len()-at-1)as u32;}out[mark]=(out.len()-mark-1)as u32;}
 assert_eq!(i.at,i.words.len());let mut stdout=std::io::BufWriter::new(std::io::stdout().lock());for w in out{stdout.write_all(&w.to_le_bytes()).unwrap();}
}
