//! Original actor stance state and core packet publication oracle.
#[path="../../crates/skate-host/src/skater_animation/state.rs"] mod state;
use skate_core::animation::{output::{NativeMatrix,attributes::{AnimationAttribute,AttributeName,AttributePayload},physics_packet::{SkaterPublicationState,PhysicsPosePacket,AnimationSignal},packet_reset::{self,AdditionalResetFields}},skeleton_input::name::encode};
use std::io::{Read,Write};
struct Input {bytes:Vec<u8>,at:usize}
impl Input {
 fn word(&mut self)->u32 {let v=u32::from_le_bytes(self.bytes[self.at..self.at+4].try_into().unwrap());self.at+=4;v}
 fn float(&mut self)->f32 {f32::from_bits(self.word())}
 fn boolean(&mut self)->bool {self.word()!=0}
 fn raw(&mut self)->Vec<u8> {let n=self.word() as usize;let out=self.bytes[self.at..self.at+n].to_vec();self.at+=n;out}
 fn matrices(&mut self)->Vec<NativeMatrix> {let n=self.word();(0..n).map(|_|core::array::from_fn(|_|core::array::from_fn(|_|self.float()))).collect()}
 fn publication(&mut self)->SkaterPublicationState {SkaterPublicationState{orientation_bit31:self.boolean(),mirrored:self.boolean(),riding_fakie:self.boolean(),weight_on_nose:self.boolean(),relative_stance:self.word() as i32,natural_stance:self.word() as i32,request_bit16:self.boolean(),request_bit15:self.boolean(),air_dismount_revert_requested:self.boolean(),air_dismount_revert_frames:self.word() as i32,signal:if self.boolean() {Some(AnimationSignal{name_hash:self.word(),active:self.word() as u8})}else {None}}}
 fn packet(&mut self)->PhysicsPosePacket {PhysicsPosePacket{bone_count:self.word(),hierarchy:self.matrices(),local:self.matrices(),timestep:self.float(),foot_surface_ids:[self.word(),self.word()],flags:self.word(),board_flipped:self.boolean(),mirrored:self.boolean(),riding_switch:self.boolean(),riding_fakie:self.boolean(),weight_forwards:self.boolean(),regular_stance:self.boolean(),air_dismount_revert_frames:self.word() as i32}}
 fn reset_fields(&mut self)->AdditionalResetFields {AdditionalResetFields{compression:self.float(),foot_ik_influence:[self.float(),self.float()],next_step_position_valid:self.boolean(),actor_flag_1904_bit23:self.boolean(),actor_flag_1908_bit2:self.boolean(),external_impulse_active:self.boolean(),external_physics_input_active:self.boolean(),externally_controlled:self.boolean(),prevent_manual_respawn:self.boolean(),ignore_respawn_reset_button:self.word() as u8,force_braking:self.boolean(),truck_tightness:self.float(),wheel_hardness:self.float(),auxiliary_vectors:core::array::from_fn(|_|core::array::from_fn(|_|self.float())),requested_physics_mode:self.word()}}
}
fn word(out:&mut Vec<u8>,w:u32) {out.extend(w.to_le_bytes());}
fn raw(out:&mut Vec<u8>,s:&[u8]) {word(out,s.len() as u32);out.extend(s);}
fn status(out:&mut Vec<u8>,r:Result<(),String>) {match r {Ok(())=>word(out,1),Err(e)=>{word(out,0);raw(out,e.as_bytes());}}}
fn matrices(out:&mut Vec<u8>,ms:&[NativeMatrix]) {word(out,ms.len() as u32);for m in ms {for row in m {for f in row {word(out,f.to_bits());}}}}
fn publication(out:&mut Vec<u8>,p:&SkaterPublicationState) {for w in [u32::from(p.orientation_bit31),u32::from(p.mirrored),u32::from(p.riding_fakie),u32::from(p.weight_on_nose),p.relative_stance as u32,p.natural_stance as u32,u32::from(p.request_bit16),u32::from(p.request_bit15),u32::from(p.air_dismount_revert_requested),p.air_dismount_revert_frames as u32,u32::from(p.signal.is_some())] {word(out,w);}if let Some(s)=&p.signal {word(out,s.name_hash);word(out,u32::from(s.active));}}
fn packet(out:&mut Vec<u8>,p:&PhysicsPosePacket) {word(out,p.bone_count);matrices(out,&p.hierarchy);matrices(out,&p.local);for w in [p.timestep.to_bits(),p.foot_surface_ids[0],p.foot_surface_ids[1],p.flags,u32::from(p.board_flipped),u32::from(p.mirrored),u32::from(p.riding_switch),u32::from(p.riding_fakie),u32::from(p.weight_forwards),u32::from(p.regular_stance),p.air_dismount_revert_frames as u32] {word(out,w);}}
fn reset_fields(out:&mut Vec<u8>,r:&AdditionalResetFields) {for w in [r.compression.to_bits(),r.foot_ik_influence[0].to_bits(),r.foot_ik_influence[1].to_bits(),u32::from(r.next_step_position_valid),u32::from(r.actor_flag_1904_bit23),u32::from(r.actor_flag_1908_bit2),u32::from(r.external_impulse_active),u32::from(r.external_physics_input_active),u32::from(r.externally_controlled),u32::from(r.prevent_manual_respawn),u32::from(r.ignore_respawn_reset_button),u32::from(r.force_braking),r.truck_tightness.to_bits(),r.wheel_hardness.to_bits()] {word(out,w);}for v in r.auxiliary_vectors {for f in v {word(out,f.to_bits());}}word(out,r.requested_physics_mode);}
// Actual field-write target for the two extracted actor getters below.
struct MotionTarget {animation:RequestedStanceTarget}
struct RequestedStanceTarget {requested_stance:u32}
struct SkaterAnimation {state:state::AnimationState,motion:MotionTarget}
fn run()->Result<(),String> {
 let mut bytes=Vec::new();std::io::stdin().read_to_end(&mut bytes).unwrap();let mut input=Input{bytes,at:8};let count=input.word();let mut out=Vec::new();
 for _ in 0..count {match input.word() {
  0=>{let mut p=input.packet();let mut f=input.reset_fields();status(&mut out,packet_reset::reset(&mut p,&mut f).map_err(|e|format!("{e:?}")));packet(&mut out,&p);reset_fields(&mut out,&f);},
  1=>{let mut s=input.publication();let mut p=input.packet();let hierarchy=input.matrices();let local=input.matrices();let lo=input.word() as u64;let hi=input.word() as u64;let dt=f64::from_bits(lo|(hi<<32));let name=input.raw();match skate_core::animation::output::physics_packet::publish_evaluated(&mut s,&hierarchy,&local,&mut p,dt,&name) {Ok(v)=>{word(&mut out,1);word(&mut out,v as u32);},Err(e)=>{word(&mut out,0);raw(&mut out,format!("{e:?}").as_bytes());}}publication(&mut out,&s);packet(&mut out,&p);},
  2=>{word(&mut out,skate_core::animation::output::physics_packet::signal_hash(&input.raw()));},
  3=>{let mut actor=SkaterAnimation{state:state::AnimationState::new(input.boolean()),motion:MotionTarget{animation:RequestedStanceTarget{requested_stance:input.word()}}};let n=input.word();word(&mut out,actor.state.flags);word(&mut out,actor.state.phase.to_bits());publication(&mut out,&actor.state.publication);word(&mut out,u32::from(actor.state.mirrored()));word(&mut out,u32::from(actor.state.fakie()));word(&mut out,u32::from(actor.state.switch()));word(&mut out,actor.state.cull_threshold().to_bits());word(&mut out,actor.checkpoint_stance());word(&mut out,actor.motion.animation.requested_stance);for _ in 0..n {match input.word() {0=>{actor.state.flags=input.word();actor.state.publication=input.publication();actor.state.phase=input.float();},1=>{let n=input.word();let attrs:Vec<_>=(0..n).map(|_|AnimationAttribute{name:AttributeName(core::array::from_fn(|_|input.word())),payload:AttributePayload([None;6]),kind:0,status:0,sequence_id:0,begin_time:0.,end_time:0.}).collect();actor.state.apply_stance_events(&attrs);},2=>actor.state.prepare_publication(),3=>actor.state.finish_publication(),4=>actor.request_checkpoint_stance(input.word()),_=>unreachable!()};word(&mut out,actor.state.flags);word(&mut out,actor.state.phase.to_bits());publication(&mut out,&actor.state.publication);word(&mut out,u32::from(actor.state.mirrored()));word(&mut out,u32::from(actor.state.fakie()));word(&mut out,u32::from(actor.state.switch()));word(&mut out,actor.state.cull_threshold().to_bits());word(&mut out,actor.checkpoint_stance());word(&mut out,actor.motion.animation.requested_stance);}},
  _=>unreachable!(),
 }}assert_eq!(input.at,input.bytes.len());std::io::stdout().write_all(&out).map_err(|e|e.to_string())?;Ok(())
}
fn main() {if let Err(e)=run() {eprintln!("{e}");std::process::exit(2);}}
