// The checker prefixes the complete accepted live physical/pose/dispatcher factory.
fn biped_snapshot(out:&mut Vec<u32>,p:&mut GamePhysics,s:&mut SkaterRuntime,ik:&physics::foot_ik::FootIk,input:&physics::animation_input::AnimationInput,wobble:&skate_core::physics::skeleton_output::wobble::Wobble,elapsed:bool,queries:&PlayerInputState,actions:&Actions,biped:&physics::offboard::skeleton_ground::State,board:&physics::skeleton_air::SkeletonAir,air:&physics::air_reckoning::AirReckoning){snapshot(out,p,s);adjusted_out(out,&s.animated_skeleton,ik,&s.skeleton_input.grind_air,queries);observe_dispatcher(out,&s.skeleton_input,input,wobble,elapsed,&s.player_input.processed,actions);physics::offboard::skeleton_ground::migration_observe(out,biped);physics::air_reckoning::migration_biped_observe(out,air);physics::skeleton_air::migration_biped_observe(out,board);physics::air_reckoning::migration_biped_settings(out,air);}
fn biped_solve(out:&mut Vec<u32>,p:&mut GamePhysics,s:&mut SkaterRuntime,ik:&mut physics::foot_ik::FootIk)->Result<(),String>{
 physics::advance(p,s,[0.;2])?;out.push(p.contact_count as u32);out.push(s.solved_drives.as_ref().map_or(0,|b|b.rows.len())as u32);let wheel=p.riding.ground.wheel_normal;let normal=p.riding.ground.overall_normal;let toolkit=skate_core::physics::board_toolkit::BoardToolkit::from_board(&p.board,s.player_input.processed.flags_2468,p.riding.motion.speed,four(normal),four(p.riding.reckoning.ground_normal));let saved=s.player_input.processed;let processed=&mut s.player_input.processed;processed.vectors_464_480_496_512_528[0]=four(wheel).map(f32::to_bits);processed.vectors_544_560_592_608[0]=s.animated_skeleton.roots.animation_to_world[1].map(f32::to_bits);processed.time_on_ground_2752=p.ticks as f32*processed.timestep_2604;p.riding.probes.prepare_wall(processed,&toolkit);p.riding.finish_post_physics(&mut p.board,p.board_wiping_out,p.processed_flags_2468,p.settings.step.simulation.time_step)?;let processed=&mut s.player_input.processed;processed.vectors_464_480_496_512_528[1]=four(p.riding.ground.parts[6].point).map(f32::to_bits);processed.vectors_464_480_496_512_528[2]=processed.vectors_464_480_496_512_528[1];processed.vectors_464_480_496_512_528[4]=four(normal).map(f32::to_bits);processed.vectors_880_896_912_928_944[0]=s.animated_skeleton.animation_hips[3].map(f32::to_bits);processed.vectors_880_896_912_928_944[1]=[0.,1.,0.,0.].map(f32::to_bits);physics::publish(p,s);s.player_input.processed=saved;let deck=physics::deck_frame(&p.board);let processed=&s.player_input.processed;let post=ik.post_physics(&mut s.skeleton,core_ik::post_physics::Input{state_id:processed.state_2508,category_id:processed.category_2512,board_body_flag_868:p.riding.ground.part_contact_count!=0,wipeout:false,flags_2468:processed.flags_2468,flags_2484:processed.flags_2484,value_2664:processed.state_timer_2664,state_2520:processed.player_state_value_2520,world_to_animation:&s.animated_skeleton.roots.world_to_animation,board:&deck});out.extend(post.map(u32::from));s.skeleton.publish_physical_record(deck);p.ticks+=1;Ok(())
}
fn main(){
 let args=std::env::args().collect::<Vec<_>>();let assets=std::path::Path::new(&args[1]);let data=skate_data::collections::Collections::load(assets).unwrap();let mut out=Vec::new();let mut retained=physics::offboard::skeleton_ground::migration_fixture_default();let initial=match physics::offboard::skeleton_ground::State::load(&data){Ok(s)=>{adjusted_error_out(&mut out,Ok(()));retained=s;true},Err(e)=>{adjusted_error_out(&mut out,Err(e));false}};physics::offboard::skeleton_ground::migration_observe(&mut out,&retained);
 if !initial||args.len()>2{let mut stdout=std::io::stdout().lock();for v in out{stdout.write_all(&v.to_le_bytes()).unwrap();}return;}
 let e=animation_pose::PoseEvaluator::from_banks(&skate_data::animation_banks::AnimationBanks::load(assets).unwrap()).unwrap();let stock=physics::settings::PhysicsSettings::load(&data).unwrap();let ws=wobble_settings(&data);let mut bytes=Vec::new();std::io::stdin().read_to_end(&mut bytes).unwrap();let mut i=ProbeInput{words:bytes.chunks_exact(4).map(|b|u32::from_le_bytes(b.try_into().unwrap())).collect(),at:0};let count=i.word();out.push(count);
 for c in 0..count{
  let spawn=i.affine();let world=i.world(stock.floor_material);let seams=i.word()!=0;let(mut p,mut s)=make(&data,assets,&e,spawn,world);if seams{p.world.enable_imported_floor_seams();}let mut ik=physics::foot_ik::FootIk::load(&data,&e.frames,&s.animated_skeleton).unwrap();let mut input=physics::animation_input::AnimationInput::load(&data,&e.frames,"normal").unwrap();let mut biped=physics::offboard::skeleton_ground::State::load(&data).unwrap();let mut board=physics::skeleton_air::SkeletonAir::load(&data).unwrap();let mut air=physics::air_reckoning::AirReckoning::load(&data).unwrap();let mut wobble=skate_core::physics::skeleton_output::wobble::Wobble::default();let mut elapsed=false;let mut queries=PlayerInputState::default();let mut actions=Actions::default();let n=i.word();out.extend([c,n,0]);let mark=out.len()-1;let initial=out.len();out.push(0);biped_snapshot(&mut out,&mut p,&mut s,&ik,&input,&wobble,elapsed,&queries,&actions,&biped,&board,&air);out[initial]=(out.len()-initial-1)as u32;
  for _ in 0..n{
   let op=i.word();out.extend([op,0]);let at=out.len()-1;let payload=out.len();out.push(0);match op{
    0=>{
     let prepared_at=out.len();out.push(0);let prepared=process_dispatcher(&mut i,&mut out,&mut p,&mut s,&e,&mut ik,&mut input,&mut wobble,&ws,&mut queries,&mut actions);out[prepared_at]=prepared as u32;let branch=i.word();let frame=i.matrix();let com=i.floats();let body=i.floats();let lift=i.float();let forward=i.floats();let pose=i.word();let solve=i.word()!=0;let globals=if pose==4{Vec::new()}else{adjusted_hierarchy(&e,pose)};let mut target=IDENTITY;let mut result=Ok(());let mut ok=false;
     if prepared{
      let collision=dispatcher_collision(&s);let saved=s.player_input.processed;let reckoning_settings=biped.migration_reckoning_settings();let spin=input.extra.physical_body_spin;let mut owners=physics::skeleton_input_runtime::SkeletonOwners{animated:&mut s.animated_skeleton,body:&mut s.skeleton,drives:&mut s.skeleton_drives,ik:&mut ik,animation_input:&mut input,correction:&mut s.skeleton_output.correction,pose_errors:&mut s.pose_errors};
      let value=if branch==0{s.skeleton_input.update_biped_ground(&mut board,&mut p.board,physics::offboard::skeleton_ground::Input{world_frame:&frame,centre_of_mass_1056:com},&mut biped,&mut s.player_input.processed,&mut owners,&globals,&collision,p.settings.step.simulation,|update|{reckoning_settings.finish_reckoning(update,&mut p.riding,&mut air,&saved,spin);Ok(())})}else if branch==1{s.skeleton_input.update_biped_air(&mut board,&mut p.board,physics::offboard::skeleton_air::Input{frame_208:frame,trajectory_position_272:com,body_target_416:body,lift_436:lift,board_forward_96:forward},&mut s.player_input.processed,&mut owners,&globals,&collision,p.settings.step.simulation,|update,processed,spin|{biped.finish_reckoning(update,&mut p.riding,&mut air,processed,spin);Ok(())})}else{panic!("branch")};
      result=value.map(|v|{target=v;});p.processed_flags_2468=s.player_input.processed.flags_2468;ok=result.is_ok();if ok&&solve{result=biped_solve(&mut out,&mut p,&mut s,&mut ik);ok=result.is_ok();}
     }
     out.push(ok as u32);probe_error(&mut out,result.as_ref().err().map(String::as_str).unwrap_or(""));probe_matrix(&mut out,target);
    },
    1=>board.capture_physics_error(&p.board,&i.matrix()),2=>board.reset_board(),3=>physics::offboard::skeleton_ground::migration_set_board(&mut biped,i.matrix()),4=>p.world=i.world(p.settings.floor_material),5=>{let mut owners=physics::skeleton_input_runtime::SkeletonOwners{animated:&mut s.animated_skeleton,body:&mut s.skeleton,drives:&mut s.skeleton_drives,ik:&mut ik,animation_input:&mut input,correction:&mut s.skeleton_output.correction,pose_errors:&mut s.pose_errors};s.skeleton_input.reset_for_teleport(&mut owners,&mut s.skeleton_collision,&mut s.collision_feedback,&mut wobble,&mut elapsed);},6=>{let flags=i.word();let cool=i.word();for b in s.skeleton.bodies_mut(){b.state_flags=flags;b.rates.cool_down=cool;}},7=>{let value=skate_core::player::offboard::ground_reckoning::Input{previous_up:i.floats(),requested_up:i.floats(),requested_forward:i.floats(),blend:i.float(),reverse_stance:i.word()!=0,enable_body_spin_input:i.word()!=0,physical_body_spin_2812:i.float()};let v=physics::offboard::skeleton_ground::migration_update(&biped,&mut p.riding,&mut air,value);for x in [v.dynamic_up_1136,v.up_1152,v.target_1168,v.velocity_1184,v.ground_normal_1216]{probe_floats(&mut out,x);}},8=>{air.state.spin_angle=i.float();air.state.spin_speed=i.float();air.state.secondary_lean_angle=i.float();},_=>panic!("biped operation")
   }out[payload]=(out.len()-payload-1)as u32;biped_snapshot(&mut out,&mut p,&mut s,&ik,&input,&wobble,elapsed,&queries,&actions,&biped,&board,&air);out[at]=(out.len()-at-1)as u32;
  }out[mark]=(out.len()-mark-1)as u32;
 }
 assert_eq!(i.at,i.words.len());let mut stdout=std::io::BufWriter::new(std::io::stdout().lock());for v in out{stdout.write_all(&v.to_le_bytes()).unwrap();}
}
