// Appended to original physics.rs: full active source owners and real producers.
mod migration_biped {
use super::*;use crate::{Input,Output};use skate_core::{player::input_phase::*,physics::board_toolkit::BoardToolkit};
fn block(o:&mut Output,f:impl FnOnce(&mut Output)){let at=o.0.len();o.word(0);f(o);o.0[at]=(o.0.len()-at-1)as u32;}
macro_rules! observations{($p:ident,$s:ident)=>{wipeout::Observations{processed:&$s.player_input.processed,board:&$p.riding.ground,collision:&$s.collision_feedback,deck:solve::deck_frame(&$p.board),input_board:$s.animated_skeleton.board_frames.animation_target,world_to_animation:$s.animated_skeleton.roots.world_to_animation,pose_error:$s.collision_pose_error,maximum_pose_error:$s.collision_maximum_error,jump_fix_frames:$s.player_state.post.jump_fix_frames,air:&$s.air_reckoning.state,system_up_y:$p.riding.reckoning_frames.system[1][1],grind_locked_to_middle:$s.trajectory.selector.grind_locked_to_middle(),grind_normal:$s.trajectory.selector.grind_normal()}};}
fn possession(o:&mut Output,p:&GamePhysics,s:&SkaterRuntime){
 let f=s.skateboard_controller.fields;o.words([f.word_444,f.state_448,f.system_on_452 as u32]);let state=&s.board_possession.state;let r=state.retrieval;o.matrix(r.initial_0);o.matrix(r.target_64);o.matrix(r.current_128);o.floats([r.elapsed_192,r.duration_196,r.progress_200,r.weight_204]);for h in state.hands{o.matrix(h.child);o.matrix(h.parent);for w in h.dynamics{o.words(w)}}o.word(state.selected_hand_424);
 offboard::board_manager::runtime::migration_biped_live(o,&s.board_possession_live);o.word(p.board_wiping_out as u32);for m in [p.settings.wheel_material,p.settings.truck_material,p.settings.deck_material]{o.floats([m.static_friction,m.dynamic_friction,m.restitution])}o.word(p.settings.truck_collisions as u32);o.word(p.settings.deck_geometry.children.len()as u32);for c in &p.settings.deck_geometry.children{o.word(c.collision_enabled as u32)}
}
fn snapshot(o:&mut Output,p:&GamePhysics,s:&SkaterRuntime,last:&Option<skate_core::player::offboard::contact_toolkit::Input>,returned:[u32;3]){
 o.word(16);block(o,|o|biped_ground::migration_biped_observe(o,&s.biped_ground));block(o,|o|biped_air::migration_biped_observe(o,&s.biped_air));block(o,|o|crate::biped_contact_out(o,&s.offboard_contact));
 block(o,|o|{crate::biped_selector::owner_out(o,&s.offboard_air_selector,s.offboard_air_selector.core.launch,s.biped_air.state.result);crate::biped_selector::settings_out(o,&s.offboard_air_selector.settings)});
 block(o,|o|offboard::landing_deck::migration_biped_observe(o,&s.landing_deck));block(o,|o|biped_ground::grab_runtime::migration_observe(o,&s.offboard_grab));block(o,|o|crate::observe_BoardPossessionManager(o,&s.offboard_feet));
 block(o,|o|{crate::observe_PhysicalPlayerInput(o,&s.player_input.physical);o.words(returned)});block(o,|o|crate::observe_ProcessedPhysicsInput(o,&s.player_input.processed));
 block(o,|o|{let l=&s.ground_lifecycle;let c=&l.skeleton_controller;o.words([c.effective,c.requested,c.has_request as u32,c.override_enabled as u32,c.flag_18 as u32,l.skeleton_elapsed_16505 as u32,l.board_animated_290 as u32]);o.float(l.manual_drag_2724);o.word(l.edge.is_some()as u32);o.word(l.pending_wall_jump.is_some()as u32)});
 block(o,|o|{o.0.extend(p.board.forces().migration_air_words());o.word(p.contact_count as u32);o.word(p.network_contacts as u32);o.wide(p.ticks);o.word(p.failed as u32)});block(o,|o|crate::observe_SkeletonCollisionFeedback(o,&s.collision_feedback));
 block(o,|o|match observations!(p,s).frame(){Ok(f)=>{o.status(Ok(()));crate::observe_WipeoutFrame(o,&f)},Err(e)=>o.status(Err(e))});
 block(o,|o|{o.word(last.is_some()as u32);if let Some(x)=last{for v in [x.position,x.forward,x.up,x.right,x.velocity,x.animation_up,x.animation_right]{o.floats(v)}}});
 block(o,|o|crate::observe_PlayerInputState(o,&s.player_input.player));block(o,|o|possession(o,p,s));footplant::migration_air_snapshot(o,p,s);
}
fn actual_packet(p:&GamePhysics,s:&mut SkaterRuntime){let x=&mut s.player_input.processed;let v=p.board.bodies()[6].rates.linear_velocity;x.vectors_400_416[0]=[v.x,v.y,v.z,0.].map(f32::to_bits);x.vectors_400_416[1]=x.vectors_400_416[0];x.vectors_544_560_592_608[2]=s.skeleton.record.centre_of_mass.map(f32::to_bits);x.vectors_544_560_592_608[3]=s.skeleton.record.centre_of_mass_velocity.map(f32::to_bits);x.collision_pose_error_736=s.collision_pose_error.map(f32::to_bits);x.effective_anim_transform_192=s.animated_skeleton.roots.animation_to_world.map(|v|v.map(f32::to_bits));let a=&s.player_input.player;x.line_tests_960_1008_1056=[a.left_line_test_1536,a.right_line_test_1584,a.hips_line_test_1488];}
fn solve_feedback(p:&mut GamePhysics,s:&mut SkaterRuntime)->Result<(),String>{solve::advance(p,s,[0.;2])?;let x=&s.player_input.processed;let t=s.player_input.toolkit.as_ref().ok_or("Postphysics wall probe requires the current board toolkit")?;p.processed_flags_2468=x.flags_2468;p.riding.probes.prepare_wall(x,t);p.riding.finish_post_physics(&mut p.board,p.board_wiping_out,p.processed_flags_2468,p.settings.step.simulation.time_step)?;let partial=skateboard_controller::partial_request(&s.skateboard_controller,&p.riding.ground);skeleton_feedback::publish(p,s,partial);p.ticks+=1;Ok(())}
pub(super)fn run(assets:&std::path::Path,fixtures:&std::path::Path,i:&mut Input,o:&mut Output)->Result<(),String>{
 let graphs=crate::graph_runtime::StockGraphs{action:footplant::migration_air_loaded(&fixtures.join("actor.action.reference"))?,motion:footplant::migration_air_loaded(&fixtures.join("actor.motion.reference"))?};let count=i.word();o.word(count);
 for _ in 0..count{
  let mut p=GamePhysics::load_with_terrain(assets,ground::Terrain::Flat)?;p.world=crate::read_biped_world(i)?;
  let n=i.word();let objects=(0..n).map(|_|crate::biped_grab::object(i)).collect();let n=i.word();let bindings=(0..n).map(|_|offboard::grab_scene::MeshAssembly{mesh:i.word(),assembly:i.word()}).collect();p.offboard_grab_scene=offboard::grab_scene::Registry::new(&p.world,objects,bindings)?;
  let mut s=SkaterRuntime::load(assets,&graphs,&p,"normal")?;let mut last=None;let mut returned=[0;3];let n=i.word();o.word(n);snapshot(o,&p,&s,&last,returned);
  for _ in 0..n{let op=i.word();o.word(op);let result=match op{
   0=>{s.player_input.processed=crate::read_ProcessedPhysicsInput(i);s.animation_input.fields.animation_translation=i.floats();s.animation_input.fields.animation_end_com=i.floats();s.animation_input.fields.animation_time=i.float();s.animation_input.fields.magnitude_scale=i.float();s.animation_input.fields.turn_scale=i.float();s.animation_input.fields.cadence_end_percent=i.float();s.animation_input.fields.animation_physics_blend_seconds=i.float();s.animation_input.extra.offboard_magnitude=i.float();s.animation_input.extra.offboard_turn=i.float();s.animation_input.extra.biped_world_x=i.float();s.animation_input.extra.biped_world_z=i.float();s.animation_input.extra.biped_start_angle=i.float();s.animation_input.extra.physical_body_spin=i.float();s.animation_input.extra.look_x=i.float();s.animation_input.extra.look_y=i.float();actual_packet(&p,&mut s);Ok(())},
   1=>{let kind=i.word();let globals=if kind==4{vec![]}else{const POSES:[&str;4]=["RIG_TPOSE","POSTURE_STIFF_POSE","POSTURE_SLOUCH_POSE","POSTURE_BUFF_POSE"];let e=&s.animation.evaluator;e.hierarchy(&e.evaluate(&[skate_core::animation::playback_tree::PoseCommand::Pose{name:POSES[kind as usize].into()}])?)?};s.animation.packet.hierarchy=globals.clone();let x=&mut s.player_input.processed;let deck=solve::deck_frame(&p.board);let landing=skate_core::physics::skeleton_landing::LandingInput{filtered_state:0,flags_2468:x.flags_2468,flags_2472:x.flags_2472,flags_2476:x.flags_2476,balance:0.,physical_com_velocity_along_up:s.skeleton.record.centre_of_mass_velocity[1],physical_com_height:s.skeleton.record.centre_of_mass[1]-deck[3][1],animation_com_height:0.};s.animated_skeleton.process_pose(&globals,landing,x.timestep_2604,&mut x.flags_2468,&mut x.flags_2472,None)},
   2=>{s.player_input.toolkit=if i.word()!=0{let x=&s.player_input.processed;Some(BoardToolkit::from_board(&p.board,x.flags_2468,x.scalar_2612,x.vectors_464_480_496_512_528[0].map(f32::from_bits),[0.,1.,0.,0.]))}else{None};Ok(())},
   3=>biped_air::consume_selector(&p,&mut s),4=>{s.offboard_contact.begin_input();Ok(())},5=>biped_ground::enter(&mut p,&mut s),
   6=>{let c=skate_core::player::offboard::ground_job::ContactSnapshot{readiness:s.offboard_contact.readiness()as i32,prefix:s.offboard_contact.prefix()};biped_ground::update(&mut p,&mut s,&PlayerControls::default(),c).map(|v|last=Some(v))},
   7=>{if let Some(last)=last{offboard::contact_toolkit::StaticScene::new(&p.world).map_err(str::to_owned).and_then(|scene|s.offboard_contact.submit(last,s.player_input.processed.actor_query_2952 as i32,&scene).map_err(str::to_owned)).and_then(|_|biped_ground::submit_geometry(&p,&mut s))}else{Err("No completed Ground toolkit submission".into())}},
   8=>{let frame=observations!(p,s).frame();match frame{Err(e)=>Err(e),Ok(f)=>{let v=s.skeleton_input.root_velocity;let flag=s.collision_feedback.flags.group_8;let force=s.collision_feedback.maximum_group_8_force;biped_ground::post(&mut s,skate_core::player::offboard::ground_lifecycle::CollisionInput{shared:&f,skeleton_velocity_16336:v,contact_flag_4072:flag,contact_force_4056:force});Ok(())}}},
   9=>biped_ground::fill(&s,&s.offboard_feet).map(|v|{let r=biped_ground::publish_fields(v,&mut s.player_input.physical);returned=[r.word_36,r.word_40,r.flag_86 as u32]}),10=>{biped_ground::exit(&mut s);Ok(())},
   11=>biped_air::enter(&p,&mut s),12=>biped_air::update(&mut p,&mut s,&PlayerControls::default()),13=>{let frame=observations!(p,s).frame();match frame{Err(e)=>Err(e),Ok(f)=>biped_air::post(&mut s,f)}},14=>biped_air::fill(&mut s),15=>{biped_air::exit(&mut s);Ok(())},
   16=>{p.board.clear_forces();p.riding.start_wheel_queries(&p.board,&p.world).and_then(|_|p.riding.finish_wheel_queries())},17=>solve_feedback(&mut p,&mut s),18=>foot_ik_queries::query(&p.world,&s.skeleton).map(|v|v.publish(&mut s.player_input.player)),
   19=>{let scene=offboard::grab_scene::Scene::new(&p.world,&p.offboard_grab_scene);s.offboard_grab.execute_queries(&scene)},20=>{let scene=offboard::grab_scene::Scene::new(&p.world,&p.offboard_grab_scene);s.offboard_grab.sync(&scene,skate_core::player::offboard::ground_query::QueryContext{selection_flags_2948:s.player_input.processed.actor_query_2948,matching_id_2952:s.player_input.processed.actor_query_2952 as i32})},
   21=>{let pub_=s.offboard_grab.publish();block(o,|o|{for r in &pub_.records{crate::biped_grab::record_option(o,r.as_ref())}crate::biped_grab::object_option(o,pub_.object)});Ok(())},
   22=>crate::read_biped_world(i).map(|world|p.world=world),23=>{s.offboard_air_selector.reset();Ok(())},24=>{s.biped_ground.reset(&mut s.offboard_contact);Ok(())},25=>{s.ground_lifecycle.skeleton_controller.override_enabled=i.word()!=0;Ok(())},26=>{s.animation.packet.flags=i.word();s.animation.packet.air_dismount_revert_frames=i.word()as i32;Ok(())},27=>{s.skeleton_air.capture_physics_error(&p.board,&s.animated_skeleton.board_frames.animation_target);Ok(())},28=>{s.offboard_contact.refresh();Ok(())},29=>{s.offboard_feet.reset();Ok(())},30=>{s.landing_deck.reset();Ok(())},_=>panic!("Biped owner operation")};o.status(result);snapshot(o,&p,&s,&last,returned);
  }
 }Ok(())
}
}
pub(crate)fn migration_biped_run(a:&std::path::Path,f:&std::path::Path,i:&mut crate::Input,o:&mut crate::Output)->Result<(),String>{migration_biped::run(a,f,i,o)}
pub(crate)fn migration_biped_load(assets:&std::path::Path,invalid:&std::path::Path,o:&mut crate::Output)->Result<(),String>{
 let metadata=skate_data::animation_banks::AnimationBanks::load(assets)?.metadata()?;let stock=skate_data::collections::Collections::load(assets)?;
 let mut ground=biped_ground::Owner::load(&stock,&metadata)?;let mut air=biped_air::BipedAir::load(&stock)?;
 o.status(Ok(()));let at=o.0.len();o.word(0);biped_ground::migration_biped_observe(o,&ground);o.0[at]=(o.0.len()-at-1)as u32;let at=o.0.len();o.word(0);biped_air::migration_biped_observe(o,&air);o.0[at]=(o.0.len()-at-1)as u32;
 let data=skate_data::collections::Collections::load(invalid)?;let result=biped_ground::Owner::load(&data,&metadata).and_then(|g|biped_air::BipedAir::load(&data).map(|a|(g,a)));
 match result{Ok((g,a))=>{ground=g;air=a;o.status(Ok(()))},Err(e)=>o.status(Err(e))}
 let at=o.0.len();o.word(0);biped_ground::migration_biped_observe(o,&ground);o.0[at]=(o.0.len()-at-1)as u32;let at=o.0.len();o.word(0);biped_air::migration_biped_observe(o,&air);o.0[at]=(o.0.len()-at-1)as u32;Ok(())
}
