use physics::{board_ground::*,board_motion_output::BoardMotionOutput,board_probes::*,board_toolkit::BoardToolkit,board_runtime::*,board_step::CollisionBody,contact_feedback::BoardContactReport,drive_frames::*,rigid_body::RetailSimulationStep,mass::default_skateboard_mass_properties,board::BodyId};
use math::{Vector3,Basis3};use std::io::{Read,Write};
struct Input{w:Vec<u32>,at:usize}
impl Input{fn word(&mut self)->u32{let w=self.w[self.at];self.at+=1;w}fn float(&mut self)->f32{f32::from_bits(self.word())}fn vector(&mut self)->Vector3{Vector3::new(self.float(),self.float(),self.float())}fn four(&mut self)->[f32;4]{std::array::from_fn(|_|self.float())}fn matrix(&mut self)->[[f32;4];4]{std::array::from_fn(|_|self.four())}fn transform(&mut self)->RetailAffineTransform{RetailAffineTransform{basis:Basis3{columns:std::array::from_fn(|_|std::array::from_fn(|_|self.float()))},translation:self.vector()}}}
fn floats(o:&mut Vec<u32>,v:impl IntoIterator<Item=f32>){o.extend(v.into_iter().map(f32::to_bits));}
fn vector(o:&mut Vec<u32>,v:Vector3){floats(o,[v.x,v.y,v.z]);}
fn state(o:&mut Vec<u32>,w:&WheelLineState,g:&BoardGroundState){for v in w.normals{vector(o,v);}floats(o,w.distances);o.extend(w.physics_surfaces);o.push(w.minimum_distance.to_bits());for c in g.parts{o.push(c.in_contact as u32);vector(o,c.normal);vector(o,c.point);vector(o,c.relative_velocity);}for v in g.previous_velocities{vector(o,v);}for v in g.accelerations{vector(o,v);}vector(o,g.closing_velocity);floats(o,[g.maximum_closing_speed,g.opposing_contact,g.surface_twelve_height]);o.push(g.collision_flags);vector(o,g.overall_normal);vector(o,g.wheel_normal);o.extend(g.valid_wheel_normals.map(u32::from));o.extend([g.part_contact_count as u32,g.wheel_contact_count as u32,g.time_without_wheel_contact.to_bits()]);floats(o,g.wheel_angular_drag);}
fn probe(o:&mut Vec<u32>,p:BoardProbeState){vector(o,p.start);vector(o,p.point);vector(o,p.normal);o.extend([p.surface_tag,p.hit as u32]);}
fn toolkit(o:&mut Vec<u32>,t:BoardToolkit){for m in [t.deck,t.effective,t.inverse_effective]{for c in m{floats(o,c);}}for v in [t.side,t.up,t.forward,t.horizontal_forward,t.transverse_up,t.forward_velocity,t.travel_direction,t.filtered_normal]{floats(o,v);}floats(o,[t.absolute_speed,t.control_sign,t.total_mass]);}
fn line(o:&mut Vec<u32>,l:WheelLine){vector(o,l.start);vector(o,l.end);}
fn main(){let mut bytes=Vec::new();std::io::stdin().read_to_end(&mut bytes).unwrap();let mut i=Input{w:bytes.chunks_exact(4).map(|b|u32::from_le_bytes(b.try_into().unwrap())).collect(),at:0};let mut o=Vec::new();let cases=i.word();for c in 0..cases{let op=i.word();o.extend([c,op,0]);let size=o.len()-1;
 if op==0{let mut w=WheelLineState::default();let mut g=BoardGroundState::default();if i.word()!=0{w.normals=std::array::from_fn(|_|i.vector());w.distances=std::array::from_fn(|_|i.float());w.physics_surfaces=std::array::from_fn(|_|i.word());w.minimum_distance=i.float();g.previous_velocities=std::array::from_fn(|_|i.vector());g.wheel_normal=i.vector();g.collision_flags=i.word();g.time_without_wheel_contact=i.float();}let n=i.word();o.push(n);state(&mut o,&w,&g);for _ in 0..n{match i.word(){0=>{let hits=std::array::from_fn(|_|if i.word()!=0{Some(WheelLineHit{fraction:i.float(),normal:i.vector(),surface_tag:i.word()})}else{None});w.publish(hits);},1=>{let mut reports=Vec::new();let n=i.word();for _ in 0..n{reports.push(BoardContactReport{part:BodyId::ORDER[i.word() as usize],other:CollisionBody::StaticWorld,is_body_a:true,normal:i.vector(),position:i.vector(),relative_linear_velocity:i.vector(),other_surface:i.word() as u16,normal_force_on_a:Vector3::ZERO,friction_force_on_a:Vector3::ZERO,tangents:[Vector3::ZERO;2]});}let up=i.vector();let angle=i.float();let wiping=i.word()!=0;g.update(&reports,&w,up,angle,wiping);},2=>{let velocities=std::array::from_fn(|_|i.vector());g.sample_accelerations(velocities,i.float());},3=>g.advance_contact_time(i.float()),4=>g=BoardGroundState::default(),_=>panic!()};state(&mut o,&w,&g);}
 }else if op==1{let mut p=BoardProbeState::default();let n=i.word();o.push(n);probe(&mut o,p);for _ in 0..n{match i.word(){0=>p.start(i.vector()),1=>{let hit=if i.word()!=0{Some(BoardProbeHit{point:i.vector(),normal:i.vector(),surface_tag:i.word()})}else{None};p.publish(hit);},2=>p.disable(),_=>panic!()};probe(&mut o,p);line(&mut o,deck_probe(i.vector()));let input=WallLineInput{state:i.word(),contact_normal:i.vector(),skater_up:i.vector(),deck_position:i.vector(),time:i.float()};let result=wall_probe(input);o.push(result.is_some() as u32);if let Some(l)=result{line(&mut o,l);}}
 }else if op==2{let deck=i.matrix();let n=i.word();let masses:Vec<_>=(0..n).map(|_|i.float()).collect();let flags=i.word();let speed=i.float();let normal=i.four();let retained=i.four();toolkit(&mut o,BoardToolkit::calculate(deck,&masses,flags,speed,normal,retained));
 }else if op==3{let authored=authored_body_transforms(AuthoredTransformInputs::STOCK);let sim=RetailSimulationStep::fixed_60_hz(0,0.001,Vector3::new(0.,-9.81,0.));let mut b=BoardRuntime::new(default_skateboard_mass_properties(),authored,i.transform(),sim,BoardMotion::Active);let n=i.word();o.push(n);for _ in 0..n{b.set_transform(i.transform());b.bodies_mut()[6].rates.linear_velocity=i.vector();b.bodies_mut()[6].rates.angular_velocity=i.vector();let up=i.vector();let flags=i.word();let speed=i.float();let normal=i.four();let retained=i.four();for l in wheel_lines(&b,up){line(&mut o,l);}let m=BoardMotionOutput::from_board(&b,up,flags);for v in [m.angular_velocity,m.linear_velocity,m.ground_velocity]{vector(&mut o,v);}floats(&mut o,[m.speed,m.ground_speed,m.forward_speed]);for c in m.effective_basis.columns{floats(&mut o,c);}toolkit(&mut o,BoardToolkit::from_board(&b,flags,speed,normal,retained));}
 }else{panic!()};o[size]=(o.len()-size-1) as u32;}assert_eq!(i.at,i.w.len());let mut stdout=std::io::BufWriter::new(std::io::stdout().lock());for w in o{stdout.write_all(&w.to_le_bytes()).unwrap();}}
