// Appended after the complete frozen Footplant module. All production calls
// execute its unchanged original bodies and concrete physical/skeleton owners.
mod migration {
use super::*;use crate::{Input,Output};
use crate::physics::{GamePhysics,SkaterRuntime,plant_skeleton};
use skate_core::{air::known::{KnownAirFootplantInput,KnownAirTrajectory},math::Vector3,
 physics::{board_toolkit::BoardToolkit,grind_contact::Primitive,board_world::{BoardWorld,WorldTriangle},world_contact::triangle_from_volume,contact::RetailContactMaterial}};
fn block(o:&mut Output,f:impl FnOnce(&mut Output)){let at=o.0.len();o.word(0);f(o);o.0[at]=(o.0.len()-at-1)as u32;}
pub(super) fn result(o:&mut Output,r:QueryResult){o.floats(r.contact_position);o.floats(r.contact_normal);o.floats(r.landing_normal);o.float(r.contact_time);o.matrix(r.contact_transform);o.word(r.contact_frame as u32);o.word(r.surface);o.word(r.geometry);}
fn trajectory(o:&mut Output,t:Trajectory){o.floats(t.position);o.floats(t.velocity);o.floats(t.acceleration);o.float(t.duration);}
fn owner(o:&mut Output,f:&Footplant){o.word(f.enabled as u32);result(o,f.result);o.word(f.selected_toe.map(|v|v as u32).unwrap_or(u32::MAX));for v in [f.candidate,f.hit,f.perform,f.flag_627,f.launch_valid,f.lock_valid,f.contact_active,f.requested]{o.word(v as u32)}o.floats([f.contact_time,f.scalar_596,f.scalar_600,f.target_blend,f.active_elapsed,f.scalar_612]);o.word(f.surface);for v in [f.contact,f.adjusted_contact,f.current_up,f.selected_world,f.selected_record,f.leg_direction]{o.floats(v)}for v in f.vectors_352_368{o.floats(v)}for v in f.curve{o.floats(v)}for v in [f.physical_com,f.animation_com,f.launch_direction,f.locked_target]{o.floats(v)}trajectory(o,f.request);trajectory(o,f.completed_trajectory);}
fn settings(o:&mut Output,s:&Settings){o.floats(s.deck_bounds);o.floats([s.max_leg_angle_error,s.leg_length_on_landing,s.foot_volume_y_offset,s.deck_bounds_y_offset]);o.floats(s.radial_speed_scale.x);o.floats(s.radial_speed_scale.y);o.floats([s.max_horizontal_speed,s.max_descending_speed,s.release_outward_speed,s.end_handle,s.end_angle,s.end_leg_length,s.start_handle,s.min_duration,s.max_duration]);}
fn publication(o:&mut Output,f:&skate_core::player::input_phase::AirOutputFields){o.floats([f.footplant_contact_time_208,f.footplant_duration_212,f.footplant_surface_height_216]);o.word(f.footplant_surface_224);for v in [f.footplant_left_449,f.footplant_right_450,f.flag_447,f.flag_448]{o.word(v as u32)}}
fn snapshot(o:&mut Output,p:&GamePhysics,s:&SkaterRuntime,out:&skate_core::player::input_phase::AirOutputFields){o.word(6);block(o,|o|owner(o,&s.footplant));block(o,|o|settings(o,&s.footplant.settings));block(o,|o|publication(o,out));block(o,|o|{let w=&s.wipeout.state;for v in w.reasons{o.word(v as u32)}o.floats(w.values);o.word(w.count);o.float(w.cooldown);o.word(w.contact_frames as u32);o.float(w.balance);o.word(w.mode)});block(o,|o|s.trajectory.migration_footplant_trace(o));block(o,|o|{for part in s.skeleton_collision.parts{o.word(part.volume_group as u32)}});super::super::handplant::migration_footplant_shared_snapshot(o,p,s);}
fn world(i:&mut Input)->BoardWorld{let triangles=(0..i.word()).map(|_|{let vertices=core::array::from_fn(|_|Vector3::new(i.float(),i.float(),i.float()));let fatness=i.float();let edge_cosines=i.floats();let flags=i.word();let material=RetailContactMaterial{static_friction:i.float(),dynamic_friction:i.float(),restitution:i.float()};WorldTriangle{triangle:triangle_from_volume(vertices,fatness,edge_cosines,flags),material,tag:i.word()}}).collect();BoardWorld::new(triangles)}
fn loaded(path:&std::path::Path)->Result<crate::graph_runtime::LoadedGraph,String>{let source=skate_data::state_graph::StateGraph::load(path).map_err(|e|e.to_string())?;let binding=skate_data::state_graph::binding::Binding::from_graph(&source).map_err(|e|e.to_string())?;let runtime=crate::graph_runtime::CompiledGraph::from_binding(&binding).map_err(|e|e.to_string())?;Ok(crate::graph_runtime::LoadedGraph{source,binding,runtime})}
fn publish(i:&mut Input,s:&mut SkaterRuntime,p:&mut GamePhysics){let x=&mut s.player_input.processed;x.flags_2468=i.word();x.flags_2472=i.word();x.flags_2476=i.word();x.flags_2480=i.word();x.flags_2484=i.word();x.state_2508=i.word();x.category_2512=i.word();x.timestep_2604=i.float();x.gravity_2648=i.float();x.vectors_544_560_592_608[2]=i.floats::<4>().map(f32::to_bits);x.vectors_400_416[0]=i.floats::<4>().map(f32::to_bits);x.vectors_464_480_496_512_528[0]=i.floats::<4>().map(f32::to_bits);x.vectors_544_560_592_608[1]=i.floats::<4>().map(f32::to_bits);x.vectors_544_560_592_608[3]=i.floats::<4>().map(f32::to_bits);p.riding.reckoning_frames.heading=i.floats();x.vectors_544_560_592_608[0]=i.floats::<4>().map(f32::to_bits);}
fn packet(i:&mut Input)->KnownAirFootplantInput{let position=i.floats();let velocity=i.floats();let acceleration=i.floats();let scalar_48=i.float();KnownAirFootplantInput{trajectory:KnownAirTrajectory{position,velocity,acceleration,scalar_48,word_52:0,word_56:0,word_60:0},remaining_collision_time:i.float(),collision_position:i.floats(),landing_normal:i.floats()}}
pub(super) fn run(assets:&std::path::Path,fixtures:&std::path::Path,i:&mut Input,o:&mut Output)->Result<(),String>{
 let graphs=crate::graph_runtime::StockGraphs{action:loaded(&fixtures.join("actor.action.reference"))?,motion:loaded(&fixtures.join("actor.motion.reference"))?};let count=i.word();o.word(count);
 for _ in 0..count{let mut p=GamePhysics::load_with_terrain(assets,super::super::ground::Terrain::Flat)?;p.world=world(i);let edges=(0..i.word()).map(|_|Primitive{start:i.floats(),end:i.floats(),owner:i.wide()}).collect::<Vec<_>>();let mut s=SkaterRuntime::load(assets,&graphs,&p,"normal")?;let mut packet=KnownAirFootplantInput{trajectory:KnownAirTrajectory{position:[0.;4],velocity:[0.;4],acceleration:[0.;4],scalar_48:-1.,word_52:0,word_56:0,word_60:0},remaining_collision_time:0.,collision_position:[0.;4],landing_normal:[0.;4]};let mut out=skate_core::player::input_phase::AirOutputFields::default();let rows=i.word();o.word(rows);snapshot(o,&p,&s,&out);
 for _ in 0..rows{let op=i.word();o.word(op);let mut extra=Vec::new();let result=match op{
 0=>{publish(i,&mut s,&mut p);Ok(())},
 1=>{let kind=i.word();let mut globals=if kind==4{Vec::new()}else{const POSES:[&str;4]=["RIG_TPOSE","POSTURE_STIFF_POSE","POSTURE_SLOUCH_POSE","POSTURE_BUFF_POSE"];let e=&s.animation.evaluator;e.hierarchy(&e.evaluate(&[skate_core::animation::playback_tree::PoseCommand::Pose{name:POSES[if kind==5{0}else{kind as usize}].into()}])?)?};if kind==5{globals.truncate(1)}s.animation.packet.hierarchy=globals.clone();let x=&mut s.player_input.processed;let deck=crate::physics::solve::deck_frame(&p.board);let landing=skate_core::physics::skeleton_landing::LandingInput{filtered_state:0,flags_2468:x.flags_2468,flags_2472:x.flags_2472,flags_2476:x.flags_2476,balance:0.,physical_com_velocity_along_up:s.skeleton.record.centre_of_mass_velocity[1],physical_com_height:s.skeleton.record.centre_of_mass[1]-deck[3][1],animation_com_height:0.};s.animated_skeleton.process_pose(&globals,landing,x.timestep_2604,&mut x.flags_2468,&mut x.flags_2472,None)},
 2=>{packet=packet_read(i);Ok(())},
 3|5=>{let g=p.settings.step.simulation.gravity_acceleration;let frame=FootplantFrame{processed:&s.player_input.processed,toolkit:s.player_input.toolkit.as_ref().expect("caller has real toolkit"),animated:&s.animated_skeleton,body:&s.skeleton,gravity:[g.x,g.y,g.z,0.],world:&p.world,edges:&edges};if op==3{s.footplant.update_candidate(&packet,&frame);Ok(())}else{s.footplant.consume_and_submit(&packet,&frame,&mut s.foot_ik,&mut s.skeleton_collision)}},
 4=>{s.footplant.update_launch(&packet);Ok(())},6=>ground::enter(&mut p,&mut s),
 7=>{s.animation_input.extra.body_adjust=i.floats();ground::update(&mut p,&mut s)},8=>{ground::post_physics(&mut s);Ok(())},
 9=>{if i.word()!=0{s.footplant.full_reset()}else{s.footplant.reset()}Ok(())},
 10=>{out.footplant_contact_time_208=i.float();out.footplant_duration_212=i.float();out.footplant_surface_height_216=i.float();out.footplant_surface_224=i.word();out.footplant_left_449=i.word()as u8;out.footplant_right_450=i.word()as u8;out.flag_447=i.word()as u8;out.flag_448=i.word()as u8;s.footplant.publish(&mut out);Ok(())},
 11=>{let com=i.floats();let velocity=i.floats();extra.push(ground::migration_footplant_start(&mut s.footplant,com,velocity));Ok(())},12=>{let t=i.float();let adjust=i.floats();ground::migration_footplant_adjust(&mut s.footplant,t,adjust);Ok(())},
 13=>{s.footplant.selected_toe=if i.word()==0{None}else{Some(i.word()as usize)};Ok(())},
 14=>{use skate_core::player::offboard::{air_selector::ledge::filter_edges,ground_query::Edge};let edges=(0..i.word()).map(|_|Edge{start:Vector3::new(i.float(),i.float(),i.float()),end:Vector3::new(i.float(),i.float(),i.float())}).collect::<Vec<_>>();let reference=i.floats();let filtered=filter_edges(&edges,reference);extra.push(filtered.len()as u32);for e in filtered{for v in [e.start,e.end]{extra.extend([v.x.to_bits(),v.y.to_bits(),v.z.to_bits()]);}}Ok(())},
 15=>{s.footplant.update_pose(&packet,&s.animated_skeleton,&mut s.foot_ik,&mut s.skeleton_collision);Ok(())},
 16=>{s.player_input.toolkit=if i.word()!=0{let x=&s.player_input.processed;Some(BoardToolkit::from_board(&p.board,x.flags_2468,x.scalar_2612,x.vectors_464_480_496_512_528[0].map(f32::from_bits),[0.,1.,0.,0.]))}else{None};Ok(())},
 17=>{let x=&mut s.player_input.processed;x.state_variant_index_2528=i.word();x.state_2504=i.word();x.external_physics_1616.flags=i.word();x.transition_2636=i.float();x.prepared_jump_704=i.floats::<4>().map(f32::to_bits);Ok(())},
 18=>{s.trajectory.selector.reset();Ok(())},_=>panic!("Footplant wire operation")};o.status(result);o.word(extra.len()as u32);o.0.extend(extra);snapshot(o,&p,&s,&out);
 }
 }Ok(())
}
fn packet_read(i:&mut Input)->KnownAirFootplantInput{packet(i)}
}
pub(crate) fn migration_footplant_run(assets:&std::path::Path,fixtures:&std::path::Path,i:&mut crate::Input,o:&mut crate::Output)->Result<(),String>{migration::run(assets,fixtures,i,o)}
