use riding::{push::{PushInput,PushLimits,PushAcceleration,calculate_acceleration,enqueue_push},braking::{BrakeInput,BrakeSettings,LinearDragInput,LinearDragSettings,calculate_braking,calculate_linear_drag},speed_model::{SpeedModelSettings,SpeedModelState,SpeedModelInput,update},grounded::propulsion::{GroundPropulsionInput,GroundPropulsionSettings,PropulsionSubmission,calculate}};
use physics::{force_queue::{BoardForceQueue,QueuedPointForce},manual::controller::ManualEffect};
use physics::manual::{controller::{self as manual,ManualInput,ManualAngleMeasurement,ManualError},settings::{ManualSettings,ManualGains,ManualMode},state::ManualState,angle};
use math::Vector3;use point_graph::PointGraph;use std::io::{Read,Write};
struct Input { words:Vec<u32>,at:usize }
impl Input {
 fn word(&mut self)->u32{let v=self.words[self.at];self.at+=1;v}
 fn float(&mut self)->f32{f32::from_bits(self.word())}
 fn three(&mut self)->Vector3{Vector3::new(self.float(),self.float(),self.float())}
 fn four(&mut self)->[f32;4]{std::array::from_fn(|_|self.float())}
 fn curve(&mut self)->PointGraph<8>{PointGraph{x:std::array::from_fn(|_|self.float()),y:std::array::from_fn(|_|self.float())}}
 fn push(&mut self)->PushInput{PushInput{flags_2468:self.word(),flags_2472:self.word(),target_speed:self.float(),current_speed:self.float(),absolute_body_speed:self.float(),scale:self.float(),delta_seconds:self.float(),direction:self.three()}}
 fn limits(&mut self)->PushLimits{PushLimits{maximum_pushable_speed:self.float(),low_speed_change:self.float(),high_speed_change:self.float()}}
 fn brake(&mut self)->BrakeInput{BrakeInput{flags_2468:self.word(),input_2728:self.float(),signed_speed:self.float(),absolute_body_speed:self.float(),surface_factor:self.float(),direction:self.three()}}
 fn brakes(&mut self)->BrakeSettings{BrakeSettings{input_force:self.float(),override_force:self.float(),minimum_speed:self.float()}}
 fn speed_settings(&mut self)->SpeedModelSettings{SpeedModelSettings{negative_gain:self.float(),maximum_gravity_acceleration:self.float(),gravity:self.float(),positive_gain:self.float(),coffin_acceleration:self.float(),speed_error_bound:self.float(),surface_friction:self.curve(),manual_acceleration:self.float(),negative_manual_angle_limit:self.float(),manual_angle_limit:self.float(),no_input_delay:self.float(),no_input_friction:self.curve(),manual_friction:self.curve(),override_enabled:self.word()!=0,override_speed:self.float(),normal_threshold:self.four(),override_direction_threshold:self.four()}}
 fn speed_input(&mut self)->SpeedModelInput{SpeedModelInput{flags_2468:self.word(),flags_2476:self.word(),wheel_contact_count:self.word() as i32,frames_2580:self.word() as i32,timestep:self.float(),signed_speed:self.float(),angle_2652:self.float(),surface_speed:self.float(),turn_2672:self.float(),balance:self.float(),elapsed_without_input:self.float(),manual_state_276:self.float(),vector_160:self.four(),vector_352:self.four(),velocity_416:self.four(),normal_464:self.four(),effective_forward:self.four(),mass:self.float()}}
 fn ground_input(&mut self)->GroundPropulsionInput{GroundPropulsionInput{flags_2468:self.word(),flags_2472:self.word(),target_speed:self.float(),signed_speed:self.float(),absolute_body_speed:self.float(),scalar_2660:self.float(),timestep:self.float(),brake_input:self.float(),push_direction:self.three(),brake_direction:self.three(),surface_braking_factor:self.float()}}
 fn ground_settings(&mut self)->GroundPropulsionSettings{GroundPropulsionSettings{braking:self.brakes(),maximum_pushable_speed:self.float(),mode_speed_changes:[self.float(),self.float()]}}
 fn manual_settings(&mut self)->ManualSettings{ManualSettings{noise_vs_speed:self.curve(),torque_scale_without_contact:self.float(),torque_bleed_without_contact:self.float(),start_torque_scale:self.float(),procedural_noise_scale:self.float(),procedural_noise_frequency:self.float(),powerslide:ManualGains{proportional:self.float(),integral:self.float(),derivative:self.float()},manual:ManualGains{proportional:self.float(),integral:self.float(),derivative:self.float()},maximum_tilt_degrees:self.float(),maximum_angle_error:self.float(),derivative_limit:self.float(),brake_tilt_degrees:self.float(),animation_noise_scale:self.float()}}
 fn manual_input(&mut self)->ManualInput{ManualInput{balance:self.float(),flipped_controls:self.float(),procedural_noise_time:self.float(),absolute_speed:self.float(),animation_noise:self.float(),timestep:self.float(),powersliding:self.word()!=0,braking:self.word()!=0,positive_balance_contact:self.word()!=0,negative_balance_contact:self.word()!=0,reversed_point_selection:self.word()!=0,reference_x:self.four(),reference_z:self.four(),deck_z:self.four(),velocity_frame_z:self.four(),angular_velocity_world:self.four(),correction_point_7888:self.four(),correction_point_7952:self.four()}}
}
fn floats(o:&mut Vec<u32>,v:impl IntoIterator<Item=f32>){o.extend(v.into_iter().map(f32::to_bits));}
fn vector(o:&mut Vec<u32>,v:Vector3){floats(o,[v.x,v.y,v.z]);}
fn force(o:&mut Vec<u32>,f:QueuedPointForce){o.push(f.tag);vector(o,f.force_world);vector(o,f.point_body);}
fn push(o:&mut Vec<u32>,p:PushAcceleration){vector(o,p.vector);vector(o,p.local_point);o.push(p.suppressed as u32);}
fn queue(o:&mut Vec<u32>,q:&BoardForceQueue){o.push(q.entries().len() as u32);for &f in q.entries(){force(o,f);}}
fn manual_state(o:&mut Vec<u32>,s:ManualState){floats(o,[s.filtered_angle_error,s.target_angle,s.measured_angle,s.angular_correction,s.elapsed]);}
fn manual_effect(o:&mut Vec<u32>,e:ManualEffect){for v in [e.angular_displacement,e.force_world,e.force_point_body,e.corrective_force_world,e.corrective_point_body]{floats(o,v);}o.extend([e.correction_active as u32,e.opposing_motion_without_correction as u32]);}
struct Measurement { mode:u32,supplied:f32,calls:u32,last:[[f32;4];3] }
impl ManualAngleMeasurement for Measurement {type Error=String;fn angle_between(&mut self,a:[f32;4],b:[f32;4],axis:[f32;4])->Result<f32,String>{self.calls+=1;self.last=[a,b,axis];if self.mode==1{return Err("probe manual measurement unavailable".to_string());}if self.mode==2{return Ok(self.supplied);}Ok(riding::collision_response::signed_angle(Vector3::new(a[0],a[1],a[2]),Vector3::new(b[0],b[1],b[2]),Vector3::new(axis[0],axis[1],axis[2])))}}
fn measurement(o:&mut Vec<u32>,m:&Measurement){o.push(m.calls);for v in m.last{floats(o,v);}}
fn main(){
 let mut bytes=Vec::new();std::io::stdin().read_to_end(&mut bytes).unwrap();let mut i=Input{words:bytes.chunks_exact(4).map(|b|u32::from_le_bytes(b.try_into().unwrap())).collect(),at:0};let mut o=Vec::new();let count=i.word();
 for c in 0..count {let op=i.word();o.extend([c,op,0]);let mark=o.len()-1;match op {
  0=>{let input=i.push();push(&mut o,calculate_acceleration(input,i.limits()));},
  1=>{let input=i.brake();force(&mut o,calculate_braking(input,i.brakes()));},
  2=>{let input=LinearDragInput{flags_2468:i.word(),absolute_body_speed:i.float(),balance_2720:i.float(),scalar_2724:i.float(),comparison_scalar:i.float()};let settings=LinearDragSettings{brake_speed:i.float(),balance_speed:i.float(),comparison_threshold:i.float(),balance_drag:i.float()};o.push(calculate_linear_drag(input,settings).to_bits());},
  3=>{let settings=i.speed_settings();let mut state=SpeedModelState{target_speed:i.float(),flags_1360:i.word()};o.extend([state.target_speed.to_bits(),state.flags_1360]);let steps=i.word();o.push(steps);for _ in 0..steps{state.flags_1360|=i.word();floats(&mut o,update(&mut state,&settings,&i.speed_input()));o.extend([state.target_speed.to_bits(),state.flags_1360]);}},
  4=>{let mut q=BoardForceQueue::default();let fill=i.word();for _ in 0..fill{assert!(q.append(QueuedPointForce{tag:i.word(),force_world:i.three(),point_body:i.three()}));}queue(&mut o,&q);let steps=i.word();o.push(steps);for _ in 0..steps{if i.word()!=0{q.clear();}let input=i.ground_input();let settings=i.ground_settings();let mut suppressed=i.word() as u8;let active=i.word()!=0;let manual=ManualEffect{angular_displacement:[0.;4],force_world:[0.;4],force_point_body:[0.;4],corrective_force_world:i.four(),corrective_point_body:i.four(),correction_active:active,opposing_motion_without_correction:false};let result=calculate(input,settings,&mut suppressed);o.push(suppressed as u32);force(&mut o,result.braking);push(&mut o,result.push);match result.submit(&manual,&mut q){PropulsionSubmission::ManualCorrection(v)=>o.extend([1,v as u32]),PropulsionSubmission::BrakingAndPush(v)=>o.extend([0,v[0] as u32,v[1] as u32])};queue(&mut o,&q);
}},
  5=>{let input=i.push();let limits=i.limits();let count=i.word();let masses=(0..count).map(|_|i.float()).collect::<Vec<_>>();let mut q=BoardForceQueue::default();push(&mut o,enqueue_push(input,limits,&masses,&mut q));queue(&mut o,&q);},
  6=>{match angle::normalize(i.float()){Ok(v)=>o.extend([1,v.to_bits()]),Err(_)=>o.extend([0,12.75f32.to_bits()])};},
  7=>{
   let settings=i.manual_settings();let mode=ManualMode{correction_angular_speed_threshold:i.float(),corrective_force_enabled:i.word()!=0};let mut state=ManualState{filtered_angle_error:i.float(),target_angle:i.float(),measured_angle:i.float(),angular_correction:i.float(),elapsed:i.float()};let mut m=Measurement{mode:0,supplied:0.,calls:0,last:[[0.;4];3]};manual_state(&mut o,state);measurement(&mut o,&m);let steps=i.word();o.push(steps);
   for _ in 0..steps{let cmd=i.word();o.push(cmd);match cmd{0=>state.reset(),1=>{let category=i.word();let result=state.enter_ground(category,i.float());o.push(match result{physics::manual::state::ManualEntryContinuation::Continue=>0,physics::manual::state::ManualEntryContinuation::RemoveVelocityIntoGround=>1});},2=>{m.mode=i.word();m.supplied=i.float();let input=i.manual_input();match manual::calculate(&mut state,&settings,mode,&input,&mut m){Ok(e)=>{o.push(1);manual_effect(&mut o,e);},Err(e)=>o.extend([0,match e{ManualError::Angle(_)=>0,ManualError::Measurement(_)=>1}])};},_=>panic!("Manual command")};manual_state(&mut o,state);measurement(&mut o,&m);}
  },
  _=>panic!("Unknown speed/propulsion operation")};o[mark]=(o.len()-mark-1) as u32;
 }assert_eq!(i.at,i.words.len());let mut stdout=std::io::BufWriter::new(std::io::stdout().lock());for w in o{stdout.write_all(&w.to_le_bytes()).unwrap();}
}
