// Appended to the complete frozen GroundAnimation module. All production
// lifecycle, force, jump, skeleton and selector methods execute unchanged.
mod migration {
use super::*;
use crate::{Input,Output};
use skate_core::{air::ground_jump::{GroundJumpInput,GroundJumpMode},physics::{board_toolkit::BoardToolkit,force_queue::QueuedPointForce,board_world::{BoardWorld,WorldTriangle},world_contact::triangle_from_volume,contact::RetailContactMaterial}};
fn block(o:&mut Output,f:impl FnOnce(&mut Output)){let at=o.0.len();o.word(0);f(o);o.0[at]=(o.0.len()-at-1)as u32;}
fn vector(o:&mut Output,v:Vector3){o.floats([v.x,v.y,v.z]);}
fn jump(o:&mut Output,v:GroundJump){o.floats(v.velocity);o.float(v.scalar_16);o.word(v.active as u32);}
fn settings(o:&mut Output,a:&GroundAnimationSettings){let s=&a.jump;o.floats(s.vertical_response.x);o.floats(s.vertical_response.y);for g in [&s.y_scalar_vs_normal_y,&s.speed_scalar_vs_angle,&s.minimum_height_vs_speed,&s.maximum_height_vs_speed]{o.floats(g.x);o.floats(g.y);}o.floats([s.speed_response_max_speed,s.minimum_scalar,s.maximum_y_bonus,s.adjust_z_factor,s.adjust_x_factor,s.absolute_minimum_height,s.hippy_minimum_height,s.hippy_maximum_height]);for m in a.modes{o.floats([m.minimum_height_64,m.minimum_height_68,m.maximum_height]);}}
fn snapshot(o:&mut Output,p:&GamePhysics,s:&SkaterRuntime,out:&AirOutputFields){
 o.word(6);
 block(o,|o|{let g=&s.ground_animation;jump(o,g.jump);o.word(g.launched as u32);o.floats(g.launch_velocity)});
 block(o,|o|settings(o,&s.ground_animation_settings));
 block(o,|o|{let g=&s.ground.steering;o.float(g.deck_tilt);o.floats(g.targets);o.floats(g.activation_time);let l=&s.ground_lifecycle;o.word(l.skeleton_elapsed_16505 as u32);o.word(l.board_animated_290 as u32);o.float(l.manual_drag_2724);o.word(s.wipeout.state.mode);o.float(s.wipeout.state.balance);o.word(s.skeleton_output.correction.pending as u32);});
 block(o,|o|{for m in [p.settings.wheel_material,p.settings.standard_wheel_material]{o.floats([m.static_friction,m.dynamic_friction,m.restitution]);}for b in p.board.bodies(){o.float(b.inertia.linear_drag)}for b in p.board.bodies(){vector(o,b.rates.linear_velocity)}});
 block(o,|o|{let q=p.board.forces().entries();o.word(q.len()as u32);for v in q{o.word(v.tag);vector(o,v.force_world);vector(o,v.point_body)}});
 block(o,|o|{o.word(s.ground_runtime.collision_force.is_some()as u32);if let Some(v)=s.ground_runtime.collision_force{for v in [v.force_2528,v.point_2544,v.vector_2592]{o.floats(v)}}});
 super::super::footplant::migration_ground_snapshot(o,p,s,out);
}
fn world(i:&mut Input)->BoardWorld{let triangles=(0..i.word()).map(|_|{let vertices=core::array::from_fn(|_|Vector3::new(i.float(),i.float(),i.float()));let fatness=i.float();let edge_cosines=i.floats();let flags=i.word();let material=RetailContactMaterial{static_friction:i.float(),dynamic_friction:i.float(),restitution:i.float()};WorldTriangle{triangle:triangle_from_volume(vertices,fatness,edge_cosines,flags),material,tag:i.word()}}).collect();BoardWorld::new(triangles)}
fn loaded(path:&std::path::Path)->Result<crate::graph_runtime::LoadedGraph,String>{let source=skate_data::state_graph::StateGraph::load(path).map_err(|e|e.to_string())?;let binding=skate_data::state_graph::binding::Binding::from_graph(&source).map_err(|e|e.to_string())?;let runtime=crate::graph_runtime::CompiledGraph::from_binding(&binding).map_err(|e|e.to_string())?;Ok(crate::graph_runtime::LoadedGraph{source,binding,runtime})}
fn publish(i:&mut Input,s:&mut SkaterRuntime,p:&mut GamePhysics){let x=&mut s.player_input.processed;x.flags_2468=i.word();x.flags_2472=i.word();x.flags_2476=i.word();x.flags_2480=i.word();x.flags_2484=i.word();x.flags_2488=i.word();x.state_variant_index_2528=i.word();x.state_2504=i.word();x.state_2508=i.word();x.category_2512=i.word();x.external_physics_1616.flags=i.word();x.wheel_count_2556=i.word();x.timestep_2604=i.float();x.gravity_2648=i.float();x.scalar_2612=i.float();x.scalar_2616=i.float();x.scalar_2652=i.float();x.scalar_2656=i.float();x.state_timer_2664=i.float();x.scalar_2764=i.float();x.transition_2636=i.float();s.ground_lifecycle.manual_drag_2724=i.float();s.animation_input.fields.balance=i.float();s.animation_input.fields.brake=i.float();s.animation_input.extra.physical_body_spin=i.float();s.animation_input.extra.jump_strength=i.float();s.animation_input.extra.jump_controls=i.floats();p.trainer.pop=i.float();for v in &mut x.vectors_400_416{*v=i.floats::<4>().map(f32::to_bits)}for v in &mut x.vectors_464_480_496_512_528{*v=i.floats::<4>().map(f32::to_bits)}for v in &mut x.vectors_544_560_592_608{*v=i.floats::<4>().map(f32::to_bits)}x.prepared_jump_704=i.floats::<4>().map(f32::to_bits);x.animation_com_to_deck_752=i.floats::<4>().map(f32::to_bits);x.collision_pose_error_736=i.floats::<4>().map(f32::to_bits);}
fn jump_input(i:&mut Input)->GroundJumpInput{GroundJumpInput{flags_2468:i.word(),flags_2480:i.word(),flags_2484:i.word(),flags_2488:i.word(),effective_forward:i.floats(),forward:i.floats(),current_velocity:i.floats(),ground_reference_position:i.floats(),reference_up:i.floats(),filtered_ground_normal:i.floats(),animation_com_position:i.floats(),prepared_velocity:i.floats(),jump_strength:i.float(),jump_controls:i.floats(),gravity_y:i.float(),surface_speed:i.float()}}
pub(super) fn run(assets:&std::path::Path,fixtures:&std::path::Path,i:&mut Input,o:&mut Output)->Result<(),String>{
 let graphs=crate::graph_runtime::StockGraphs{action:loaded(&fixtures.join("actor.action.reference"))?,motion:loaded(&fixtures.join("actor.motion.reference"))?};let count=i.word();o.word(count);
 for _ in 0..count{let mut p=GamePhysics::load_with_terrain(assets,super::super::ground::Terrain::Flat)?;p.world=world(i);let mut s=SkaterRuntime::load(assets,&graphs,&p,"normal")?;s.ground_settings=std::sync::Arc::new(s.ground_profiles.select(1,1)?.tuned(p.trainer));let mut out=AirOutputFields::default();let rows=i.word();o.word(rows);snapshot(o,&p,&s,&out);
 for _ in 0..rows{let op=i.word();o.word(op);let mut extra=Output(Vec::new());let result=match op{
 0=>{publish(i,&mut s,&mut p);Ok(())},
 1=>{let kind=i.word();let mut globals=if kind==4{Vec::new()}else{const POSES:[&str;4]=["RIG_TPOSE","POSTURE_STIFF_POSE","POSTURE_SLOUCH_POSE","POSTURE_BUFF_POSE"];let e=&s.animation.evaluator;e.hierarchy(&e.evaluate(&[skate_core::animation::playback_tree::PoseCommand::Pose{name:POSES[if kind==5{0}else{kind as usize}].into()}])?)?};if kind==5{globals.truncate(1)}s.animation.packet.hierarchy=globals.clone();let x=&mut s.player_input.processed;let deck=crate::physics::solve::deck_frame(&p.board);let landing=skate_core::physics::skeleton_landing::LandingInput{filtered_state:0,flags_2468:x.flags_2468,flags_2472:x.flags_2472,flags_2476:x.flags_2476,balance:0.,physical_com_velocity_along_up:s.skeleton.record.centre_of_mass_velocity[1],physical_com_height:s.skeleton.record.centre_of_mass[1]-deck[3][1],animation_com_height:0.};s.animated_skeleton.process_pose(&globals,landing,x.timestep_2604,&mut x.flags_2468,&mut x.flags_2472,None)},
 2=>{s.player_input.toolkit=if i.word()!=0{let x=&s.player_input.processed;Some(BoardToolkit::from_board(&p.board,x.flags_2468,x.scalar_2612,x.vectors_464_480_496_512_528[0].map(f32::from_bits),x.vectors_544_560_592_608[0].map(f32::from_bits)))}else{None};Ok(())},
 3=>enter(&mut p,&mut s),4=>advance(&mut p,&mut s),5=>exit(&mut p,&mut s),
 6=>{out.jump_velocity_delta_112=core::array::from_fn(|_|i.word());out.launch_velocity_128=core::array::from_fn(|_|i.word());out.launched_442=i.word()as u8;s.ground_animation.fill(&s.player_input.processed,&mut out);extra.words(out.jump_velocity_delta_112);extra.words(out.launch_velocity_128);extra.word(out.launched_442 as u32);Ok(())},
 7=>{p.board.forces_mut().clear();Ok(())},8=>{let tag=i.word();p.board.forces_mut().append(QueuedPointForce{tag,force_world:Vector3::new(i.float(),i.float(),i.float()),point_body:Vector3::new(i.float(),i.float(),i.float())});Ok(())},
 9=>{s.ground_animation.jump.velocity=i.floats();s.ground_animation.jump.scalar_16=i.float();s.ground_animation.jump.active=i.word()!=0;s.ground_animation.launched=i.word()!=0;s.ground_animation.launch_velocity=i.floats();Ok(())},
 10=>{board::set_drag(&mut p,i.float());Ok(())},11=>{let mode=i.word();jump(&mut extra,skate_core::air::ground_jump::calculate(jump_input(i),s.ground_animation_settings.modes[mode as usize],&s.ground_animation_settings.jump));Ok(())},
 12=>{let mode=i.word();let surface=i.word();s.ground_profiles.select(mode,surface).map(|selected|s.ground_settings=std::sync::Arc::new(selected.tuned(p.trainer)))},
 13=>{let data=skate_data::collections::Collections::load(assets)?;super::super::air_trajectory::AirTrajectoryRuntime::load(&data).map(|a|s.trajectory=a)},14=>{s.trajectory.bind_grind_world(std::sync::Arc::clone(&p.grind_world));Ok(())},
 15=>{let index=i.word();let data=skate_data::collections::Collections::load(&fixtures.join(format!("load-{index}"))).map_err(|e|e.to_string())?;GroundAnimationSettings::load(&data).map(|v|s.ground_animation_settings=v)},
 16=>{s.skeleton_air.capture_physics_error(&p.board,&s.animated_skeleton.board_frames.animation_target);Ok(())},17=>{s.ground.steering.deck_tilt=i.float();s.ground.steering.targets=i.floats();s.ground.steering.activation_time=i.floats();s.wipeout.state.mode=i.word();s.wipeout.state.balance=i.float();s.ground_lifecycle.skeleton_elapsed_16505=i.word()!=0;s.ground_lifecycle.board_animated_290=i.word()as u8;Ok(())},_=>panic!("GroundAnimation wire operation")};o.status(result);o.word(extra.0.len()as u32);o.0.extend(extra.0);snapshot(o,&p,&s,&out);
 }
 }Ok(())
}
}
pub(crate) fn migration_ground_animation_run(assets:&std::path::Path,fixtures:&std::path::Path,i:&mut crate::Input,o:&mut crate::Output)->Result<(),String>{migration::run(assets,fixtures,i,o)}
