// Complete original Ground owners are inserted byte-for-byte by the checker.
use skate_core::{point_graph::PointGraph,physics::manual::{controller::ManualInput,state::ManualState,settings::{ManualSettings,ManualMode,ManualGains}},riding::{steering::{SteeringInput,SteeringSettings,TruckSteeringState},speed_wobble::{SpeedWobbleInput,SpeedWobbleSettings},ground_force::GroundForceSettings,ground_contact_response::WallRidePhysical,collision_response::{CollisionResponseSettings,CollisionResponsePhysical},grounded::{propulsion::{GroundPropulsionInput,GroundPropulsionSettings},drag::GroundDragInput,state::{board::GroundBoardOutcome,data::PhysicsGroundState,board_types::*,corrections::*}},braking::{BrakeSettings,LinearDragSettings},speed_model::{SpeedModelInput,SpeedModelSettings,SpeedModelState},slide_friction::{SlideFrictionInput,SlideFrictionSettings},straighten::{StraightenInput,StraightenSettings},heading::{HeadingInput,HeadingSettings},anti_flip::{AntiFlipInput,AntiFlipSettings},pumping::{PumpForceInput,state::PumpingState,settings::{PumpingSettings,PumpingMode}}},air::trajectory::{LaunchInfo,SelectorInput}};
use physics::ground_runtime::{GroundSettings,GroundLaunchInfo,GroundLaunchPhysical};
use tuning::TrainerTuning;
type Vector=[f32;4];type Transform=[[f32;4];4];
struct GroundAirDistances{grind_lock_distance:[f32;5]}
impl Input<'_>{fn three(&mut self)->Vector3{Vector3::new(self.float(),self.float(),self.float())}fn matrix(&mut self)->Transform{std::array::from_fn(|_|self.floats())}fn curve<const N:usize>(&mut self)->PointGraph<N>{PointGraph{x:self.floats(),y:self.floats()}}}
impl Output{fn vector(&mut self,v:Vector3){self.floats([v.x,v.y,v.z]);}}
// GENERATED_GROUND_PROTOCOL
// CACHE_PRIVACY_BEGIN
pub fn seed(owner:&mut Owner,seed:u32,flags:u8){
 use skate_core::player::offboard::{grab_scene::Geometry,ground_sync::{Bounds,BoardLimits}};
 fn record(seed:u32)->Record{let words=std::array::from_fn(|n|seed.wrapping_mul(101).wrapping_add((n as u32)*17));let geometry=Geometry{id:seed+1,word_60:seed^0xa5a55a5a,points:(0..1+seed%4).map(|n|[seed as f32*0.125,n as f32*0.25,-(n as f32)*0.5,0.]).collect(),approach_vectors:(0..seed%3).map(|n|[n as f32*0.25,1.,0.,-0.]).collect()};Record(words,std::sync::Arc::new(geometry))}
 *owner=Owner::default();owner.flags_12836=flags;owner.interactable_latched=seed&1!=0;owner.query_position=[seed as f32,0.125,-0.25,-0.];owner.validation_position=[-0.5,seed as f32*0.25,0.75,0.];
 for n in 0..seed%3{let mut frame=skate_core::physics::skeleton_animation_record::IDENTITY;frame[3]=owner.query_position;owner.queries.push(Query{position:owner.query_position,sort_position:owner.validation_position,bounds:Bounds{frame,extents:[0.25,0.5,0.75,1.]},limits:BoardLimits{margin:0.125,angle_a:-0.25,angle_b:0.375},mode:n,capacity:(seed+n)as usize,context:QueryContext{selection_flags_2948:u32::from(flags),matching_id_2952:-(seed as i32)}});}
 for n in 0..1+seed%3{owner.pending.push(record(seed+n));owner.validated.push(record(seed+n+10));}
 if seed&1!=0{owner.query_result=Some(owner.pending.clone());owner.validation=Some(vec![None,Some(Hit{fraction:0.375,assembly:None}),Some(Hit{fraction:-0.,assembly:Some(seed+1)})]);}
 for n in 0..2{if seed&(1<<n)!=0{owner.requests[n]=Some(Descriptor{kind:n as u32+1,id:seed+n as u32});}if seed&(2<<n)!=0{owner.data[n]=Some(record(seed+20+n as u32));}owner.data_ready[n]=seed&(4<<n)!=0;}
 if seed&2!=0{owner.interactable_request=Some(std::array::from_fn(|n|Line{start:[n as f32,0.25,0.5,0.],end:[n as f32,-0.25,-0.5,0.],radius:0.125,group:-(seed as i32),reject_flags:seed+n as u32,source_pool_mask:2,selection_flags:seed^n as u32}));}
 if seed%3==1{owner.interactable_result=Some(None);}else if seed%3==2{owner.interactable_result=Some(Some(seed+31));}
}
fn observe_record(out:&mut Vec<u32>,r:&Record){out.extend(r.0);out.extend([r.1.id,r.1.points.len()as u32]);for v in &r.1.points{out.extend(v.map(f32::to_bits));}out.push(r.1.approach_vectors.len()as u32);for v in &r.1.approach_vectors{out.extend(v.map(f32::to_bits));}out.push(r.1.word_60);}
pub fn observe(out:&mut Vec<u32>,s:&Owner){
 out.push(s.queries.len()as u32);for q in &s.queries{for v in [q.position,q.sort_position]{out.extend(v.map(f32::to_bits));}for v in q.bounds.frame{out.extend(v.map(f32::to_bits));}out.extend(q.bounds.extents.map(f32::to_bits));out.extend([q.limits.margin,q.limits.angle_a,q.limits.angle_b].map(f32::to_bits));out.extend([q.mode,q.capacity as u32,(q.capacity>>32)as u32,q.context.selection_flags_2948,q.context.matching_id_2952 as u32]);}
 out.push(s.query_result.is_some()as u32);if let Some(r)=&s.query_result{out.push(r.len()as u32);for r in r{observe_record(out,r);}}
 for r in [&s.pending,&s.validated]{out.push(r.len()as u32);for r in r{observe_record(out,r);}}
 out.push(s.validation.is_some()as u32);if let Some(h)=&s.validation{out.push(h.len()as u32);for h in h{out.push(h.is_some()as u32);if let Some(h)=h{out.push(h.fraction.to_bits());out.push(h.assembly.is_some()as u32);if let Some(id)=h.assembly{out.push(id);}}}}
 for d in &s.requests{out.push(d.is_some()as u32);if let Some(d)=d{out.extend([d.kind,d.id]);}}for r in &s.data{out.push(r.is_some()as u32);if let Some(r)=r{observe_record(out,r);}}out.extend(s.data_ready.map(u32::from));
 out.push(s.interactable_request.is_some()as u32);if let Some(lines)=s.interactable_request{for l in lines{out.extend(l.start.map(f32::to_bits));out.extend(l.end.map(f32::to_bits));out.extend([l.radius.to_bits(),l.group as u32,l.reject_flags,l.source_pool_mask as u32,l.selection_flags]);}}
 out.push(s.interactable_result.is_some()as u32);if let Some(id)=s.interactable_result{out.push(id.is_some()as u32);if let Some(id)=id{out.push(id);}}out.extend([s.interactable_latched as u32,u32::from(s.flags_12836)]);out.extend(s.query_position.map(f32::to_bits));out.extend(s.validation_position.map(f32::to_bits));
}
// CACHE_PRIVACY_END
struct GroundContext{air:skate_core::air::reckoning::AirState,wipeout:skate_core::player::wipeout::Requests,grab:physics::biped_ground::grab_runtime::Owner,trace:Vec<u32>,pending_launch:Option<GroundLaunchInfo>}
impl Default for GroundContext{fn default()->Self{Self{air:skate_core::air::reckoning::AirState::new(),wipeout:skate_core::player::wipeout::Requests::new(),grab:Default::default(),trace:Vec::new(),pending_launch:None}}}
fn ground_trace(trace:&mut Vec<u32>,id:u32,words:Vec<u32>){trace.extend([id,words.len()as u32]);trace.extend(words);}
fn ground_owner(out:&mut Vec<u32>,s:&SkaterRuntime,ctx:&GroundContext,wobble:&skate_core::physics::skeleton_output::wobble::Wobble){
 let mut o=Output(Vec::new());physics::ground_runtime::observe_state(&mut o,&s.ground);physics::ground_runtime::observe_settings(&mut o,&s.ground_settings);o.floats(physics::ground_runtime::retained_normal(&s.ground_runtime));let(w,c,d)=physics::ground_runtime::runtime_settings(&s.ground_runtime);o.floats(w.anti_gravity_vs_time.x);o.floats(w.anti_gravity_vs_time.y);o.floats([w.max_dot_floor_wall,w.foot_force_time,w.auto_jump_height,w.max_time,w.velocity_time_to_consider,w.auto_jump_y_down_scalar,w.auto_jump_force]);observe_CollisionResponseSettings(&mut o,c);o.floats(d);
 let c=s.ground_runtime.contact;o.word(c.active_2731 as u32);o.word(c.tag_16_force.tag);o.vector(c.tag_16_force.force_world);o.vector(c.tag_16_force.point_body);o.floats(c.vector_2688);o.float(c.scalar_2704);o.word(c.animated_board_2708 as u32);o.word(s.ground_runtime.collision_force.is_some()as u32);if let Some(c)=s.ground_runtime.collision_force{o.floats(c.force_2528);o.floats(c.point_2544);o.floats(c.vector_2592);}
 let life=&s.ground_lifecycle;let c=&life.skeleton_controller;o.words([c.effective,c.requested,c.has_request as u32,c.override_enabled as u32,c.flag_18 as u32,life.skeleton_elapsed_16505 as u32]);o.word(life.board_animated_290 as u32);o.float(life.manual_drag_2724);o.floats([ctx.air.spin_angle,ctx.air.spin_speed]);o.words([wobble.active as u32,wobble.landing as u32]);o.floats([wobble.time,wobble.amplitude,wobble.direction]);o.words(ctx.wipeout.reasons.map(u32::from));o.floats(ctx.wipeout.values);o.word(ctx.wipeout.count);o.float(ctx.wipeout.cooldown);o.word(ctx.wipeout.contact_frames as u32);o.float(ctx.wipeout.balance);o.word(ctx.wipeout.mode);o.word(ctx.pending_launch.is_some()as u32);if let Some(l)=&ctx.pending_launch{observe_GroundLaunchInfo(&mut o,l);}out.extend(o.0);physics::biped_ground::grab_runtime::observe(out,&ctx.grab);out.push(ctx.trace.len()as u32);out.extend(&ctx.trace);
}
fn ground_physics(out:&mut Vec<u32>,s:skate_core::riding::grounded::state::output::PhysicsGroundOutput){
 out.extend([s.skateboard_motion_4.is_push_accelerating as u32,s.skateboard_motion_4.is_at_pushable_speed as u32,s.velocity_projection_36.is_some()as u32]);if let Some(v)=s.velocity_projection_36{probe_floats(out,v.velocity_without_axis_component);out.push(v.active as u32);}let g=s.ground_32;out.extend([g.wall_ride_exit as u32,g.anti_flip_nudge_present as u32,g.is_pinning as u32]);probe_floats(out,g.anti_flip_torque);probe_floats(out,[g.time_to_skitch,g.skitch_spline_height,g.processed_scalar_2720]);out.push(g.processed_flag_2484_bit_13 as u32);let s28=s.state_28;out.extend([s28.grab_spline_type,s28.grab_spline_object_id,s28.flag_84 as u32,s28.has_world_grab_intent_without_object as u32,s28.manual_correction_write_78.is_some()as u32]);if let Some(v)=s28.manual_correction_write_78{out.push(v as u32);}out.extend([s.intents_52.has_world_grab_intent as u32,s.intents_52.selected_mode_below_speed_threshold_58 as u32,s.is_grabbing_object_72_304 as u32,s.manual_opposition_56_168 as u32,s.push_suppressed_20_596 as u32]);
}
fn ground_outcome(out:&mut Vec<u32>,s:GroundBoardOutcome){match s{GroundBoardOutcome::Animated=>out.extend([0,0,0,0,0,0]),GroundBoardOutcome::Collision{tag_15_queued}=>out.extend([1,tag_15_queued as u32,0,0,0,0]),GroundBoardOutcome::Ordinary(v)=>out.extend([2,0,v.manual_correction as u32,v.terminal_force_tag,v.terminal_force_queued as u32,v.speed_model_reset as u32])}}
fn ground_error(out:&mut Vec<u32>,error:String){
 if error=="Ground::Enter must finish before Ground::Update"{out.extend([0,0,0]);probe_error(out,&error);probe_error(out,"");return;}
 if error.starts_with("Invalid pumping physics mode "){out.extend([1,0,0]);probe_error(out,&error);probe_error(out,"");return;}
 let inner=error.strip_prefix("Native Ground board update: Service { stage: ").expect("concrete Ground failure must expose its original stage");let(stage,source)=inner.split_once(", source: ").unwrap();let stages=["CenterOfMassHeight","SetWheelMaterials","ContactResponse","UpdateBodyAccumulator","SetAnimatedVelocity","WriteProcessedVelocity","BuildAnimatedPose","PublishAnimatedPose","UpdateExternalPlayer","CommitExternalPlayer","FinalizeAnimatedBoard","CollisionForce","ApplyCollisionVector","CollisionProjection","ManualEffect","PushForceSquared","AntiFlipNudge","ApplyCollisionDecay","ApplyStraighten","ApplyHeading","ApplyAntiFlip","ApplyManual","HangUps","HalfpipeWheelCatch","Pinning","StrongForceSquared"];let stage=stages.iter().position(|s|*s==stage).unwrap()as u32;let source: String=serde_json::from_str(source.strip_suffix(" }").unwrap()).unwrap();out.extend([2,0,stage]);probe_error(out,"");probe_error(out,&source);
}
fn ground_tick(i:&mut ProbeInput,out:&mut Vec<u32>,p:&mut GamePhysics,s:&mut SkaterRuntime,e:&animation_pose::PoseEvaluator,ik:&mut physics::foot_ik::FootIk,input:&mut physics::animation_input::AnimationInput,wobble:&mut skate_core::physics::skeleton_output::wobble::Wobble,ws:&skate_core::physics::skeleton_output::wobble::Settings,queries:&mut PlayerInputState,actions:&mut Actions,ctx:&mut GroundContext)->bool{
 let processed=process_dispatcher(i,out,p,s,e,ik,input,wobble,ws,queries,actions);let pose=i.word();let enter=i.word()!=0;let v=&mut s.player_input.processed;v.state_2504=i.word();v.category_2516=i.word();v.state_variant_index_2528=i.word();v.state_timer_2664=i.float();v.time_since_last_input_2748=i.float();v.truck_tightness_2760=i.float();v.crouch_2776=i.float();v.crouch_delta_2780=i.float();v.spin_input_2672=i.float();v.transition_2636=i.float();v.frames_since_teleport_2584=i.word();s.ground_lifecycle.manual_drag_2724=i.float();let trajectory=i.word();let edge_flags=i.word();let edge_point=i.floats();let edge_start=i.vector();let edge_end=i.vector();let launch_present=i.word()!=0;let coffin=i.word()!=0;let solve=i.word()!=0;
 if !processed{return false;}ctx.trace.clear();ctx.pending_launch=None;
 let v=&mut s.player_input.processed;v.wheel_count_2556=p.riding.ground.wheel_contact_count as u32;v.scalar_2612=p.riding.motion.speed;v.scalar_2616=p.riding.motion.ground_speed;v.scalar_2652=p.riding.motion.forward_speed;v.scalar_2656=p.riding.motion.ground_speed;v.scalar_2764=0.;v.vectors_400_416=[four(p.board.bodies()[6].rates.linear_velocity).map(f32::to_bits),four(p.board.bodies()[6].rates.angular_velocity).map(f32::to_bits)];v.vectors_464_480_496_512_528=[four(p.riding.ground.wheel_normal).map(f32::to_bits),four(p.riding.ground.parts[6].point).map(f32::to_bits),four(p.riding.ground.parts[6].point).map(f32::to_bits),s.animated_skeleton.roots.heading_alignment[2].map(f32::to_bits),four(p.riding.ground.overall_normal).map(f32::to_bits)];v.vectors_544_560_592_608[0]=s.animated_skeleton.roots.animation_to_world[1].map(f32::to_bits);v.vectors_544_560_592_608[2]=s.skeleton.record.centre_of_mass.map(f32::to_bits);v.vectors_544_560_592_608[3]=s.skeleton.record.centre_of_mass_velocity.map(f32::to_bits);v.collision_pose_error_736=s.collision_pose_error.map(f32::to_bits);v.effective_anim_transform_192=s.animated_skeleton.roots.animation_to_world.map(|c|c.map(f32::to_bits));v.time_on_ground_2752=p.ticks as f32*v.timestep_2604;v.signed_ground_time_2756=v.time_on_ground_2752;
 let toolkit=s.ground_runtime.prepare_toolkit(&p.board,v);
 if enter{use skate_core::player::offboard::board_possession::lifecycle::Effects as _;s.board_possession_live.effects(p,&mut s.ground_lifecycle.board_animated_290,v.timestep_2604).standard_board();s.board_possession_live.publish_volumes(p);s.skeleton_output.wobble=std::mem::take(wobble);let result=physics::ground_phase::enter_components(&mut p.board,&s.player_input.processed,input,&toolkit,&mut s.ground,&mut s.ground_lifecycle,&mut ctx.air,&mut ctx.wipeout,&mut s.skeleton_collision,ik,&mut s.skeleton_output,&mut p.board_wiping_out);*wobble=std::mem::take(&mut s.skeleton_output.wobble);let ok=result.is_ok();adjusted_error_out(out,result);if !ok{return false;}}
 let v=&s.player_input.processed;p.riding.update_ground_reckoning(&p.board,physics::riding_outputs::RidingPoseInputs{com_to_deck:s.animated_skeleton.record.com_to_deck(),body_spin:input.extra.physical_body_spin},v.flags_2468,input.fields.balance,coffin,v);s.ground.state.push_suppressed_2730=false;
 let mut pending=Output(Vec::new());pending.words([v.flags_2476,v.state_2508]);for m in [toolkit.deck,s.animated_skeleton.roots.animation_to_world]{for c in m{pending.floats(c);}}ground_trace(&mut ctx.trace,5,pending.0.clone());let selector=match physics::air_phase::selector_input(p,s){Ok(v)=>v,Err(error)=>{adjusted_error_out(out,Err(error));return false;}};let mut observed=Output(Vec::new());observe_SelectorInput(&mut observed,&selector);out.extend(observed.0);
 let v=&s.player_input.processed;let normal=v.vectors_464_480_496_512_528[0].map(f32::from_bits);let up=v.vectors_544_560_592_608[0].map(f32::from_bits);let initial=v.vectors_400_416[0].map(f32::from_bits);let mut velocity=initial;let mut prediction=s.animated_skeleton.roots.predicted_board_position;
 let frame=physics::ground_runtime::GroundUpdateFrame{processed:v,animation:input,riding:&p.riding,skeleton:&s.animated_skeleton,toolkit:&toolkit,base_trucks:p.settings.step.base_truck_transforms,extra:physics::ground_runtime::GroundInputObservations{manual_drag_2724:s.ground_lifecycle.manual_drag_2724,trajectory_state_bits:trajectory,edge_flags,edge_point}};
 let launch=GroundLaunchPhysical{reckoning:&p.riding.reckoning_frames,skeleton_vector_16208:s.animated_skeleton.board_frames.local_centre_of_mass,skeleton_vector_16240:s.animated_skeleton.board_frames.local_board_position,board_position:toolkit.deck[3],physical_center_of_mass:v.vectors_544_560_592_608[2].map(f32::from_bits),velocity:initial,angular_velocity:v.prepared_jump_704.map(f32::from_bits),flags_2468:v.flags_2468,time_step:v.timestep_2604};
 let targets=&mut s.skeleton_drives.targets;let mut future_words=Vec::new();let mut future=|delta:Vector3|{let mut o=Output(Vec::new());o.vector(delta);ground_trace(&mut future_words,3,o.0);targets.apply_future_deck_displacement(delta);prediction[0]+=delta.x;prediction[1]+=delta.y;prediction[2]+=delta.z;Ok(())};
 let mut launch_words=Vec::new();let mut pending_launch=None;let mut boundary=|info:&GroundLaunchInfo|{pending_launch=Some(info.clone());let mut input=selector;input.board_vertical_velocity=info.velocity[1];let mut o=Output(Vec::new());observe_GroundLaunchInfo(&mut o,info);observe_LaunchInfo(&mut o,&info.selector_launch());observe_SelectorInput(&mut o,&input);ground_trace(&mut launch_words,7,o.0);Err("Pending actual trajectory Launch/Update continuation".into())};
 let physical=physics::ground_runtime::GroundPhysicalFrame{skeleton_record:&s.animated_skeleton.record,wall_ride:WallRidePhysical{board_normal:normal,up,velocity:initial,board_mass:toolkit.total_mass,gravity:v.gravity_2648,speed:v.scalar_2652,contact_count:v.wheel_count_2556 as i32},collision:CollisionResponsePhysical{flags_2472:v.flags_2472,collision_displacement:v.collision_pose_error_736.map(f32::from_bits),velocity:v.vectors_400_416[1].map(f32::from_bits),forward:toolkit.travel_direction,up,ground_normal:four(p.riding.reckoning.ground_normal),time_step:v.timestep_2604,mass:toolkit.total_mass},hang_geometry:skate_core::physics::ground_hang_geometry::HangGeometryInput{edge_start,edge_end,reference_point:Vector3::new(edge_point[0],edge_point[1],edge_point[2])},processed_velocity:&mut velocity,wheel_material:&mut p.settings.wheel_material,wipeout:&mut ctx.wipeout,time_step:v.timestep_2604,launch_physical:launch_present.then_some(launch),launch_and_update:&mut boundary};
 let result=s.ground.update(&mut s.ground_runtime,&mut p.board,&p.world,&s.ground_settings,frame,physical,physics::ground_runtime::GroundUpdateTargets{foot_ik:ik,skeleton_elapsed_16505:&mut s.ground_lifecycle.skeleton_elapsed_16505,board_correction_pending:&mut s.skeleton_output.correction.pending,move_future_deck:&mut future,offboard_grab:&mut ctx.grab});s.player_input.processed.vectors_400_416[0]=velocity.map(f32::to_bits);s.animated_skeleton.roots.predicted_board_position=prediction;ctx.trace.extend(launch_words);ctx.trace.extend(future_words);ctx.pending_launch=pending_launch;out.push(result.is_ok()as u32);let outcome=match result{Ok(v)=>v,Err(error)=>{ground_error(out,error);return false;}};ground_trace(&mut ctx.trace,4,Vec::new());let outcome_start=out.len();ground_outcome(out,outcome);ground_trace(&mut ctx.trace,9,out[outcome_start..].to_vec());ground_physics(out,s.ground.output(&s.player_input.processed,input,&toolkit));
 ground_trace(&mut ctx.trace,6,pending.0);let globals=adjusted_hierarchy(e,pose);let a=&mut s.animated_skeleton;a.board_frames.update_com_lift(&a.roots.animation_to_world,a.animation_hips[3],0.02);let collision=dispatcher_collision(s);let result={let mut owners=physics::skeleton_input_runtime::SkeletonOwners{animated:&mut s.animated_skeleton,body:&mut s.skeleton,drives:&mut s.skeleton_drives,ik,animation_input:input,correction:&mut s.skeleton_output.correction,pose_errors:&mut s.pose_errors};s.skeleton_input.update_ground(&p.board,&p.riding.reckoning_frames.system,&mut s.player_input.processed,&mut owners,&globals,&collision,p.settings.step.simulation)};let(frame,ok,error)=match result{Ok(v)=>(v,true,String::new()),Err(e)=>(IDENTITY,false,e)};probe_matrix(out,frame);adjusted_error_out(out,if ok{Ok(())}else{Err(error)});if !ok{return false;}
 let mut capture=Output(Vec::new());for m in [frame,s.animated_skeleton.board_frames.animation_target]{for c in m{capture.floats(c);}}ground_trace(&mut ctx.trace,8,capture.0);p.processed_flags_2468=s.player_input.processed.flags_2468;if !solve{return true;}
 let targets=s.ground.steering.targets;if let Err(error)=physics::advance(p,s,targets){adjusted_error_out(out,Err(error));return false;}out.extend([p.contact_count as u32,s.solved_drives.as_ref().map_or(0,|b|b.rows.len())as u32]);let saved=s.player_input.processed;let v=&mut s.player_input.processed;v.vectors_464_480_496_512_528[0]=four(p.riding.ground.wheel_normal).map(f32::to_bits);v.vectors_544_560_592_608[0]=s.animated_skeleton.roots.animation_to_world[1].map(f32::to_bits);v.time_on_ground_2752=p.ticks as f32*v.timestep_2604;p.riding.probes.prepare_wall(v,&toolkit);p.riding.finish_post_physics(&mut p.board,p.board_wiping_out,p.processed_flags_2468,p.settings.step.simulation.time_step).unwrap();let v=&mut s.player_input.processed;v.vectors_464_480_496_512_528[1]=four(p.riding.ground.parts[6].point).map(f32::to_bits);v.vectors_464_480_496_512_528[2]=v.vectors_464_480_496_512_528[1];v.vectors_464_480_496_512_528[4]=four(p.riding.ground.overall_normal).map(f32::to_bits);v.vectors_880_896_912_928_944[0]=s.animated_skeleton.animation_hips[3].map(f32::to_bits);v.vectors_880_896_912_928_944[1]=[0.,1.,0.,0.].map(f32::to_bits);physics::publish(p,s);s.player_input.processed=saved;
 let mut observed=physics::deck_frame(&p.board);let sample=wobble.update(ws);skate_core::physics::skeleton_output::wobble::apply(sample,&mut observed);out.push(sample.sampled as u32);probe_floats(out,[sample.tilt,sample.squish]);out.push(sample.remains_active as u32);probe_matrix(out,observed);let v=&s.player_input.processed;let inverse=s.animated_skeleton.roots.world_to_animation;let post=ik.post_physics(&mut s.skeleton,core_ik::post_physics::Input{state_id:v.state_2508,category_id:v.category_2512,board_body_flag_868:p.riding.ground.part_contact_count!=0,wipeout:false,flags_2468:v.flags_2468,flags_2484:v.flags_2484,value_2664:v.state_timer_2664,state_2520:v.player_state_value_2520,world_to_animation:&inverse,board:&observed});out.extend(post.map(u32::from));s.skeleton.publish_physical_record(physics::deck_frame(&p.board));p.ticks+=1;adjusted_error_out(out,Ok(()));true
}
impl GroundContext{fn grab_signature(&self)->Vec<u32>{let mut out=Vec::new();physics::biped_ground::grab_runtime::observe(&mut out,&self.grab);out}}
fn main(){
 let args=std::env::args().collect::<Vec<_>>();let assets=std::path::Path::new(&args[1]);let data=skate_data::collections::Collections::load(assets).unwrap();if args.get(2).map(String::as_str)==Some("--load-only"){let mut bytes=Vec::new();std::io::stdin().read_to_end(&mut bytes).unwrap();let stage=u32::from_le_bytes(bytes.try_into().unwrap());let result=match stage{0=>physics::ground_runtime::GroundState::load(&data,"normal",true).map(|_|()),1=>physics::ground_runtime::GroundRuntime::load(&data).map(|_|()),2=>physics::ground_runtime::GroundProfiles::load(&data).map(|_|()),_=>panic!("loader")};let mut out=Vec::new();adjusted_error_out(&mut out,result);let mut stdout=std::io::BufWriter::new(std::io::stdout().lock());for word in out{stdout.write_all(&word.to_le_bytes()).unwrap();}return;}let e=animation_pose::PoseEvaluator::from_banks(&skate_data::animation_banks::AnimationBanks::load(assets).unwrap()).unwrap();let stock=physics::settings::PhysicsSettings::load(&data).unwrap();let profiles=physics::ground_runtime::GroundProfiles::load(&data).unwrap();let ws=wobble_settings(&data);let mut bytes=Vec::new();std::io::stdin().read_to_end(&mut bytes).unwrap();let mut i=ProbeInput{words:bytes.chunks_exact(4).map(|b|u32::from_le_bytes(b.try_into().unwrap())).collect(),at:0};let mut out=Vec::new();let count=i.word();
 for c in 0..count{let spawn=i.affine();let world=i.world(stock.floor_material);let seams=i.word()!=0;let mode=i.word();let surface=i.word();let tuning=read_TrainerTuning(&mut Input{p:&mut i});let(mut p,mut s)=make(&data,assets,&e,spawn,world);s.ground_settings=std::sync::Arc::new(profiles.select(mode,surface).unwrap().tuned(tuning));if seams{p.world.enable_imported_floor_seams();}let mut ik=physics::foot_ik::FootIk::load(&data,&e.frames,&s.animated_skeleton).unwrap();let mut input=physics::animation_input::AnimationInput::load(&data,&e.frames,"normal").unwrap();let mut wobble=Default::default();let mut ctx=GroundContext::default();let mut queries=PlayerInputState::default();let mut actions=Actions::default();let n=i.word();out.extend([c,n,0]);let mark=out.len()-1;let initial=out.len();out.push(0);snapshot(&mut out,&mut p,&mut s);adjusted_out(&mut out,&s.animated_skeleton,&ik,&s.skeleton_input.grind_air,&queries);observe_dispatcher(&mut out,&s.skeleton_input,&input,&wobble,s.ground_lifecycle.skeleton_elapsed_16505,&s.player_input.processed,&actions);let ground_initial=out.len();ground_owner(&mut out,&s,&ctx,&wobble);out.push((out.len()-ground_initial)as u32);out[initial]=(out.len()-initial-1)as u32;
 for _ in 0..n{let op=i.word();out.extend([op,0]);let at=out.len()-1;let payload=out.len();out.push(0);match op{
 0=>{let success=out.len();out.push(0);out[success]=ground_tick(&mut i,&mut out,&mut p,&mut s,&e,&mut ik,&mut input,&mut wobble,&ws,&mut queries,&mut actions,&mut ctx)as u32;},1=>physics::migration_ground_exit(&mut p,&mut s),2=>{let mode=i.word();let surface=i.word();match profiles.select(mode,surface){Ok(v)=>{s.ground_settings=std::sync::Arc::new(v.tuned(tuning));adjusted_error_out(&mut out,Ok(()));},Err(e)=>{adjusted_error_out(&mut out,Err(e));}}},3=>{s.ground.state=read_PhysicsGroundState(&mut Input{p:&mut i});s.ground.pumping=read_PumpingState(&mut Input{p:&mut i});s.ground.entered=i.word()!=0;},4=>{let seed=i.word();let flags=i.word()as u8;physics::biped_ground::grab_runtime::seed(&mut ctx.grab,seed,flags);},5=>ctx.grab.invalidate(),6=>ctx.grab.enter_reset(),7=>p.world=i.world(p.settings.floor_material),8=>physics::ground_phase::reset_board_state(&mut s.ground,&mut s.ground_runtime,&mut s.ground_lifecycle,&mut p.board_wiping_out),9=>{let balance=i.float();let toolkit=s.ground_runtime.prepare_toolkit(&p.board,&s.player_input.processed);let result=s.ground.pumping_settings.update_revert(&mut s.ground.pumping,&toolkit,&p.riding,&s.animated_skeleton,&s.player_input.processed,balance);adjusted_error_out(&mut out,result);},10=>{let life=&mut s.ground_lifecycle;let c=&mut life.skeleton_controller;c.effective=i.word();c.requested=i.word();c.has_request=i.word()!=0;c.override_enabled=i.word()!=0;c.flag_18=i.word()!=0;life.skeleton_elapsed_16505=i.word()!=0;life.board_animated_290=i.word()as u8;ctx.air.spin_angle=i.float();ctx.air.spin_speed=i.float();ctx.wipeout.mode=i.word();ctx.wipeout.balance=i.float();p.board_wiping_out=i.word()!=0;},_=>panic!("Ground proof operation")};out[payload]=(out.len()-payload-1)as u32;snapshot(&mut out,&mut p,&mut s);adjusted_out(&mut out,&s.animated_skeleton,&ik,&s.skeleton_input.grind_air,&queries);observe_dispatcher(&mut out,&s.skeleton_input,&input,&wobble,s.ground_lifecycle.skeleton_elapsed_16505,&s.player_input.processed,&actions);let ground_observation=out.len();ground_owner(&mut out,&s,&ctx,&wobble);out.push((out.len()-ground_observation)as u32);out[at]=(out.len()-at-1)as u32;}out[mark]=(out.len()-mark-1)as u32;}
 assert_eq!(i.at,i.words.len());let mut stdout=std::io::BufWriter::new(std::io::stdout().lock());for word in out{stdout.write_all(&word.to_le_bytes()).unwrap();}
}
