// Appended inside the frozen host Handplant module after observation helpers.
// Caller inputs are explicit. Every production lifecycle/geometry/IK call below
// invokes the original unchanged host and core owners.
fn block(o:&mut Output,f:impl FnOnce(&mut Output)){let at=o.0.len();o.word(0);f(o);o.0[at]=(o.0.len()-at-1)as u32;}
fn vector(o:&mut Output,v:Vector3){o.floats([v.x,v.y,v.z]);}
fn body(o:&mut Output,b:&skate_core::physics::assembly::BodySnapshot){o.word(b.state_flags);let r=b.rates;o.floats([r.orientation.x,r.orientation.y,r.orientation.z,r.orientation.w]);for c in r.basis.columns{o.floats(c)}for c in r.world_inverse_inertia.columns{o.floats(c)}for v in [r.position,r.linear_velocity,r.angular_velocity,r.force_acceleration,r.torque_acceleration]{vector(o,v)}o.float(r.kinetic_energy);o.word(r.cool_down);}
fn dynamics(o:&mut Output,d:skate_core::physics::drive_parameters::RetailDriveDynamics){for p in [d.linear,d.angular]{o.floats([p.spring_or_max_velocity,p.damping,p.max_strength]);o.word(p.drive_type as u32);}}
fn drive_frames(o:&mut Output,f:skate_core::physics::drive_frames::RetailDriveFrames){for a in [f.body_a,f.body_b]{o.floats([a.orientation.x,a.orientation.y,a.orientation.z,a.orientation.w]);vector(o,a.translation);}}
fn snapshot(o:&mut Output,p:&GamePhysics,s:&SkaterRuntime){
 o.word(10);
 block(o,|o|{owner(o,&s.handplant);effects(o,s)});
 block(o,|o|super::super::air_reckoning::migration_lifecycle_observe(o,&s.air_reckoning,&p.riding));
 block(o,|o|{let r=&s.animated_skeleton.roots;for m in [r.board,r.inverse_board,r.animation_to_board,r.animation_to_world,r.world_to_animation,r.heading_alignment]{o.matrix(m)}o.floats(r.previous_board_position);o.floats(r.predicted_board_position);o.word(r.supplied_prediction.is_some()as u32);if let Some(v)=r.supplied_prediction{o.floats(v)}o.word(r.initialize_heading as u32);let f=&s.animated_skeleton.board_frames;for m in [f.physical_board,f.skate_root,f.animation_target,f.com_frame,f.lifted_com_frame]{o.matrix(m)}for v in [f.centre_of_mass,f.previous_centre_of_mass,f.com_velocity,f.local_centre_of_mass,f.local_board_position]{o.floats(v)}o.float(f.lift_height);});
 block(o,|o|{let a=&s.animated_skeleton;let r=&a.record;for m in r.pose{o.matrix(m)}for v in [r.centre_of_mass,r.centre_of_mass_delta,r.com_to_deck_world,r.com_to_deck_world_delta]{o.floats(v)}o.float(r.reset_scalar);for m in a.targets{o.matrix(m)}for m in [a.animation_board,a.unadjusted_board,a.animation_hips,a.motion.trajectory,a.motion.inverse_trajectory,a.motion.next_trajectory]{o.matrix(m)}o.floats(a.motion.velocity_world);o.float(a.motion.migration_lifecycle_previous());o.float(a.board_at_y_delta);for m in s.skeleton_input.drive_frames{o.matrix(m)}});
 block(o,|o|{let state=&s.foot_ik.state;o.word(state.feet_enabled()as u32);for l in state.limbs{o.word(l.mode as u32);o.floats([l.board_blend,l.external_blend,l.target_blend]);o.word(l.external_target_set as u32);o.word(l.local_target_set as u32);o.floats(l.external_target_local_delta);o.floats(l.part_position);}for f in state.frames{for m in [f.target,f.world,f.external_world,f.board,f.parent_world,f.external_parent_world,f.parent_board]{o.matrix(m)}o.word(f.within_contact_bounds as u32);}for t in state.external_targets{o.floats(t.world_position);o.floats(t.animation_position);o.floats(t.normal);o.word(t.normal_set as u32);o.float(t.normal_blend);}for c in state.contacts.feet{o.word(c.query_state);o.floats(c.position);o.floats([c.desired_offset,c.offset]);}o.word(state.contacts.support_failed as u32);o.word(state.contacts.support_failed_this_update as u32);});
 block(o,|o|{let a=&s.skeleton_air.board_animation;o.floats(a.rotation_error);o.word(a.blending as u32);let h=p.board.hook();for w in h.drive.frames{o.word(w)}for w in h.drive.dynamics{o.word(w)}body(o,&h.body);for b in p.board.bodies(){body(o,b)}for b in s.skeleton.bodies(){body(o,b)}for b in &s.skeleton_drives.targets.bodies{body(o,b)}});
 block(o,|o|{let r=&s.skeleton.record;for m in r.pose{o.matrix(m)}for v in r.positions{o.floats(v)}for v in r.velocities{o.floats(v)}for v in r.velocity_changes{o.floats(v)}o.floats(r.centre_of_mass);o.floats(r.centre_of_mass_velocity);o.float(r.timestep);for v in s.pose_errors.parts{o.floats(v)}for v in s.pose_errors.extra{o.floats(v)}for v in s.pose_errors.targets{o.floats(v)}});
 block(o,|o|{let d=&s.skeleton_drives;for f in d.targets.frames{drive_frames(o,f)}for value in d.targets.dynamics{dynamics(o,value)}for b in &d.bones{o.word(b.is_some()as u32);if let Some(b)=b{for n in b.parent{o.word(n as u32)}for a in b.active{o.word(a as u32)}for f in b.frames{drive_frames(o,f)}for d in b.dynamics.channels{dynamics(o,d)}o.word(b.dynamics.mode);o.floats(b.dynamics.strengths);o.float(b.dynamics.transition_counter);o.word(b.dynamics.transition_active as u32)}}});
 block(o,|o|{let p=&s.player_input.processed;for w in [p.flags_2468,p.flags_2472,p.flags_2476,p.flags_2480,p.flags_2484,p.state_2508,p.category_2512,s.animation_input.fields.flags2468]{o.word(w)}let input=&s.skeleton_input;o.word(input.reenable_requested as u32);o.word(input.teleporting as u32);o.word(input.force_mode);o.floats(input.root_velocity);o.floats(input.previous_root_position);o.floats(input.reset_local_hips);o.word(input.invalid_target_reset as u32);o.matrix(input.animation_board_to_physics);for v in input.extra_target_positions{o.floats(v)}o.floats(s.skeleton_output.correction.board_prediction_error);o.word(s.skeleton_output.correction.pending as u32);});
 block(o,|o|{let a=&s.animated_skeleton;let b=&a.board_offset;o.matrix(b.transform);o.floats([b.orientation_frames,b.height_frames]);o.word(b.orientation_refreshed as u32);o.word(b.height_refreshed as u32);let l=&a.landing;o.word(l.active as u32);o.word(l.kind);o.floats([l.time,l.position,l.velocity,l.previous_com_velocity,l.previous_animation_height]);o.word(l.previous_filtered_state);o.float(l.desired_grind_com);});
}
fn publish(i:&mut Input,skater:&mut SkaterRuntime,physics:&mut GamePhysics){let p=&mut skater.player_input.processed;p.flags_2468=i.word();p.flags_2472=i.word();p.flags_2476=i.word();p.flags_2480=i.word();p.flags_2484=i.word();p.state_2508=i.word();p.category_2512=i.word();p.timestep_2604=i.float();p.gravity_2648=i.float();p.vectors_544_560_592_608[2]=i.floats::<4>().map(f32::to_bits);p.vectors_400_416[0]=i.floats::<4>().map(f32::to_bits);p.vectors_464_480_496_512_528[0]=i.floats::<4>().map(f32::to_bits);p.vectors_544_560_592_608[1]=i.floats::<4>().map(f32::to_bits);p.vectors_544_560_592_608[3]=i.floats::<4>().map(f32::to_bits);physics.riding.reckoning_frames.heading=i.floats();}
pub(super) fn run(assets:&std::path::Path,fixtures:&std::path::Path,i:&mut Input,o:&mut Output)->Result<(),String>{
 let graphs=crate::graph_runtime::StockGraphs{action:loaded(&fixtures.join("actor.action.reference"))?,motion:loaded(&fixtures.join("actor.motion.reference"))?};let count=i.word();o.word(count);
 for _ in 0..count{
  let mut physics=GamePhysics::load_with_terrain(assets,super::super::ground::Terrain::Flat)?;let world_header=i.word();i.at-=4;physics.world=if world_header==u32::MAX{i.word();authored_query_world(i)}else{world(i)};let edges=(0..i.word()).map(|_|Primitive{start:i.floats(),end:i.floats(),owner:i.wide()}).collect();physics.grind_world=std::sync::Arc::new(crate::grind_world::migration_handplant_primitives(edges));
  let mut skater=SkaterRuntime::load(assets,&graphs,&physics,"normal")?;let rows=i.word();o.word(rows);snapshot(o,&physics,&skater);
  for _ in 0..rows{let op=i.word();o.word(op);let mut target=None;let result=match op{
   0=>{publish(i,&mut skater,&mut physics);Ok(())},
   1=>{let kind=i.word();let mut globals=if kind==4{Vec::new()}else{const POSES:[&str;4]=["RIG_TPOSE","POSTURE_STIFF_POSE","POSTURE_SLOUCH_POSE","POSTURE_BUFF_POSE"];let e=&skater.animation.evaluator;e.hierarchy(&e.evaluate(&[skate_core::animation::playback_tree::PoseCommand::Pose{name:POSES[if kind==5{0}else{kind as usize}].into()}])?)?};if kind==5{globals.truncate(1)}skater.animation.packet.hierarchy=globals.clone();let p=&mut skater.player_input.processed;let deck=crate::physics::solve::deck_frame(&physics.board);let landing=skate_core::physics::skeleton_landing::LandingInput{filtered_state:0,flags_2468:p.flags_2468,flags_2472:p.flags_2472,flags_2476:p.flags_2476,balance:0.,physical_com_velocity_along_up:skater.skeleton.record.centre_of_mass_velocity[1],physical_com_height:skater.skeleton.record.centre_of_mass[1]-deck[3][1],animation_com_height:0.};skater.animated_skeleton.process_pose(&globals,landing,p.timestep_2604,&mut p.flags_2468,&mut p.flags_2472,None)},
   2=>{ground_query(&physics,&mut skater);Ok(())},3=>ground_update(&mut physics,&mut skater),4=>enter(&mut physics,&mut skater),5=>update(&mut physics,&mut skater),
   6=>{let anchor=i.floats();let bone=i.word();plant_skeleton::advance(&mut physics,&mut skater,anchor,(bone!=u32::MAX).then_some(bone as usize))},
   7=>{let right=i.word()!=0;let point=i.floats();let delay=i.word();plant_skeleton::hold_foot(&mut skater,right,point,delay);Ok(())},
   8=>{skater.skeleton_air.capture_physics_error(&physics.board,&skater.animated_skeleton.board_frames.animation_target);Ok(())},9=>{skater.skeleton_air.reset_board();Ok(())},
   10|11=>{let fast=if op==10{i.word()!=0}else{true};let com=if op==11{i.floats()}else{[0.;4]};if op==11{skater.animation.packet.flags=i.word();skater.animation.packet.air_dismount_revert_frames=i.word()as i32;}let collision=super::super::input_phase::collision(&skater);let mut owners=super::super::skeleton_input_runtime::SkeletonOwners{animated:&mut skater.animated_skeleton,body:&mut skater.skeleton,drives:&mut skater.skeleton_drives,ik:&mut skater.foot_ik,animation_input:&mut skater.animation_input,correction:&mut skater.skeleton_output.correction,pose_errors:&mut skater.pose_errors};let r=if op==10{skater.skeleton_input.update_animated(&mut skater.skeleton_air,&mut physics.board,&physics.riding.reckoning_frames.system,&mut skater.player_input.processed,&mut owners,&skater.animation.packet.hierarchy,&collision,physics.settings.step.simulation,fast)}else{skater.skeleton_input.update_known_air(&mut skater.skeleton_air,&mut physics.board,&physics.riding.reckoning_frames.system,com,&skater.animation.packet,&mut skater.player_input.processed,&mut owners,&skater.animation.packet.hierarchy,&collision,physics.settings.step.simulation)};r.map(|m|target=Some(m))},
   12=>{skater.handplant.continuation=i.word()!=0;Ok(())},13=>{if i.word()!=0{skater.handplant.full_reset()}else{skater.handplant.reset()}Ok(())},
   14=>{let c=candidate(i);let com=i.floats();let velocity=i.floats();let normal=i.floats();let body=i.floats();let heading=i.floats();skater.handplant.launch(c,com,velocity,normal,body,heading);Ok(())},15=>{skater.animated_skeleton.motion.next_trajectory=i.matrix();Ok(())},_=>panic!("handplant lifecycle operation")};o.status(result);o.word(target.is_some()as u32);if let Some(m)=target{o.matrix(m)}snapshot(o,&physics,&skater);
  }
 }Ok(())
}
}
pub(crate) fn migration_handplant_lifecycle_run(assets:&std::path::Path,fixtures:&std::path::Path,i:&mut crate::Input,o:&mut crate::Output)->Result<(),String>{migration::run(assets,fixtures,i,o)}
