// Actual frozen host scheduling modules; only owner/transport facades live here.
extern crate self as skate_net;
#[derive(Clone,Copy)]pub struct Pose{pub p:[f32;3],pub q:[f32;4]}
pub struct Body{pub pose:Pose,pub velocity:[f32;3],pub angular:[f32;3]}
pub struct Bone{pub index:u16,pub pose:Pose}
pub mod packed{use super::*;pub struct BodyState{pub root:Pose,pub enabled:u64,pub bodies:Vec<Body>}pub struct PoseState{pub root:Pose,pub bones:Vec<Bone>}}
pub fn hash(_: &[u8])->u64{0} // Physical schema identity boundary; capture/hash format is separate.
pub mod animation{pub fn native_matrix(m:skate_core::physics::skeleton_animation_record::AnimationPartTransform)->bevy::prelude::Mat4{use bevy::prelude::*;Mat4::from_cols(Vec3::new(m[0][0],m[0][1],m[0][2]).extend(0.),Vec3::new(m[1][0],m[1][1],m[1][2]).extend(0.),Vec3::new(m[2][0],m[2][1],m[2][2]).extend(0.),Vec3::new(m[3][0],m[3][1],m[3][2]).extend(1.))}}
mod math{pub use skate_core::math::*;}
#[path="../../crates/skate-host/src/animation_pose.rs"]mod animation_pose;
mod physics{
 pub use skate_core::physics::*;
 use super::*;
 use bevy::prelude::{Mat4,Mat3,Quat,Vec3,Transform};
 pub struct GamePhysics{pub settings:settings::PhysicsSettings,pub board:skate_core::physics::board_runtime::BoardRuntime,pub world:skate_core::physics::board_world::BoardWorld,pub riding:riding_outputs::RidingOutputs,pub network_proxies:network::Proxies,pub network_contacts:usize,pub contact_count:usize,pub query:skate_core::physics::collision::WorldContactSettings,pub retention:skate_core::physics::board_world::ContactRetentionSettings,pub board_wiping_out:bool,pub processed_flags_2468:u32,pub ticks:u64,pub failed:bool}
 pub struct Animated{pub roots:skate_core::physics::skeleton_root::SkeletonRootFrames,pub board_frames:skate_core::physics::skeleton_board_frames::SkeletonBoardFrames,pub record:SkeletonAnimationRecord,pub bone_indices:[usize;24],pub physics_frames:[AnimationPartTransform;24]}
 pub struct SkeletonInput{pub deck_velocity:[f32;4],pub root_velocity:[f32;4],pub previous_root_position:[f32;4],pub reset_local_hips:[f32;4],pub invalid_target_reset:bool,pub animation_board_to_physics:AnimationPartTransform,pub extra_target_positions:[[f32;4];3],pub drive_frames:[AnimationPartTransform;24]}
 pub struct PlayerInput{pub processed:skate_core::player::input_phase::ProcessedPhysicsInput,pub toolkit:Option<skate_core::physics::board_toolkit::BoardToolkit>,pub physical:skate_core::player::input_phase::PhysicalPlayerInput}
 #[derive(Clone,Copy)]pub struct BoardBones{pub front_truck:usize,pub back_truck:usize,pub front_left_wheel:usize,pub front_right_wheel:usize,pub back_left_wheel:usize,pub back_right_wheel:usize}
 pub struct OutputPose{pub board_bones:BoardBones}
 pub struct Output{pub correction:skate_core::physics::skeleton_output::correction::CorrectionState,pub pose:OutputPose}
 pub struct FrameNames{pub bone_names:Vec<String>}pub struct Evaluator{pub frames:FrameNames}pub struct Animation{pub evaluator:Evaluator}
 pub struct BipedState{pub position_368:[f32;4],pub surface:u32}pub struct BipedController{pub state:BipedState}pub struct Biped{pub controller:BipedController}
 pub struct GroundLifecycle{pub board_animated_290:u8}
 pub struct SkaterRuntime{pub skeleton:SkeletonBody,pub skeleton_joints:SkeletonJoints,pub skeleton_drives:SkeletonDrives,pub skeleton_collision:SkeletonCollisionMode,pub collision_feedback:SkeletonCollisionFeedback,pub pose_errors:SkeletonPoseErrors,pub collision_pose_error:[f32;4],pub collision_extra_errors:[[f32;4];2],pub collision_maximum_error:Option<f32>,pub solved_drives:Option<SkeletonDriveBatch>,pub animated_skeleton:Animated,pub skeleton_input:SkeletonInput,pub player_input:PlayerInput,pub skeleton_output:Output,pub skateboard_controller:skate_core::physics::skateboard_controller::SkateboardController,pub board_possession:offboard::board_manager::Owner,pub board_possession_live:offboard::board_manager::runtime::LiveState,pub ground_lifecycle:GroundLifecycle,pub biped_ground:Biped,pub animation:Animation,pub render_pose:Vec<AnimationPartTransform>}
 #[path="physical-host/settings.rs"]pub mod settings;
 #[path="physical-host/skeleton_body.rs"]pub mod stock_body;
 #[path="physical-host/colliders.rs"]pub mod colliders;
 #[path="physical-host/skeleton_colliders.rs"]pub mod skeleton_colliders;
 #[path="physical-host/riding_outputs/mod.rs"]pub mod riding_outputs;
 #[path="physical-host/solve/mod.rs"]pub mod solve;
 #[path="physical-host/skeleton_feedback.rs"]pub mod feedback;
 #[path="physical-host/network.rs"]pub mod network;
 pub mod offboard{#[path="board_possession/mod.rs"]pub mod board_possession;#[path="board_manager/mod.rs"]pub mod board_manager;}
 pub fn deck_frame(board:&skate_core::physics::board_runtime::BoardRuntime)->AnimationPartTransform{solve::deck_frame(board)}
 pub fn advance(p:&mut GamePhysics,s:&mut SkaterRuntime,targets:[f32;2])->Result<(),String>{solve::advance(p,s,targets)}
 pub fn publish(p:&GamePhysics,s:&mut SkaterRuntime){let request=s.skateboard_controller.request_partial_ragdoll(p.riding.ground.part_contact_count);feedback::publish(p,s,request);}
}
use physics::{GamePhysics,SkaterRuntime};
use skate_core::physics::{board_runtime::{BoardRuntime,BoardMotion},board_world::{BoardWorld,WorldTriangle,ContactRetentionSettings},collision::WorldContactSettings,world_contact::triangle_from_volume,drive_frames::RetailAffineTransform,board::BodyId,force_queue::QueuedPointForce,skeleton_root::SkeletonRootFrames,skeleton_board_frames::SkeletonBoardFrames};
const POSES:[&str;4]=["RIG_TPOSE","POSTURE_STIFF_POSE","POSTURE_SLOUCH_POSE","POSTURE_BUFF_POSE"];
impl ProbeInput{
 fn affine(&mut self)->RetailAffineTransform{RetailAffineTransform{basis:Basis3{columns:std::array::from_fn(|_|self.floats())},translation:self.vector()}}
 fn world(&mut self,material:RetailContactMaterial)->BoardWorld{let n=self.word();let triangles=(0..n).map(|_|{let v=std::array::from_fn(|_|self.vector());let fat=self.float();let flags=self.word();let tag=self.word();WorldTriangle{triangle:triangle_from_volume(v,fat,[1.;3],flags),material,tag}}).collect();BoardWorld::new(triangles)}
}
fn four(v:Vector3)->[f32;4]{[v.x,v.y,v.z,0.]}
fn affine_out(out:&mut Vec<u32>,a:RetailAffineTransform){probe_basis(out,a.basis);probe_vector(out,a.translation);}
fn roots_out(out:&mut Vec<u32>,r:&SkeletonRootFrames){for m in [r.board,r.inverse_board]{probe_matrix(out,m);}probe_floats(out,r.previous_board_position);probe_floats(out,r.predicted_board_position);out.push(r.supplied_prediction.is_some() as u32);probe_floats(out,r.supplied_prediction.unwrap_or([0.;4]));for m in [r.animation_to_board,r.animation_to_world,r.world_to_animation,r.heading_alignment]{probe_matrix(out,m);}out.push(r.initialize_heading as u32);}
fn board_frames_out(out:&mut Vec<u32>,b:&SkeletonBoardFrames){for m in [b.physical_board,b.skate_root,b.animation_target,b.com_frame,b.lifted_com_frame]{probe_matrix(out,m);}for v in [b.centre_of_mass,b.previous_centre_of_mass,b.com_velocity,b.local_centre_of_mass,b.local_board_position]{probe_floats(out,v);}out.push(b.lift_height.to_bits());}
fn riding_out(out:&mut Vec<u32>,r:&physics::riding_outputs::RidingOutputs){
 let(w,g)=(&r.wheel_lines,&r.ground);for v in w.normals{probe_vector(out,v);}probe_floats(out,w.distances);out.extend(w.physics_surfaces);out.push(w.minimum_distance.to_bits());for c in g.parts{out.push(c.in_contact as u32);for v in [c.normal,c.point,c.relative_velocity]{probe_vector(out,v);}}for v in g.previous_velocities.into_iter().chain(g.accelerations){probe_vector(out,v);}probe_vector(out,g.closing_velocity);probe_floats(out,[g.maximum_closing_speed,g.opposing_contact,g.surface_twelve_height]);out.push(g.collision_flags);probe_vector(out,g.overall_normal);probe_vector(out,g.wheel_normal);out.extend(g.valid_wheel_normals.map(u32::from));out.extend([g.part_contact_count as u32,g.wheel_contact_count as u32,g.time_without_wheel_contact.to_bits()]);probe_floats(out,g.wheel_angular_drag);
 for p in [r.probes.deck,r.probes.wall]{for v in [p.start,p.point,p.normal]{probe_vector(out,v);}out.extend([p.surface_tag,p.hit as u32]);}
 let o=&r.reckoning;for v in [o.dynamic_up,o.up,o.target,o.up_velocity,o.ground_normal]{probe_vector(out,v);}out.push(o.ground_blend.to_bits());
 // Derived Debug exposes the private original filter words without modifying
 // the implementation, layout assumptions, unsafe memory reads or tolerances.
 let text=format!("{o:?}");let histories=text.split("words: [").skip(1).map(|s|s.split(']').next().unwrap()).collect::<Vec<_>>();assert_eq!(histories.len(),3);for h in histories{let words=h.split(',').map(|w|w.trim().parse::<u32>().unwrap()).collect::<Vec<_>>();assert_eq!(words.len(),24);out.extend(words);}
 let f=&r.reckoning_frames;for m in [f.ground,f.system,f.unflipped,f.inverse_system,f.body_flip]{probe_matrix(out,m);}probe_floats(out,f.heading);out.push(f.target_lean_angle.to_bits());probe_floats(out,f.lateral_tilt);out.extend(r.body_spin.words());let m=r.motion;for v in [m.angular_velocity,m.linear_velocity,m.ground_velocity]{probe_vector(out,v);}probe_floats(out,[m.speed,m.ground_speed,m.forward_speed]);probe_basis(out,m.effective_basis);out.push(r.heading_adjust_factor().to_bits());
}
fn batch_out(out:&mut Vec<u32>,b:&SkeletonDriveBatch){out.push(b.rows.len() as u32);for n in 0..b.rows.len(){constraint_drive(out,&b.rows[n]);match b.identities[n]{SkeletonDriveIdentity::Target(t)=>out.extend([0,t as u32,0]),SkeletonDriveIdentity::Bone{part,channel}=>out.extend([1,part as u32,channel as u32])};out.push(b.spy[n] as u32);}}
fn snapshot(out:&mut Vec<u32>,p:&mut GamePhysics,s:&mut SkaterRuntime){
 for b in p.board.bodies(){probe_body(out,*b);}probe_body(out,p.board.hook().body);out.extend(p.board.hook().drive.frames);out.extend(p.board.hook().drive.dynamics);for f in p.board.part_transforms(){affine_out(out,f);}affine_out(out,p.board.hook_transform());out.push(p.board.collision_group());
 probe_snapshot(out,&s.skeleton);constraint_drives(out,&s.skeleton_drives);collision_mode(out,&s.skeleton_collision);collision_feedback(out,&s.collision_feedback);collision_errors(out,&s.pose_errors);roots_out(out,&s.animated_skeleton.roots);board_frames_out(out,&s.animated_skeleton.board_frames);probe_animation_record(out,&s.animated_skeleton.record);
 let i=&s.skeleton_input;for v in [i.deck_velocity,i.root_velocity,i.previous_root_position,i.reset_local_hips]{probe_floats(out,v);}out.push(i.invalid_target_reset as u32);probe_matrix(out,i.animation_board_to_physics);for v in i.extra_target_positions{probe_floats(out,v);}for m in i.drive_frames{probe_matrix(out,m);}probe_floats(out,s.skeleton_output.correction.board_prediction_error);out.push(s.skeleton_output.correction.pending as u32);probe_floats(out,s.collision_pose_error);for v in s.collision_extra_errors{probe_floats(out,v);}out.extend([s.collision_maximum_error.is_some() as u32,s.collision_maximum_error.unwrap_or(0.).to_bits()]);out.push(s.solved_drives.is_some() as u32);if let Some(b)=&s.solved_drives{batch_out(out,b);}out.push(p.board.solved_contacts().len() as u32);for c in p.board.solved_contacts(){out.extend(c.words());out.extend([c.reaction_index_a as u32,c.reaction_index_b as u32]);}
 riding_out(out,&p.riding);out.extend([p.contact_count as u32,p.network_contacts as u32,p.ticks as u32,(p.ticks>>32) as u32,p.processed_flags_2468,p.board_wiping_out as u32,p.failed as u32]);let f=s.skateboard_controller.fields;out.extend([f.word_444,f.state_448,f.system_on_452 as u32]);let r=&s.board_possession.state;for m in [r.retrieval.initial_0,r.retrieval.target_64,r.retrieval.current_128]{probe_matrix(out,m);}probe_floats(out,[r.retrieval.elapsed_192,r.retrieval.duration_196,r.retrieval.progress_200,r.retrieval.weight_204]);for h in r.hands{probe_matrix(out,h.child);probe_matrix(out,h.parent);for d in h.dynamics{out.extend(d);}}out.push(r.selected_hand_424);out.push(p.network_proxies.bodies.len() as u32);for b in &p.network_proxies.bodies{probe_body(out,*b);}possession_live_out(out,p,s);
}
fn possession_fill_out(out:&mut Vec<u32>,f:skate_core::player::offboard::board_possession::Fill){probe_floats(out,[f.angle_36,f.angle_40]);out.extend([f.held_311,f.free_312,f.returning_313,f.hiding_321,f.flag_322,f.flag_323,f.flag_324].map(u32::from));}
fn possession_live_out(out:&mut Vec<u32>,p:&mut GamePhysics,s:&mut SkaterRuntime){
 let c=&p.settings;for m in [c.wheel_material,c.truck_material,c.deck_material]{probe_floats(out,[m.static_friction,m.dynamic_friction,m.restitution]);}out.extend([c.truck_collisions as u32,c.deck_geometry.children.len() as u32]);out.extend(c.deck_geometry.children.iter().map(|v|v.collision_enabled as u32));
 let l=&mut s.board_possession_live;out.extend([l.volumes.deck as u32,l.volumes.trucks as u32,l.volumes.wheels as u32,l.volumes.deck_children.len() as u32]);out.extend(l.volumes.deck_children.iter().map(|v|*v as u32));
 let(a,active,standard,released,drag)={let e=l.effects(p,&mut s.ground_lifecycle.board_animated_290,s.player_input.processed.timestep_2604);(*e.alignment,*e.alignment_active,e.standard_materials,e.released_material,e.standard_angular_drag)};
 probe_floats(out,a.first_1008);probe_floats(out,a.second_1024);out.extend([a.factor_1040.to_bits(),a.flag_1044 as u32,active as u32]);for m in standard.into_iter().chain([released]){probe_floats(out,[m.static_friction,m.dynamic_friction,m.restitution]);}out.push(drag.to_bits());out.push(l.output.is_some() as u32);if let Some(f)=l.output{possession_fill_out(out,f);}
}
fn mapped(e:&animation_pose::PoseEvaluator,s:&SkaterRuntime,kind:u32)->[AnimationPartTransform;24]{let pose=e.evaluate(&[skate_core::animation::playback_tree::PoseCommand::Pose{name:POSES[kind as usize].into()}]).unwrap();let globals=e.hierarchy(&pose).unwrap();map_animation_parts(&globals,&s.animated_skeleton.bone_indices,&s.animated_skeleton.physics_frames).unwrap()}
fn make(data:&skate_data::collections::Collections,assets:&std::path::Path,e:&animation_pose::PoseEvaluator,spawn:RetailAffineTransform,world:BoardWorld)->(GamePhysics,SkaterRuntime){
 let settings=physics::settings::PhysicsSettings::load(data).unwrap();let board=BoardRuntime::new(settings.masses,settings.authored,spawn,settings.step.simulation,BoardMotion::Active);let riding=physics::riding_outputs::RidingOutputs::load(data,&board,0x2000).unwrap();let mut p=GamePhysics{settings,board,world,riding,network_proxies:Default::default(),network_contacts:0,contact_count:0,query:WorldContactSettings{volume_padding:0.05,maximum_separating_distance:0.5,edge_cos_bend_normal_threshold:0.999,convexity_epsilon:0.01,is_object:false},retention:ContactRetentionSettings{capacity:u32::MAX,duplicate_distance_squared:-1.,deferred_reduction:true},board_wiping_out:false,processed_flags_2468:0x2000,ticks:0,failed:false};
 let globals=e.hierarchy(&e.evaluate(&[skate_core::animation::playback_tree::PoseCommand::Pose{name:"RIG_TPOSE".into()}]).unwrap()).unwrap();let physical=skate_data::physics_skeleton::PhysicsSkeleton::load(&assets.join("private/stock/physics-skeletons.json"),&e.frames.source_sha256,"PHYS_TPOSE").unwrap();assert_eq!(physical.bones.len(),24);let bone_indices=std::array::from_fn(|part|e.frames.bone_names.iter().position(|n|n.eq_ignore_ascii_case(&physical.bones[part].name)).unwrap());let physics_frames=std::array::from_fn(|part|{let b=&physical.bones[part];let t=b.translation();physics_bone_frame(b.rotation(),[t[0],t[1],t[2],0.])});let initial=map_animation_parts(&globals,&bone_indices,&physics_frames).unwrap();let spawn=physics::deck_frame(&p.board);
 let mut skeleton=physics::stock_body::load(assets,data,&e.frames.source_sha256,&initial,spawn,p.settings.step.simulation,None).unwrap();let mut roots=SkeletonRootFrames::default();roots.reset_initial_alignment(skeleton.animation_to_world);let mut board_frames=SkeletonBoardFrames::default();board_frames.reset(spawn);for _ in 0..2{board_frames.publish_centre_of_mass(skeleton.record.centre_of_mass,p.settings.step.simulation.time_step,0);}board_frames.publish_local_observations(&roots,&spawn);
 let joints=physics::stock_body::load_joints(assets,data,&e.frames.source_sha256,&globals,&e.frames.parents,&bone_indices).unwrap();let mut drives=physics::stock_body::load_drives(assets,data,&e.frames.source_sha256,&globals,&bone_indices,&initial,&joints,skeleton.animation_to_world,spawn,p.settings.step.simulation).unwrap();let targets=drives.targets.update_extra_targets(&mut skeleton,&board_frames.com_frame,&board_frames.lifted_com_frame);let target_positions=[targets.com,targets.lifted_com,targets.following_com];let collision=physics::stock_body::load_collision(assets,data,&e.frames.source_sha256,false).unwrap();let feedback=physics::stock_body::load_feedback(data,collision.settings).unwrap();let owner=physics::offboard::board_manager::Owner::load(data).unwrap();let live=physics::offboard::board_manager::runtime::LiveState::load(data,&p).unwrap();
 let s=SkaterRuntime{skeleton,skeleton_joints:joints,skeleton_drives:drives,skeleton_collision:collision,collision_feedback:feedback,pose_errors:SkeletonPoseErrors{targets:target_positions,..Default::default()},collision_pose_error:[0.;4],collision_extra_errors:[[0.;4];2],collision_maximum_error:None,solved_drives:None,animated_skeleton:physics::Animated{roots,board_frames,record:Default::default(),bone_indices,physics_frames},skeleton_input:physics::SkeletonInput{deck_velocity:[0.;4],root_velocity:[0.;4],previous_root_position:[0.;4],reset_local_hips:[0.;4],invalid_target_reset:false,animation_board_to_physics:IDENTITY,extra_target_positions:target_positions,drive_frames:initial},player_input:physics::PlayerInput{processed:Default::default(),toolkit:None,physical:Default::default()},skeleton_output:physics::Output{correction:Default::default(),pose:physics::OutputPose{board_bones:physics::BoardBones{front_truck:0,back_truck:0,front_left_wheel:0,front_right_wheel:0,back_left_wheel:0,back_right_wheel:0}}},skateboard_controller:Default::default(),board_possession:owner,board_possession_live:live,ground_lifecycle:physics::GroundLifecycle{board_animated_290:0},biped_ground:physics::Biped{controller:physics::BipedController{state:physics::BipedState{position_368:[0.;4],surface:0}}},animation:physics::Animation{evaluator:physics::Evaluator{frames:physics::FrameNames{bone_names:e.frames.bone_names.clone()}}},render_pose:globals};(p,s)
}
fn status(out:&mut Vec<u32>,r:Result<(),String>)->bool{match r{Ok(())=>{out.push(1);true},Err(e)=>{out.push(0);probe_error(out,&e);false}}}
fn reset_physical(p:&GamePhysics,s:&mut SkaterRuntime){s.skeleton_output.correction.pending=false;let o=skate_core::physics::skeleton_general::reset_to_animation(&mut s.skeleton,&mut s.animated_skeleton.record,&s.skeleton_input.drive_frames,&s.animated_skeleton.roots.animation_to_world,s.animated_skeleton.board_frames.com_frame,p.settings.step.simulation);let b=&mut s.animated_skeleton.board_frames;b.centre_of_mass=o.world_hips;b.previous_centre_of_mass=o.world_hips;b.com_velocity=[0.;4];s.skeleton_input.reset_local_hips=o.local_hips;s.pose_errors.reset_history();}
fn tick(i:&mut ProbeInput,out:&mut Vec<u32>,p:&mut GamePhysics,s:&mut SkaterRuntime,e:&animation_pose::PoseEvaluator){
 let kind=i.word();let dt=i.float();p.settings.step.iterations=i.word();p.processed_flags_2468=i.word();let state=i.word();let category=i.word();let flags2472=i.word();let flags2480=i.word();let flags2476=i.word();let flags2488=i.word();let spin=i.float();let balance=i.float();let coffin=i.word()!=0;let lift=i.float();let force=i.vector();let point=i.vector();let targets=i.floats();let gravity=i.float();
 p.board.clear_forces();if let Err(e)=p.riding.start_wheel_queries(&p.board,&p.world){status(out,Err(e));return;}let frames=mapped(e,s,kind);s.animated_skeleton.record.update(&frames,&s.animated_skeleton.roots.animation_to_board,&s.skeleton.definition.animation_masses);s.skeleton_input.deck_velocity=four(p.board.bodies()[6].rates.linear_velocity);for b in s.skeleton.bodies_mut(){if b.state_flags&7==2{b.state_flags=(b.state_flags&8)|4;}b.rates.cool_down=0;}
 if let Err(e)=p.riding.finish_wheel_queries(){status(out,Err(e));return;}let input=&mut s.player_input.processed;input.state_2508=state;input.category_2512=category;input.flags_2472=flags2472;input.flags_2480=flags2480;input.flags_2468=p.processed_flags_2468;input.timestep_2604=dt;input.wheel_count_2556=p.riding.ground.wheel_contact_count as u32;input.scalar_2652=p.riding.motion.speed;input.scalar_2616=p.riding.motion.ground_speed;input.vectors_464_480_496_512_528[0]=four(p.riding.ground.wheel_normal).map(f32::to_bits);input.vectors_464_480_496_512_528[1]=four(p.riding.ground.parts[6].point).map(f32::to_bits);input.vectors_464_480_496_512_528[2]=input.vectors_464_480_496_512_528[1];input.vectors_464_480_496_512_528[4]=four(p.riding.ground.overall_normal).map(f32::to_bits);input.vectors_880_896_912_928_944[0]=frames[23][3].map(f32::to_bits);input.vectors_880_896_912_928_944[1]=[0.,1.,0.,0.].map(f32::to_bits);
 p.riding.update_ground_reckoning(&p.board,physics::riding_outputs::RidingPoseInputs{com_to_deck:s.animated_skeleton.record.com_to_deck(),body_spin:spin},p.processed_flags_2468,balance,coffin,input);
 let a=&mut s.animated_skeleton;a.board_frames.update_com_lift(&a.roots.animation_to_world,frames[23][3],lift);a.roots.initialize_heading=true;a.roots.update(physics::deck_frame(&p.board),four(p.board.bodies()[6].rates.linear_velocity),dt,&frames[0],&p.riding.reckoning_frames.system);a.board_frames.prepare_ground(&a.roots,&a.record.pose[0],a.roots.board,&mut p.processed_flags_2468);s.skeleton_input.root_velocity=skate_core::physics::skeleton_general::root_velocity(&mut s.skeleton_input.previous_root_position,a.roots.animation_to_world[3],dt);
 let target=s.skeleton_drives.targets.update_positions(SkeletonTargetInput{animation_hips:&frames[23],animation_board:&frames[0],animation_to_world:&a.roots.animation_to_world,inverse_board:&a.roots.inverse_board,skate_root:&a.board_frames.skate_root,com_frame:&a.board_frames.com_frame,lifted_com_frame:&a.board_frames.lifted_com_frame,teleporting:false},&mut s.skeleton);s.skeleton_input.animation_board_to_physics=target.animation_board_to_physics;s.skeleton_input.extra_target_positions=[target.positions.com,target.positions.lifted_com,target.positions.following_com];s.pose_errors.set_targets(target.positions);if !target.continuous{reset_physical(p,s);if state!=0&&state!=702{s.skeleton_input.invalid_target_reset=true;}}s.skeleton_input.drive_frames=frames;s.skeleton_drives.update(&frames,s.skeleton_collision.partial_ragdoll,s.collision_feedback.drive_weight);skate_core::physics::skeleton_general::apply_gravity_displacement(&mut s.skeleton,gravity);
 p.board.forces_mut().append(QueuedPointForce{tag:p.ticks as u32,force_world:force,point_body:point});let cached=physics::deck_frame(&p.board);let input=&mut s.player_input.processed;input.effective_anim_transform_192=s.animated_skeleton.roots.animation_to_world.map(|v|v.map(f32::to_bits));input.vectors_544_560_592_608[2]=s.skeleton.record.centre_of_mass.map(f32::to_bits);input.vectors_400_416[0]=frames[0][2].map(f32::to_bits);input.flags_2476=flags2476;input.flags_2488=flags2488;s.player_input.toolkit=Some(skate_core::physics::board_toolkit::BoardToolkit::calculate(cached,&p.board.bodies().iter().map(|b|b.inertia.inverse_mass).collect::<Vec<_>>(),0,0.,[0.,1.,0.,0.],[0.,1.,0.,0.]));physics::offboard::board_manager::runtime::update(p,s);
 if let Err(e)=physics::advance(p,s,targets){status(out,Err(e));return;}let input=&mut s.player_input.processed;input.vectors_544_560_592_608[0]=s.animated_skeleton.roots.animation_to_world[1].map(f32::to_bits);input.time_on_ground_2752=p.ticks as f32*dt;p.riding.probes.prepare_wall(input,s.player_input.toolkit.as_ref().unwrap());p.riding.finish_post_physics(&mut p.board,p.board_wiping_out,p.processed_flags_2468,p.settings.step.simulation.time_step).unwrap();physics::publish(p,s);physics::offboard::board_manager::runtime::publish(p,s);p.ticks+=1;out.push(1);
}
fn append_proxy(i:&mut ProbeInput,p:&mut GamePhysics,s:&SkaterRuntime){let offset=i.vector();let age=i.float();let q=i.floats();let lo=i.word();let hi=i.word();let bodies=p.board.bodies().iter().chain(s.skeleton.bodies()).map(|b|Body{pose:Pose{p:[b.rates.position.x+offset.x,b.rates.position.y+offset.y,b.rates.position.z+offset.z],q},velocity:[0.;3],angular:[0.;3]}).collect();let frame=packed::BodyState{root:Pose{p:[0.;3],q},enabled:u64::from(lo)|(u64::from(hi)<<32),bodies};let schema=physics::network::Schema::new(p,s).unwrap();let mut proxies=std::mem::take(&mut p.network_proxies);proxies.append(&frame,&schema,p,s,age);p.network_proxies=proxies;}
fn main(){
 let args=std::env::args().collect::<Vec<_>>();let assets=std::path::Path::new(&args[1]);let data=skate_data::collections::Collections::load(assets).unwrap();let e=animation_pose::PoseEvaluator::from_banks(&skate_data::animation_banks::AnimationBanks::load(assets).unwrap()).unwrap();let stock=physics::settings::PhysicsSettings::load(&data).unwrap();let mut bytes=Vec::new();std::io::stdin().read_to_end(&mut bytes).unwrap();let mut i=ProbeInput{words:bytes.chunks_exact(4).map(|b|u32::from_le_bytes(b.try_into().unwrap())).collect(),at:0};let mut out=Vec::new();let cases=i.word();
 for c in 0..cases{let spawn=i.affine();let world=i.world(stock.floor_material);let seams=i.word()!=0;let(mut p,mut s)=make(&data,assets,&e,spawn,world);if seams{p.world.enable_imported_floor_seams();}let n=i.word();out.extend([c,n,0]);let mark=out.len()-1;let initial=out.len();out.push(0);snapshot(&mut out,&mut p,&mut s);out[initial]=(out.len()-initial-1) as u32;for _ in 0..n{let op=i.word();out.extend([op,0]);let at=out.len()-1;match op{
  0=>tick(&mut i,&mut out,&mut p,&mut s,&e),1=>{p.board.clear_forces();let result=p.riding.start_wheel_queries(&p.board,&p.world);status(&mut out,result);},2=>{status(&mut out,p.riding.finish_wheel_queries());},3=>p.riding.reset_for_teleport(),4=>p.world=i.world(p.settings.floor_material),5=>{let result=s.skeleton_collision.select_driven(i.word()).map_err(str::to_string);status(&mut out,result);},6=>{s.skeleton_output.correction.pending=i.word()!=0;let flags=i.word();let flags2476=i.word();s.skeleton_output.correction.apply(&mut s.skeleton,four(p.riding.reckoning.ground_normal),i.word()!=0,flags,flags2476);},7=>s.skateboard_controller.fields=skate_core::player::lifecycle::SkateboardControllerFields{word_444:i.word(),state_448:i.word(),system_on_452:i.word()!=0},8=>append_proxy(&mut i,&mut p,&s),9=>p.network_proxies=Default::default(),10=>{let o=physics::offboard::board_manager::runtime::observe(&p,&s);let mut effects=s.board_possession_live.effects(&mut p,&mut s.ground_lifecycle.board_animated_290,s.player_input.processed.timestep_2604);s.board_possession.hold(&mut s.skateboard_controller.fields,&o,&mut effects);s.board_possession_live.publish_volumes(&mut p);},_=>panic!("Composition command")};snapshot(&mut out,&mut p,&mut s);out.extend([p.contact_count as u32,p.network_contacts as u32,p.board.solved_contacts().len() as u32,s.solved_drives.as_ref().map_or(0,|b|b.rows.len()) as u32,p.network_proxies.bodies.len() as u32,p.riding.ground.part_contact_count as u32,p.riding.ground.wheel_contact_count as u32,s.ground_lifecycle.board_animated_290 as u32]);out[at]=(out.len()-at-1) as u32;}out[mark]=(out.len()-mark-1) as u32;}
 assert_eq!(i.at,i.words.len());let mut stdout=std::io::BufWriter::new(std::io::stdout().lock());for w in out{stdout.write_all(&w.to_le_bytes()).unwrap();}
}
