// Full unchanged original host manager; only transport/observation adapters.
use skate_core::{player::input_phase::*,animation::output::{actor_packet::ExternalPhysicsInput,attributes::AttributeName},input::animation_packet::AnimationPacketFields};
use skate_core::physics::grind_contact::{balance::{BalanceState,TargetUpInput,ExitLeanInput,BalanceVectors},control::Control,entry::Engagement,manager::{Jumper,JumpGeometry,GeometryInput}};
use skate_core::air::trajectory::grind_surface::{Probe,ProbeHit,InvestigationInput,GrindSurface,GeometryType,Investigation};
use physics::player_input::grind::{GrindInputState,PreContext,PostContext,Pending,Host,MaterialMode};
type Input=Reader;type Output=Writer;
impl Reader{
    fn wide(&mut self)->u64{let low=self.word();low as u64|((self.word()as u64)<<32)}
    fn float(&mut self)->f32{self.scalar()}fn words<const N:usize>(&mut self)->[u32;N]{std::array::from_fn(|_|self.word())}
    fn text(&mut self)->String{let n=self.word();String::from_utf8((0..n).map(|_|self.word()as u8).collect()).unwrap()}
}
impl Writer{fn wide(&mut self,w:u64){self.word(w as u32);self.word((w>>32)as u32);}fn float(&mut self,v:f32){self.scalar(v);}}
fn geometry_kind(v:u32)->GeometryType{match v{0=>GeometryType::ThinRail,1=>GeometryType::FatRail,2=>GeometryType::Ledge,3=>GeometryType::Impossible,_=>panic!("invalid geometry discriminant")}}
// GENERATED_PROTOCOL
fn read_provider(i:&mut Input)->grind_world::StaticProvider{
    use skate_data::skate_map::{Rail,SkateMap,Geometry,Extension};let count=i.word();let rails=(0..count).map(|_|{
        let name=i.text();let closed=i.word()!=0;let points=i.word();let points=(0..points).map(|_|std::array::from_fn(|_|i.float())).collect();let native=if i.word()!=0{let n=i.word();Some((0..n).flat_map(|_|i.word().to_le_bytes()).collect())}else{None};Rail{name,closed,points,native}
    }).collect();let manifest=i.text();
    // Consume the independent native converted transport. The expected provider
    // is constructed by the real original package/WMET reader, never this data.
    let segments=i.word();for _ in 0..segments{for _ in 0..8{i.float();}i.wide();i.wide();i.wide();i.word();i.word();for _ in 0..6{i.float();}i.wide();}
    let guids=i.word();for _ in 0..guids{i.wide();i.wide();}let assets=i.word();for _ in 0..assets{i.text();i.text();i.wide();i.wide();i.word();let n=i.word();for _ in 0..n{i.word();}}
    let map=SkateMap{version:15,name:"independent-fixture".into(),spawn:[0.;3],heading:0.,environment:vec![],materials:vec![],textures:vec![],geometry:Geometry{vertices:vec![],indices:vec![],collision:vec![]},rails,doors:vec![],lights:vec![],routes:vec![],extensions:vec![Extension{tag:*b"WMET",schema:1,payload:manifest.into_bytes()}]};grind_world::StaticProvider::new(Some(&map)).unwrap()
}
fn observe_provider(o:&mut Output,p:&grind_world::StaticProvider){
    o.word(p.primitives().len()as u32);for(index,edge)in p.primitives().iter().enumerate(){for v in edge.start.into_iter().chain(edge.end){o.float(v);}o.wide(edge.owner);let m=p.metadata(index).unwrap();for v in m.spline_guids{o.wide(v);}o.word(m.segment_index);o.word(m.flags);let(min,max)=p.bounds(index).unwrap();for v in min.into_iter().chain(max){o.float(v);}let s=p.source(index).unwrap();o.error(Some(&s.stream_file));o.error(Some(&s.asset_id));o.wide(s.section_index);o.wide(s.section_offset);o.wide(p.source_rail_index(index).unwrap());}
    let query=p.query([-1.2;3],[1.2;3]).unwrap();o.word(query.len()as u32);for index in query{o.word(index as u32);}
}
fn fixture_world(kind:u32)->BoardWorld{
    let corners=match kind{2=>[[-0.06,-0.05,-4.],[0.06,-0.05,-4.],[0.06,-0.05,4.],[-0.06,-0.05,4.]],3=>[[0.,-0.05,-4.],[4.,-0.05,-4.],[4.,-0.05,4.],[0.,-0.05,4.]],5=>[[-4.,-0.05,0.34],[4.,-0.05,0.34],[4.,-0.05,4.],[-4.,-0.05,4.]],_=>[[-4.,-0.05,-4.],[4.,-0.05,-4.],[4.,-0.05,4.],[-4.,-0.05,4.]]};let mut triangles=vec![];let mut surfaces=vec![];let mut meshes=vec![];
    if kind!=0{for ids in [[0,2,1],[0,3,2]]{let vertices=ids.map(|j|Vector3::new(corners[j][0],corners[j][1],corners[j][2]));triangles.push(WorldTriangle{triangle:triangle_from_volume(vertices,0.25,[1.;3],0x10),material:RetailContactMaterial{static_friction:0.8,dynamic_friction:0.6,restitution:0.1},tag:triangles.len()as u32+1});surfaces.push(if kind==4{0x40b}else{0x20b});}meshes.push(QueryMesh{triangle_range:0..triangles.len(),local_to_world:RetailAffineTransform::IDENTITY,world_to_local:RetailAffineTransform::IDENTITY,local_bounds:Bounds{min:Vector3::new(-4.,-0.05,-4.),max:Vector3::new(4.,-0.05,4.)},matching_group:-1,rejection_flags:u32::MAX,geometry:77,pool:if kind==4{QueryPool::Conditional}else{QueryPool::Ground}});}
    BoardWorld::with_query_metadata(triangles,QueryMetadata{packed_surfaces:surfaces,meshes,static_edges:vec![],island_flags:3}).unwrap()
}
fn observe_plan(o:&mut Output,p:&Investigation){for v in [p.center,p.upmost_normal,p.direction]{for x in v{o.float(x);}}o.word(p.probes.len()as u32);for p in &p.probes{observe_Probe(o,p);}}
fn observe_observation(o:&mut Output,m:&physics::grind::ManagerObservation){
    let g=&m.geometry;for v in [g.point_1120,g.direction_1136,g.normal_1152,g.target_up_1168,g.primitive_start_1264,g.primitive_end_1280]{for x in v{o.float(x);}}o.word(g.spline_guids_1296.is_some()as u32);if let Some(v)=g.spline_guids_1296{for x in v{o.wide(x);}}for v in[g.upmost_normal_1408,g.high_side_1440]{for x in v{o.float(x);}}o.word(g.kind_1464);o.word(g.flags_1476);o.float(g.impact_speed_1492);
    let s=&m.surface;o.word(s.audio_surface_1468);o.word(s.material_1472);o.float(s.friction_vs_time_1496);o.float(s.reckon_blend_selector_1500);o.float(s.gravity_relief_1512);let c=&m.control;o.word(c.family as u32);o.word(c.flags_1516);o.word(c.flags_2468);o.word(c.flags_2488);o.float(c.translation_2796);o.float(c.balance_2800);o.float(c.exit_lean);for v in m.engagement.velocity_1184{o.float(v);}o.word(m.engagement.kind_1248);let j=&m.jumper;o.word(j.geometry_kind_16);o.word(j.family_20 as u32);o.float(j.energy_24);for v in[j.high_side_32,j.normal_48,j.direction_64,j.upmost_normal_80,j.point_96]{for x in v{o.float(x);}}
}
fn fixture_board()->skate_core::physics::board_runtime::BoardRuntime{
    use skate_core::physics::{rigid_body::{RetailBodyMassProperties,RetailLocalMassFrame,RetailInertiaDynamics,RetailSimulationStep},board_runtime::{BoardRuntime,BoardMotion}};
    let masses=[RetailBodyMassProperties{local_mass_frame:RetailLocalMassFrame::IDENTITY,dynamics:RetailInertiaDynamics{inverse_tensor:Vector3::new(1.,1.,1.),inverse_mass:1.,spherical:1.,maximum_linear_velocity:100.,maximum_angular_velocity:100.,linear_drag:0.,angular_drag:0.}};7];let mut board=BoardRuntime::new(masses,[RetailAffineTransform::IDENTITY;7],RetailAffineTransform::IDENTITY,RetailSimulationStep::fixed_60_hz(8,0.001,Vector3::new(0.,-9.81,0.)),BoardMotion::Active);board.set_collision_group(7);board
}
struct LiveHost{trace:Output,fail:u32,calls:u32,board:skate_core::physics::board_runtime::BoardRuntime,settings:physics::settings::PhysicsSettings,materials:physics::grind_materials::GrindMaterials}
impl LiveHost{fn done(&mut self)->Result<(),String>{self.calls+=1;if self.calls==self.fail{Err(format!("injected callback {}",self.calls))}else{Ok(())}}fn observe(&self,o:&mut Output){o.word(self.board.collision_group());for m in[self.settings.wheel_material,self.settings.truck_material,self.settings.deck_material]{o.float(m.static_friction);o.float(m.dynamic_friction);o.float(m.restitution);}}}
impl Host for LiveHost{
    fn apply_material_mode(&mut self,m:MaterialMode)->Result<(),String>{self.trace.word(1);self.trace.word(match m{MaterialMode::Unchanged=>0,MaterialMode::Standard=>1,MaterialMode::Grind=>2});self.materials.apply(m,&mut self.board,&mut self.settings);self.done()}
    fn surface_probe(&mut self,w:&BoardWorld,a:[u32;2],index:usize,p:Probe)->Result<Option<ProbeHit>,String>{self.trace.word(2);for v in a{self.trace.word(v);}self.trace.word(index as u32);observe_Probe(&mut self.trace,&p);let h=physics::player_input::grind::world::surface_probe(w,a,index,p)?;self.trace.word(h.is_some()as u32);if let Some(h)=h{observe_ProbeHit(&mut self.trace,&h);}self.done()?;Ok(h)}
    fn force_exit_line(&mut self,w:&BoardWorld,a:[u32;2],p:skate_core::physics::grind_contact::balance::ForceExitProbe)->Result<Option<skate_core::physics::grind_contact::balance::ForceExitHit>,String>{self.trace.word(3);for v in a{self.trace.word(v);}for v in[p.start,p.end]{for x in v{self.trace.float(x);}}let h=physics::player_input::grind::world::force_exit_line(w,a,p)?;self.trace.word(h.is_some()as u32);if let Some(h)=h{for v in h.normal{self.trace.float(v);}}self.done()?;Ok(h)}
}
fn main(){
    let args:Vec<_>=std::env::args().collect();let data=skate_data::collections::Collections::load(std::path::Path::new(&args[1])).unwrap();if args.len()==3{let mut o=Output{words:vec![]};match GrindInputState::load(&data){Ok(state)=>{o.word(1);physics::player_input::grind::observe_state(&mut o,&state);physics::player_input::grind::observe_settings(&mut o,&state);},Err(e)=>{o.word(0);o.error(Some(&e));}}std::io::stdout().write_all(&o.words.into_iter().flat_map(u32::to_le_bytes).collect::<Vec<_>>()).unwrap();return;}let mut bytes=vec![];std::io::stdin().read_to_end(&mut bytes).unwrap();let mut i=Input{bytes,at:0};let mut out=Output{words:vec![]};let count=i.word();
    for c in 0..count{let provider=read_provider(&mut i);let world=fixture_world(i.word());let mut state=GrindInputState::load(&data).unwrap();let mut pending:Option<Pending>=None;let mut p=ProcessedPhysicsInput::default();let standard=[RetailContactMaterial{static_friction:0.8,dynamic_friction:0.5,restitution:0.03},RetailContactMaterial{static_friction:0.3,dynamic_friction:0.2,restitution:0.01},RetailContactMaterial{static_friction:0.6,dynamic_friction:0.4,restitution:0.02}];let settings=physics::settings::PhysicsSettings{standard_wheel_material:standard[0],wheel_material:standard[0],truck_material:standard[1],deck_material:standard[2]};let materials=physics::grind_materials::GrindMaterials::new(&settings);let mut host=LiveHost{trace:Output{words:vec![]},fail:0,calls:0,board:fixture_board(),settings,materials};let mut initial=Output{words:vec![]};observe_provider(&mut initial,&provider);physics::player_input::grind::observe_state(&mut initial,&state);host.observe(&mut initial);out.word(c);out.word(initial.words.len()as u32);out.words.extend(initial.words);let commands=i.word();out.word(commands);
        for _ in 0..commands{let op=i.word();host.trace.words.clear();host.calls=0;host.fail=0;let mut post=None;let result=match op{
            0=>{p=read_ProcessedPhysicsInput(&mut i);let context=read_PreContext(&mut i);host.fail=i.word();match state.pre_update(&p,&provider,&world,context,&mut host){Ok(value)=>{pending=Some(value);Ok(())},Err(e)=>Err(e)}},
            1=>{p=read_ProcessedPhysicsInput(&mut i);let context=read_PostContext(&mut i);host.fail=i.word();if let Some(value)=pending.take(){match state.post_update(&mut p,&world,value,context,&mut host){Ok(value)=>{post=Some(value);Ok(())},Err(e)=>Err(e)}}else{Err("missing pre result".into())}},
            2=>{state.reset();Ok(())},3=>{physics::player_input::grind::seed_state(&mut i,&mut state);Ok(())},_=>panic!("invalid operation")};
            let mut row=Output{words:vec![]};row.word(op);row.word(result.is_ok()as u32);row.error(result.as_ref().err().map(String::as_str));row.word(host.calls);row.word(host.trace.words.len()as u32);row.words.extend(host.trace.words.iter());physics::player_input::grind::observe_state(&mut row,&state);observe_ProcessedPhysicsInput(&mut row,&p);host.observe(&mut row);row.word(pending.is_some()as u32);if let Some(p)=&pending{physics::player_input::grind::observe_pending(&mut row,p);}row.word(post.is_some()as u32);if let Some(p)=post{row.word(p.wipeout_reasons.len()as u32);for reason in p.wipeout_reasons{row.word(reason as u32);}observe_observation(&mut row,&p.observation);}out.word(row.words.len()as u32);out.words.extend(row.words);
        }}assert_eq!(i.at,i.bytes.len());std::io::stdout().write_all(&out.words.into_iter().flat_map(u32::to_le_bytes).collect::<Vec<_>>()).unwrap();
}
