use math::Vector3;use riding::{reckoning_frames::ReckoningFrames,collision_response::signed_angle};use point_graph::PointGraph;use std::io::{Read,Write};
struct Input{w:Vec<u32>,at:usize}
impl Input{fn word(&mut self)->u32{let w=self.w[self.at];self.at+=1;w}fn float(&mut self)->f32{f32::from_bits(self.word())}fn three(&mut self)->Vector3{Vector3::new(self.float(),self.float(),self.float())}fn four(&mut self)->[f32;4]{std::array::from_fn(|_|self.float())}fn matrix(&mut self)->[[f32;4];4]{std::array::from_fn(|_|self.four())}fn curve(&mut self)->PointGraph<8>{PointGraph{x:std::array::from_fn(|_|self.float()),y:std::array::from_fn(|_|self.float())}}}
fn floats(o:&mut Vec<u32>,v:impl IntoIterator<Item=f32>){o.extend(v.into_iter().map(f32::to_bits));}
fn state(o:&mut Vec<u32>,r:&ReckoningFrames){for m in [r.ground,r.system,r.unflipped,r.inverse_system,r.body_flip]{for c in m{floats(o,c);}}floats(o,r.heading);o.push(r.target_lean_angle.to_bits());floats(o,r.lateral_tilt);}
fn main(){let mut bytes=Vec::new();std::io::stdin().read_to_end(&mut bytes).unwrap();let mut i=Input{w:bytes.chunks_exact(4).map(|b|u32::from_le_bytes(b.try_into().unwrap())).collect(),at:0};let mut o=Vec::new();let cases=i.word();for c in 0..cases{let op=i.word();o.extend([c,op,0]);let size=o.len()-1;
 if op==0{let a=i.three();let b=i.three();let axis=i.three();o.push(signed_angle(a,b,axis).to_bits());}
 else if op==1{let mut r=ReckoningFrames::new();if i.word()!=0{r.ground=i.matrix();r.system=i.matrix();r.unflipped=i.matrix();r.inverse_system=i.matrix();r.body_flip=i.matrix();r.heading=i.four();r.target_lean_angle=i.float();r.lateral_tilt=i.four();}let angle_curve=i.curve();let up_curve=i.curve();let n=i.word();o.push(n);state(&mut o,&r);for _ in 0..n{match i.word(){0=>{let up=i.four();let normal=i.four();r.calculate_transform(up,normal);},1=>{let up=i.four();let dynamic_up=i.four();r.calculate_dynamic_lean(up,dynamic_up);},2=>r.calculate_tilt(i.word()!=0,&angle_curve,&up_curve),3=>r.body_flip=i.matrix(),4=>r.ground[3]=i.four(),5=>r.system[3]=i.four(),6=>r=ReckoningFrames::new(),_=>panic!()};state(&mut o,&r);}}
 else{panic!()};o[size]=(o.len()-size-1) as u32;}assert_eq!(i.at,i.w.len());let mut stdout=std::io::BufWriter::new(std::io::stdout().lock());for w in o{stdout.write_all(&w.to_le_bytes()).unwrap();}}
