// Complete original stock body/joint/drive and collision/feedback loaders.
use skate_core::physics::drive_parameters::{RetailDriveParams,RetailDriveDynamics};
use skate_core::physics::drive_frames::RetailDriveFrames;
#[path="../../crates/skate-host/src/physics/skeleton_body.rs"]mod stock;
impl ProbeInput{
 fn text(&mut self)->String{let n=self.word();String::from_utf8((0..n).map(|_|self.word() as u8).collect()).unwrap()}
 fn hierarchy(&mut self)->Vec<AnimationPartTransform>{let n=self.word();(0..n).map(|_|self.matrix()).collect()}
 fn indices(&mut self)->[usize;24]{std::array::from_fn(|_|self.word() as usize)}
}
fn settings_params(out:&mut Vec<u32>,p:RetailDriveParams){probe_floats(out,[p.spring_or_max_velocity,p.damping,p.max_strength]);out.push(p.drive_type as u32);}
fn settings_dynamics(out:&mut Vec<u32>,d:RetailDriveDynamics){settings_params(out,d.linear);settings_params(out,d.angular);}
fn settings_frames(out:&mut Vec<u32>,f:RetailDriveFrames){for p in [f.body_a,f.body_b]{probe_floats(out,[p.orientation.x,p.orientation.y,p.orientation.z,p.orientation.w]);probe_vector(out,p.translation);}}
fn settings_bone(out:&mut Vec<u32>,s:BoneDriveSettings){for a in s.animation{probe_floats(out,[a.linear_strength,a.linear_displacement,a.angular_strength,a.angular_displacement]);}probe_floats(out,[s.collision_soft_displacement,s.collision_soft_strength,s.ragdoll_soft_displacement,s.ragdoll_soft_strength]);for t in [s.transition_linear,s.transition_angular]{probe_floats(out,t.spring);probe_floats(out,t.strength);probe_floats(out,t.damping);}out.push(s.transition_calls.to_bits());}
fn settings_drives(out:&mut Vec<u32>,d:&SkeletonDrives){for b in d.targets.bodies{probe_body(out,b);}for f in d.targets.frames{settings_frames(out,f);}for p in d.targets.dynamics{settings_dynamics(out,p);}for n in 0..4{probe_matrix(out,d.targets.transform(n));}for p in &d.bones{out.push(p.is_some() as u32);let Some(p)=p else{continue;};out.extend(p.parent.map(|v|v as u32));out.extend(p.active.map(|v|v as u32));for f in p.frames{settings_frames(out,f);}for d in p.dynamics.channels{settings_dynamics(out,d);}out.push(p.dynamics.mode);probe_floats(out,p.dynamics.strengths);out.extend([p.dynamics.transition_counter.to_bits(),p.dynamics.transition_active as u32]);}settings_bone(out,d.settings.bone);out.push(d.settings.enabled as u32);probe_floats(out,d.settings.strength);for p in d.settings.collision_strength{probe_floats(out,p);}}
fn settings_joints(out:&mut Vec<u32>,j:&SkeletonJoints){for r in j.records{out.extend([r.parent as u32,r.child as u32]);out.extend(r.parameters.words);out.extend(r.frames.words);}}
fn settings_mode(out:&mut Vec<u32>,m:&SkeletonCollisionMode){for p in m.parts{out.extend([p.enabled as u32,p.volume_group,p.part_group]);probe_floats(out,[p.material.static_friction,p.material.dynamic_friction,p.material.restitution]);}out.extend(m.disable_count);out.extend([m.pending_reenable as u32,m.assembly_group,m.partial_ragdoll as u32,m.is_ragdoll as u32]);for row in m.self_culling{out.extend(row.map(|v|v as u32));}let s=m.settings;out.push(s.enabled as u32);probe_floats(out,[s.normal_material.static_friction,s.normal_material.dynamic_friction,s.normal_material.restitution]);out.extend(s.compliant.map(|v|v as u32));probe_floats(out,s.priority);out.push(s.effect_time.to_bits());}
fn settings_feedback(out:&mut Vec<u32>,a:&SkeletonCollisionFeedback){probe_floats(out,a.contact_age);probe_floats(out,a.priority);out.extend(a.compliant.map(|v|v as u32));out.extend(a.current.map(|v|v as u32));for b in a.bones{for v in [b.normal,b.specific_normal,b.tangent,b.specific_tangent,b.point]{probe_floats(out,v);}probe_floats(out,[b.force,b.specific_force]);out.extend([b.tag,b.specific_tag]);out.extend(b.groups.map(|v|v as u32));}for r in a.regions{probe_floats(out,[r.force,r.weighted_force,r.tangent_speed]);out.push(r.material_flags);probe_floats(out,r.normal);out.push(r.part.map(|v|v as u32).unwrap_or(u32::MAX));}out.push(a.planes.len() as u32);for p in &a.planes{probe_floats(out,p.normal);out.push(p.part as u32);}for p in a.specific{out.push(p.part as u32);probe_floats(out,p.local_point);probe_floats(out,p.world_point);out.extend([p.radius_squared.to_bits(),p.current as u32,p.recent as u32]);}probe_floats(out,a.highest_normal);probe_floats(out,a.foot_normal);for p in a.material_normals{probe_floats(out,p);}probe_floats(out,[a.timer,a.drive_weight,a.maximum_priority]);probe_floats(out,a.wipeout_times);out.extend([a.maximum_skater_force.to_bits(),a.other_skater as u32,a.maximum_group_8_force.to_bits(),a.maximum_group_11_force.to_bits(),a.material_12_height.to_bits()]);let f=a.flags;out.extend([f.material_6,f.noncompliant,f.compliant,f.recovering,f.group_8,f.nonboard,f.ragdoll,f.conflicting,f.impaled,f.has_impulse,f.foot_board,f.material_10,f.material_11,f.material_12,f.any].map(|v|v as u32));}
fn main(){
 let args=std::env::args().collect::<Vec<_>>();let root=std::path::Path::new(&args[1]);let data=skate_data::collections::Collections::load(root).unwrap();let bank=&args[2];
 let mut bytes=Vec::new();std::io::stdin().read_to_end(&mut bytes).unwrap();let mut i=ProbeInput{words:bytes.chunks_exact(4).map(|b|u32::from_le_bytes(b.try_into().unwrap())).collect(),at:0};let mut out=Vec::new();let count=i.word();
 for index in 0..count{let op=i.word();out.extend([index,op,0]);let mark=out.len()-1;let start=out.len();match op{
  0=>{let hat=i.word()!=0;let key=i.text();let mapped=i.matrices();let spawn=i.matrix();let sim=i.simulation();match stock::load(root,&data,bank,&mapped,spawn,sim,hat.then_some(key.as_str())){Ok(body)=>{out.push(1);probe_definition(&mut out,&body.definition);probe_snapshot(&mut out,&body);},Err(e)=>{out.push(0);probe_error(&mut out,&e);}}},
  1=>{let all=i.word()!=0;match stock::load_collision(root,&data,bank,all){Ok(mode)=>{out.push(1);settings_mode(&mut out,&mode);match stock::load_feedback(&data,mode.settings){Ok(feedback)=>{out.push(1);settings_feedback(&mut out,&feedback);},Err(e)=>{out.push(0);probe_error(&mut out,&e);}}},Err(e)=>{out.push(0);probe_error(&mut out,&e);}}},
  2=>{let hierarchy=i.hierarchy();let n=i.word();let parents=(0..n).map(|_|i.word() as i32).collect::<Vec<_>>();let indices=i.indices();let joints=stock::load_joints(root,&data,bank,&hierarchy,&parents,&indices);match &joints{Ok(j)=>{out.push(1);settings_joints(&mut out,j);},Err(e)=>{out.push(0);probe_error(&mut out,e);}}let drives=i.word()!=0;if drives{let hierarchy=i.hierarchy();let indices=i.indices();let mapped=i.matrices();let alignment=i.matrix();let spawn=i.matrix();let sim=i.simulation();if let Ok(joints)=joints{match stock::load_drives(root,&data,bank,&hierarchy,&indices,&mapped,&joints,alignment,spawn,sim){Ok(value)=>{out.push(1);settings_drives(&mut out,&value);},Err(e)=>{out.push(0);probe_error(&mut out,&e);}}}else{out.push(2);}}},_=>panic!("Stock skeleton setting operation")}
  out[mark]=(out.len()-start) as u32;
 }assert_eq!(i.at,i.words.len());let mut stdout=std::io::BufWriter::new(std::io::stdout().lock());for w in out{stdout.write_all(&w.to_le_bytes()).unwrap();}
}
