// The checker prepends the public record adapters from skeleton_body_probe.rs.
use crate::physics::{drive_parameters::{RetailDriveParams,RetailDriveDynamics,RetailDriveType},drive_frames::{RetailDriveFrame,RetailDriveFrames},drive_solver::RetailDriveRows};
use crate::physics::{solver::{packed,JointConstraint},contact_solver::RetailContactJacobian};
#[path="physics/solver/packing.rs"] mod skeleton_constraint_packing;
impl ProbeInput{
 fn parents(&mut self)->[Option<usize>;24]{std::array::from_fn(|_|{let w=self.word();if w==u32::MAX{None}else{Some(w as usize)}})}
 fn drive_settings(&mut self)->BoneDriveSettings{BoneDriveSettings{animation:std::array::from_fn(|_|AnimationDriveSettings{linear_strength:self.float(),linear_displacement:self.float(),angular_strength:self.float(),angular_displacement:self.float()}),collision_soft_displacement:self.float(),collision_soft_strength:self.float(),ragdoll_soft_displacement:self.float(),ragdoll_soft_strength:self.float(),transition_linear:DriveInterpolation{spring:self.floats(),strength:self.floats(),damping:self.floats()},transition_angular:DriveInterpolation{spring:self.floats(),strength:self.floats(),damping:self.floats()},transition_calls:self.float()}}
 fn params(&mut self)->RetailDriveParams{RetailDriveParams{spring_or_max_velocity:self.float(),damping:self.float(),max_strength:self.float(),drive_type:match self.word(){0=>RetailDriveType::NoDrive,1=>RetailDriveType::SoftDrive,2=>RetailDriveType::HardDrive,_=>panic!("drive type")}}}
 fn body(&mut self)->BodySnapshot{BodySnapshot{state_flags:self.word(),rates:RetailBodyRates{orientation:{let q=self.floats::<4>();RetailQuaternion{x:q[0],y:q[1],z:q[2],w:q[3]}},basis:Basis3{columns:std::array::from_fn(|_|self.floats())},world_inverse_inertia:Basis3{columns:std::array::from_fn(|_|self.floats())},position:self.vector(),linear_velocity:self.vector(),angular_velocity:self.vector(),force_acceleration:self.vector(),torque_acceleration:self.vector(),kinetic_energy:self.float(),cool_down:self.word()},inertia:RetailInertiaDynamics{inverse_tensor:self.vector(),inverse_mass:self.float(),spherical:self.float(),maximum_linear_velocity:self.float(),maximum_angular_velocity:self.float(),linear_drag:self.float(),angular_drag:self.float()}}}
 fn mutate(&mut self,b:&mut BodySnapshot){b.state_flags=self.word();b.rates.linear_velocity=self.vector();b.rates.angular_velocity=self.vector();b.rates.force_acceleration=self.vector();b.rates.torque_acceleration=self.vector();b.rates.kinetic_energy=self.float();b.rates.cool_down=self.word();}
}
fn constraint_params(out:&mut Vec<u32>,p:RetailDriveParams){probe_floats(out,[p.spring_or_max_velocity,p.damping,p.max_strength]);out.push(p.drive_type as u32);}
fn constraint_dynamics(out:&mut Vec<u32>,d:RetailDriveDynamics){constraint_params(out,d.linear);constraint_params(out,d.angular);}
fn constraint_bone_dynamics(out:&mut Vec<u32>,d:&BoneDriveDynamics){for c in d.channels{constraint_dynamics(out,c);}out.push(d.mode);probe_floats(out,d.strengths);out.extend([d.transition_counter.to_bits(),d.transition_active as u32]);}
fn constraint_frames(out:&mut Vec<u32>,f:RetailDriveFrames){for p in [f.body_a,f.body_b]{probe_floats(out,[p.orientation.x,p.orientation.y,p.orientation.z,p.orientation.w]);probe_vector(out,p.translation);}}
fn constraint_settings(out:&mut Vec<u32>,s:BoneDriveSettings){for a in s.animation{probe_floats(out,[a.linear_strength,a.linear_displacement,a.angular_strength,a.angular_displacement]);}probe_floats(out,[s.collision_soft_displacement,s.collision_soft_strength,s.ragdoll_soft_displacement,s.ragdoll_soft_strength]);for t in [s.transition_linear,s.transition_angular]{probe_floats(out,t.spring);probe_floats(out,t.strength);probe_floats(out,t.damping);}out.push(s.transition_calls.to_bits());}
fn constraint_drives(out:&mut Vec<u32>,d:&SkeletonDrives){for b in d.targets.bodies{probe_body(out,b);}for f in d.targets.frames{constraint_frames(out,f);}for p in d.targets.dynamics{constraint_dynamics(out,p);}for n in 0..4{probe_matrix(out,d.targets.transform(n));}for p in &d.bones{out.push(p.is_some() as u32);let Some(p)=p else{continue;};out.extend(p.parent.map(|v|v as u32));out.extend(p.active.map(|v|v as u32));for f in p.frames{constraint_frames(out,f);}constraint_bone_dynamics(out,&p.dynamics);}constraint_settings(out,d.settings.bone);out.push(d.settings.enabled as u32);probe_floats(out,d.settings.strength);for p in d.settings.collision_strength{probe_floats(out,p);}}
fn constraint_snapshot(out:&mut Vec<u32>,body:&SkeletonBody,drives:&SkeletonDrives){probe_snapshot(out,body);constraint_drives(out,drives);}
fn constraint_drive(out:&mut Vec<u32>,row:&RetailDriveRows){let p=skeleton_constraint_packing::drive(row);out.extend(p.words);out.extend([p.reaction_a as u32,p.reaction_b as u32]);}
fn main(){
 let mut bytes=Vec::new();std::io::stdin().read_to_end(&mut bytes).unwrap();assert_eq!(bytes.len()%4,0);let mut i=ProbeInput{words:bytes.chunks_exact(4).map(|b|u32::from_le_bytes(b.try_into().unwrap())).collect(),at:0};let mut out=Vec::new();let cases=i.word();
 for index in 0..cases{let op=i.word();out.extend([index,op,0]);let size_at=out.len()-1;let start=out.len();match op{
  0=>{let initial=i.matrices();let parents=i.parents();let bones=std::array::from_fn(|_|JointBone{parent_orientation:i.floats(),joint_orientation:i.floats(),volume_frame:i.matrix(),swing_limit:i.float(),twist_limit:i.float()});let settings=std::array::from_fn(|_|JointSettings{ball_joint:i.word()!=0,swing_angle:i.float(),twist_angle:i.float(),swing_ragdoll:i.float(),twist_ragdoll:i.float()});let global=SkeletonJointSettings{displacement_limit:i.floats(),twist_displacement_limit:i.float(),swing_displacement_limit:i.float(),enforce_swing_free:i.word()!=0,enforce_twist_free:i.word()!=0};match SkeletonJoints::new(&initial,&parents,&bones,&settings,global){
   Err(e)=>{out.push(0);probe_error(&mut out,e);},Ok(joints)=>{out.push(1);for r in joints.records{out.extend([r.parent as u32,r.child as u32]);out.extend(r.parameters.words);out.extend(r.frames.words);}let mut bodies=std::array::from_fn(|_|i.body());let count=i.word();out.push(count);for _ in 0..count{for b in &mut bodies{b.state_flags=i.word();}let base=i.word() as usize;let dt=i.float();let rows=joints.build(&bodies,base,dt);out.push(rows.len() as u32);for row in rows{out.extend(row.jacobian.words);out.extend([row.reaction_a as u32,row.reaction_b as u32]);}}}
  }},
  1=>{let settings=i.drive_settings();let mut d=BoneDriveDynamics{channels:std::array::from_fn(|_|RetailDriveDynamics{linear:i.params(),angular:i.params()}),mode:i.word(),strengths:i.floats(),transition_counter:i.float(),transition_active:i.word()!=0};constraint_bone_dynamics(&mut out,&d);let count=i.word();out.push(count);for _ in 0..count{d.mode=i.word();let channel=i.word() as usize;let strength=i.float();d.enable(channel,strength,settings);constraint_bone_dynamics(&mut out,&d);}},
  2=>{let child=i.matrix();let inverse_child=i.matrix();let inverse_parent=i.matrix();let mut frames=bone_drive_frames(&child,&inverse_child,&inverse_parent);constraint_frames(&mut out,frames);let count=i.word();out.push(count);for _ in 0..count{frames=prepare_bone_drive_frames(frames);constraint_frames(&mut out,frames);}},
  3=>{let definition=i.definition().unwrap();let authored=i.matrices();let spawn=i.matrix();let simulation=i.simulation();let mut body=SkeletonBody::new(definition,&authored,spawn,simulation);let initial=i.matrices();let mapped=i.matrices();let parents=i.parents();let alignment=i.matrix();let settings=SkeletonDriveSettings{bone:i.drive_settings(),enabled:i.word()!=0,strength:i.floats(),collision_strength:std::array::from_fn(|_|i.floats())};match SkeletonDrives::new(&initial,&mapped,&parents,alignment,spawn,simulation,settings){
   Err(e)=>{out.push(0);probe_error(&mut out,e);},Ok(mut drives)=>{out.push(1);constraint_snapshot(&mut out,&body,&drives);let count=i.word();out.push(count);for _ in 0..count{let cmd=i.word();out.push(cmd);match cmd{
    0=>{let partial=i.word()!=0;let weight=i.float();let pose=i.matrices();drives.update(&pose,partial,weight);},
    1=>{let part=i.word() as usize;let channel=i.word() as usize;drives.bones[part].as_mut().unwrap().active[channel]=i.word()!=0;},
    2=>{drives.settings.enabled=i.word()!=0;drives.settings.strength=i.floats();},
    3=>{let target=i.word() as usize;drives.targets.set_transform(target,i.matrix());},
    4=>{let hips=i.matrix();let root=i.matrix();drives.targets.reset(hips,root);},
    5=>drives.targets.apply_future_deck_displacement(i.vector()),
    6=>{let frames=i.matrices::<7>();let teleporting=i.word()!=0;let input=SkeletonTargetInput{animation_hips:&frames[0],animation_board:&frames[1],animation_to_world:&frames[2],inverse_board:&frames[3],skate_root:&frames[4],com_frame:&frames[5],lifted_com_frame:&frames[6],teleporting};let update=drives.targets.update_positions(input,&mut body);probe_matrix(&mut out,update.animation_board_to_physics);for p in [update.positions.com,update.positions.lifted_com,update.positions.following_com]{probe_floats(&mut out,p);}out.push(update.continuous as u32);},
    7=>{let base=i.word() as usize;let target_base=i.word() as usize;let dt=i.float();let batch=drives.build(body.bodies(),base,target_base,dt);out.push(batch.rows.len() as u32);for n in 0..batch.rows.len(){constraint_drive(&mut out,&batch.rows[n]);match batch.identities[n]{SkeletonDriveIdentity::Target(target)=>out.extend([0,target as u32,0]),SkeletonDriveIdentity::Bone{part,channel}=>out.extend([1,part as u32,channel as u32])};out.push(batch.spy[n] as u32);}},
    8=>{let part=i.word() as usize;i.mutate(&mut body.bodies_mut()[part]);},9=>{let target=i.word() as usize;i.mutate(&mut drives.targets.bodies[target]);},10=>{let part=i.word() as usize;drives.bones[part]=None;},_=>panic!("constraint command")
   }constraint_snapshot(&mut out,&body,&drives);}}
  }},_=>panic!("constraint operation")
 }out[size_at]=(out.len()-start) as u32;}
 assert_eq!(i.at,i.words.len());let mut stdout=std::io::BufWriter::new(std::io::stdout().lock());for w in out{stdout.write_all(&w.to_le_bytes()).unwrap();}
}
