// Full original skeleton input owners; the checker supplies frozen host source.
use skate_core::{player::input_phase::*,animation::{output::{actor_packet::ExternalPhysicsInput,attributes::{AttributeName,AnimationAttribute,AttributePayload}},skeleton_input::{scalar_attributes::{ScalarAttributeInputs,AnimationControlOutput},extended_attributes::ExtendedAttributes,attribute_finalization::{JumpAttributeState,FinalizationInput},contact_events::ContactEventState}},input::animation_packet::AnimationPacketFields};
mod difficulty{pub const NATIVE_MODES:[&str;5]=["easy","normal","hardcore","motorized","test"];}
struct Input<'a>{p:&'a mut ProbeInput}
impl Input<'_>{fn word(&mut self)->u32{self.p.word()}fn wide(&mut self)->u64{let lo=self.word();u64::from(lo)|(u64::from(self.word())<<32)}fn float(&mut self)->f32{self.p.float()}fn words<const N:usize>(&mut self)->[u32;N]{std::array::from_fn(|_|self.word())}fn floats<const N:usize>(&mut self)->[f32;N]{self.p.floats()}fn attribute(&mut self)->AnimationAttribute{AnimationAttribute{name:AttributeName(self.words()),kind:self.word()as u8,status:self.word()as u8,sequence_id:self.word()as i32,begin_time:self.float(),end_time:self.float(),payload:AttributePayload(std::array::from_fn(|_|(self.word()!=0).then(||self.word())))}}}
struct Output(Vec<u32>);
impl Output{fn word(&mut self,v:u32){self.0.push(v)}fn wide(&mut self,v:u64){self.word(v as u32);self.word((v>>32)as u32)}fn float(&mut self,v:f32){self.word(v.to_bits())}fn words<const N:usize>(&mut self,v:[u32;N]){self.0.extend(v)}fn floats<const N:usize>(&mut self,v:[f32;N]){self.0.extend(v.map(f32::to_bits))}}
// GENERATED_PROTOCOL
#[derive(Default)]struct Actions{values:[f32;18],calls:Vec<u32>}
impl skate_core::input::controller::ActionMap for Actions{fn value(&mut self,a:u32)->f32{self.calls.push(a);self.values[(a-64)as usize]}fn state(&mut self,a:u32)->u8{(self.value(a)!=0.)as u8}}
fn observe_dispatcher(out:&mut Vec<u32>,s:&physics::SkeletonInput,input:&physics::animation_input::AnimationInput,wobble:&skate_core::physics::skeleton_output::wobble::Wobble,elapsed:bool,p:&ProcessedPhysicsInput,actions:&Actions){out.extend([s.reenable_requested as u32,s.teleporting as u32,s.force_mode]);for v in s.head_tracking_history{probe_floats(out,v);}out.extend([s.head_tracking_active as u32,s.grind_air_started as u32,s.grind_air_active as u32,s.grind_air_adjusting as u32]);adjusted_grind(out,&s.grind_air);out.extend([wobble.active as u32,wobble.landing as u32]);probe_floats(out,[wobble.time,wobble.amplitude,wobble.direction]);out.push(elapsed as u32);let mut row=Output(Vec::new());physics::animation_input::observe(&mut row,input);row.word(actions.calls.len()as u32);row.0.extend(&actions.calls);observe_ProcessedPhysicsInput(&mut row,p);out.extend(row.0);}
fn wobble_settings(data:&skate_data::collections::Collections)->skate_core::physics::skeleton_output::wobble::Settings{let graph=|name|{let words=data.words::<20>("physics_deck_wobble","default",name).unwrap().map(f32::from_bits);skate_core::point_graph::PointGraph{x:words[4..12].try_into().unwrap(),y:words[12..20].try_into().unwrap()}};skate_core::physics::skeleton_output::wobble::Settings{takeoff_tilt:graph("TiltVsTimeTakeOff"),landing_tilt:graph("TiltVsTimeLanding"),takeoff_squish:graph("SquishVsTimeTakeOff"),landing_squish:graph("SquishVsTimeLanding"),maximum_time:data.float("physics_deck_wobble","default","MaxTime").unwrap()}}
fn dispatcher_collision(s:&SkaterRuntime)->physics::skeleton_input_runtime::CollisionInput{physics::skeleton_input_runtime::CollisionInput{contact_4070:s.collision_feedback.flags.compliant,has_pose_error_4077:s.collision_feedback.flags.has_impulse,pose_error_16272:s.collision_pose_error,partial_ragdoll:s.skeleton_collision.partial_ragdoll,drive_weight_4028:s.collision_feedback.drive_weight}}
fn process_dispatcher(i:&mut ProbeInput,out:&mut Vec<u32>,p:&mut GamePhysics,s:&mut SkaterRuntime,e:&animation_pose::PoseEvaluator,ik:&mut physics::foot_ik::FootIk,input:&mut physics::animation_input::AnimationInput,wobble:&mut skate_core::physics::skeleton_output::wobble::Wobble,ws:&skate_core::physics::skeleton_output::wobble::Settings,queries:&mut PlayerInputState,actions:&mut Actions)->bool{
 let mut adapter=Input{p:i};let pose=adapter.word();let dt=adapter.float();let processed=&mut s.player_input.processed;processed.timestep_2604=dt;processed.state_2508=adapter.word();processed.category_2512=adapter.word();processed.filtered_state_2524=adapter.word();processed.flags_2468=adapter.word();processed.flags_2472=adapter.word();processed.flags_2476=adapter.word();processed.flags_2480=adapter.word();processed.flags_2484=adapter.word();processed.flags_2488=adapter.word();let animation_flags=adapter.word();let impulse=adapter.word()!=0;let n=adapter.word();let attributes=(0..n).map(|_|adapter.attribute()).collect::<Vec<_>>();actions.values=adapter.floats();let branch=adapter.word();let solve=adapter.word()!=0;actions.calls.clear();processed.gravity_2648=9.81;processed.line_tests_960_1008_1056=[queries.left_line_test_1536,queries.right_line_test_1584,queries.hips_line_test_1488];processed.vectors_400_416[0]=four(p.board.bodies()[6].rates.linear_velocity).map(f32::to_bits);processed.vectors_720_784_800_816_832_864[0]=four(p.board.bodies()[6].rates.angular_velocity).map(f32::to_bits);processed.vectors_544_560_592_608[0]=four(p.riding.ground.overall_normal).map(f32::to_bits);processed.vectors_544_560_592_608[3]=s.skeleton.record.centre_of_mass_velocity.map(f32::to_bits);processed.off_board_scalar_2832=0.1;
 let collision=dispatcher_collision(s);p.board.clear_forces();if let Err(error)=p.riding.start_wheel_queries(&p.board,&p.world){adjusted_error_out(out,Err(error));return false;}let lines=physics::foot_ik_queries::query(&p.world,&s.skeleton).unwrap();let globals=if pose==4{Vec::new()}else{adjusted_hierarchy(e,pose)};// Use the unchanged production PrepareBoardToolkit owner. A raw solve frame
 // has translation.W=0; from_board deliberately publishes translation.W=1.
 let toolkit=skate_core::physics::board_toolkit::BoardToolkit::from_board(&p.board,s.player_input.processed.flags_2468,p.riding.motion.speed,four(p.riding.ground.overall_normal),four(p.riding.reckoning.ground_normal));
 let publication=AnimationPacketFields{stance_byte:0,timestep:dt,scalar_10388:0.,flags_10375_10496_10784:[0,impulse as u8,0],vector_10480:[0;4],matrix_10704:[[0;4];4],byte_10768:0,truck_tightness:0.,scalar_10792:0.,flag_10371:0};let external=ExternalPhysicsInput{vectors:[[0;4];10],flags:0};let packet=AnimationInputPacket{publication:&publication,external_physics_10512:&external,flag_10369:0,flag_10370:0,flag_10373:0,suppress_transition_10376:0,use_external_physics_10688:0,external_physics_flag_10689:0,flag_10786:0,flag_10787:0,force_braking_10796:0,vector_10816:[0;4],vector_10832:[0;4],vector_10848:[0;4],vector_10864:[0;4],vector_10880:[0;4],vector_10896:[0;4],scalar_10912:0.,scalar_10916:0.,state_variant_10928:0,flags_10932:animation_flags};let mut physical=PhysicalPlayerInput::default();
 let result={let mut owners=physics::skeleton_input_runtime::SkeletonOwners{animated:&mut s.animated_skeleton,body:&mut s.skeleton,drives:&mut s.skeleton_drives,ik,animation_input:input,correction:&mut s.skeleton_output.correction,pose_errors:&mut s.pose_errors};s.skeleton_input.process_data(&mut p.board,&toolkit,&packet,&mut physical,&mut s.player_input.processed,&mut owners,physics::skeleton_input_runtime::SkeletonPoseInput{globals:&globals,attributes:&attributes,actions},&collision)};
 if let Err(error)=result{adjusted_error_out(out,Err(error));let _=p.riding.finish_wheel_queries();lines.publish(queries);return false;}if let Err(error)=p.riding.finish_wheel_queries(){adjusted_error_out(out,Err(error));return false;}let wheel=p.riding.ground.wheel_normal;let dynamic_up=p.riding.ground.overall_normal;p.processed_flags_2468=s.player_input.processed.flags_2468;
 if branch!=3{
  let saved=s.player_input.processed;let processed=&mut s.player_input.processed;processed.wheel_count_2556=p.riding.ground.wheel_contact_count as u32;processed.scalar_2652=p.riding.motion.speed;processed.scalar_2616=p.riding.motion.ground_speed;processed.vectors_464_480_496_512_528[0]=four(wheel).map(f32::to_bits);p.riding.update_ground_reckoning(&p.board,physics::riding_outputs::RidingPoseInputs{com_to_deck:s.animated_skeleton.record.com_to_deck(),body_spin:input.fields.spin},processed.flags_2468,input.fields.balance,false,processed);
  // Current wheel/speed inputs are a call transport, not new ProcessData writes.
  s.player_input.processed=saved;
  let a=&mut s.animated_skeleton;a.board_frames.update_com_lift(&a.roots.animation_to_world,a.animation_hips[3],0.02);let mut frame=IDENTITY;
  let result={let mut owners=physics::skeleton_input_runtime::SkeletonOwners{animated:&mut s.animated_skeleton,body:&mut s.skeleton,drives:&mut s.skeleton_drives,ik,animation_input:input,correction:&mut s.skeleton_output.correction,pose_errors:&mut s.pose_errors};match branch{0=>s.skeleton_input.general_update(&s.player_input.processed,&mut owners,&globals,&collision,p.settings.step.simulation).map(|_|()),1=>s.skeleton_input.update_ground(&p.board,&p.riding.reckoning_frames.system,&mut s.player_input.processed,&mut owners,&globals,&collision,p.settings.step.simulation).map(|v|frame=v),2=>s.skeleton_input.update_teleport(&p.board,&p.riding.reckoning_frames.system,&mut s.player_input.processed,&mut owners,&globals,&collision,p.settings.step.simulation).map(|v|frame=v),_=>panic!("branch")}};probe_matrix(out,frame);if let Err(error)=result{adjusted_error_out(out,Err(error));lines.publish(queries);return false;}
 }
 lines.publish(queries);p.processed_flags_2468=s.player_input.processed.flags_2468;
 if solve{
  if let Err(error)=physics::advance(p,s,[0.;2]){adjusted_error_out(out,Err(error));return false;}out.push(p.contact_count as u32);out.push(s.solved_drives.as_ref().map_or(0,|b|b.rows.len())as u32);let saved=s.player_input.processed;let processed=&mut s.player_input.processed;processed.vectors_464_480_496_512_528[0]=four(wheel).map(f32::to_bits);processed.vectors_544_560_592_608[0]=s.animated_skeleton.roots.animation_to_world[1].map(f32::to_bits);processed.time_on_ground_2752=p.ticks as f32*dt;p.riding.probes.prepare_wall(processed,&toolkit);p.riding.finish_post_physics(&mut p.board,p.board_wiping_out,p.processed_flags_2468,p.settings.step.simulation.time_step).unwrap();let processed=&mut s.player_input.processed;processed.vectors_464_480_496_512_528[1]=four(p.riding.ground.parts[6].point).map(f32::to_bits);processed.vectors_464_480_496_512_528[2]=processed.vectors_464_480_496_512_528[1];processed.vectors_464_480_496_512_528[4]=four(dynamic_up).map(f32::to_bits);processed.vectors_880_896_912_928_944[0]=s.animated_skeleton.animation_hips[3].map(f32::to_bits);processed.vectors_880_896_912_928_944[1]=[0.,1.,0.,0.].map(f32::to_bits);physics::publish(p,s);s.player_input.processed=saved;
  let mut observed=physics::deck_frame(&p.board);let sampled=wobble.update(ws);skate_core::physics::skeleton_output::wobble::apply(sampled,&mut observed);out.push(sampled.sampled as u32);probe_floats(out,[sampled.tilt,sampled.squish]);out.push(sampled.remains_active as u32);probe_matrix(out,observed);let processed=&s.player_input.processed;let inverse=s.animated_skeleton.roots.world_to_animation;let post=ik.post_physics(&mut s.skeleton,core_ik::post_physics::Input{state_id:processed.state_2508,category_id:processed.category_2512,board_body_flag_868:p.riding.ground.part_contact_count!=0,wipeout:false,flags_2468:processed.flags_2468,flags_2484:processed.flags_2484,value_2664:processed.state_timer_2664,state_2520:processed.player_state_value_2520,world_to_animation:&inverse,board:&observed});out.extend(post.map(u32::from));s.skeleton.publish_physical_record(physics::deck_frame(&p.board));p.ticks+=1;
 }
 adjusted_error_out(out,Ok(()));true
}
fn main(){
 let args=std::env::args().collect::<Vec<_>>();let assets=std::path::Path::new(&args[1]);let data=skate_data::collections::Collections::load(assets).unwrap();let e=animation_pose::PoseEvaluator::from_banks(&skate_data::animation_banks::AnimationBanks::load(assets).unwrap()).unwrap();let stock=physics::settings::PhysicsSettings::load(&data).unwrap();let ws=wobble_settings(&data);let mut bytes=Vec::new();std::io::stdin().read_to_end(&mut bytes).unwrap();let mut i=ProbeInput{words:bytes.chunks_exact(4).map(|b|u32::from_le_bytes(b.try_into().unwrap())).collect(),at:0};let mut out=Vec::new();let cases=i.word();
 for c in 0..cases{let spawn=i.affine();let world=i.world(stock.floor_material);let seams=i.word()!=0;let(mut p,mut s)=make(&data,assets,&e,spawn,world);if seams{p.world.enable_imported_floor_seams();}let mut ik=physics::foot_ik::FootIk::load(&data,&e.frames,&s.animated_skeleton).unwrap();let mut input=physics::animation_input::AnimationInput::load(&data,&e.frames,"normal").unwrap();let mut wobble=skate_core::physics::skeleton_output::wobble::Wobble::default();let mut elapsed=false;let mut queries=PlayerInputState::default();let mut actions=Actions::default();let n=i.word();out.extend([c,n,0]);let mark=out.len()-1;let initial=out.len();out.push(0);snapshot(&mut out,&mut p,&mut s);adjusted_out(&mut out,&s.animated_skeleton,&ik,&s.skeleton_input.grind_air,&queries);observe_dispatcher(&mut out,&s.skeleton_input,&input,&wobble,elapsed,&s.player_input.processed,&actions);out[initial]=(out.len()-initial-1)as u32;
 for _ in 0..n{let op=i.word();out.extend([op,0]);let at=out.len()-1;let owner_mark=out.len();out.push(0);match op{
 0=>{let status=out.len();out.push(0);let ok=process_dispatcher(&mut i,&mut out,&mut p,&mut s,&e,&mut ik,&mut input,&mut wobble,&ws,&mut queries,&mut actions);out[status]=ok as u32;},1=>{let mut owners=physics::skeleton_input_runtime::SkeletonOwners{animated:&mut s.animated_skeleton,body:&mut s.skeleton,drives:&mut s.skeleton_drives,ik:&mut ik,animation_input:&mut input,correction:&mut s.skeleton_output.correction,pose_errors:&mut s.pose_errors};s.skeleton_input.reset_for_teleport(&mut owners,&mut s.skeleton_collision,&mut s.collision_feedback,&mut wobble,&mut elapsed);},2=>{let landing=i.word()!=0;let reverse=i.word()!=0;wobble.trigger(landing,reverse);},3=>{let owner=&mut s.skeleton_input;owner.reenable_requested=i.word()!=0;owner.force_mode=i.word();owner.head_tracking_active=i.word()!=0;owner.grind_air_started=i.word()!=0;owner.grind_air_active=i.word()!=0;owner.head_tracking_history=std::array::from_fn(|_|i.floats());},4=>{let limb=i.word()as usize;let mode=i.word();let v:[f32;8]=i.floats();let l=&mut ik.state.limbs[limb];let t=&mut ik.state.external_targets[limb];l.target_blend=v[0];l.external_target_set=mode==1;l.local_target_set=mode==2;t.world_position=[v[1],v[2],v[3],0.];t.animation_position=t.world_position;t.normal=[v[4],v[5],v[6],v[7]];t.normal_set=true;t.normal_blend=0.6;},
 5=>{use skate_core::air::trajectory::grind_surface::{LandingOrientation,GeometryType};let start=i.floats();let end=i.floats();let owner=u64::from(i.word());let primitive_flags=i.word();let kind=match i.word(){0=>GeometryType::ThinRail,1=>GeometryType::FatRail,2=>GeometryType::Ledge,3=>GeometryType::Impossible,_=>panic!("kind")};let garbage=i.word()!=0;let orientation=LandingOrientation{kind,garbage,boardslide_dir:i.floats(),tipslide_dir:i.floats(),backslash_dir:i.floats(),high_side:i.floats()};s.skeleton_input.grind_air.start(grind_air::Target{edge:skate_core::physics::grind_contact::Primitive{start,end,owner},primitive_flags,orientation});},6=>p.world=i.world(p.settings.floor_material),7=>input.finish_output_publication(),8=>adjusted_error_out(&mut out,input.select_physics_mode(i.word())),9=>{let flags=i.word();let cool_down=i.word();for body in s.skeleton.bodies_mut(){body.state_flags=flags;body.rates.cool_down=cool_down;}},_=>panic!("dispatcher operation")};out[owner_mark]=(out.len()-owner_mark-1)as u32;snapshot(&mut out,&mut p,&mut s);adjusted_out(&mut out,&s.animated_skeleton,&ik,&s.skeleton_input.grind_air,&queries);observe_dispatcher(&mut out,&s.skeleton_input,&input,&wobble,elapsed,&s.player_input.processed,&actions);out[at]=(out.len()-at-1)as u32;}out[mark]=(out.len()-mark-1)as u32;}
 assert_eq!(i.at,i.words.len());let mut stdout=std::io::BufWriter::new(std::io::stdout().lock());for word in out{stdout.write_all(&word.to_le_bytes()).unwrap();}
}
