// The checker prepends the skeleton-body probe's public record adapters.
use crate::physics::contact::RetailContactMaterial;
impl ProbeInput{
 fn material(&mut self)->RetailContactMaterial{RetailContactMaterial{static_friction:self.float(),dynamic_friction:self.float(),restitution:self.float()}}
 fn collision_settings(&mut self)->SkeletonCollisionSettings{SkeletonCollisionSettings{enabled:self.word()!=0,normal_material:self.material(),compliant:std::array::from_fn(|_|self.word()!=0),priority:self.floats(),effect_time:self.float()}}
 fn feedback_settings(&mut self)->SkeletonFeedbackSettings{SkeletonFeedbackSettings{body:self.collision_settings(),small_object_mass:self.float(),ground_plane_max_distance:self.float(),ground_plane_max_angle:self.float(),skater_scalar:self.float(),ai_scalar:self.float(),groin_offset:self.floats(),face_offset:self.floats(),groin_radius:self.float(),face_radius:self.float()}}
 fn flags(&mut self)->SkeletonContactFlags{SkeletonContactFlags{material_6:self.word()!=0,noncompliant:self.word()!=0,compliant:self.word()!=0,recovering:self.word()!=0,group_8:self.word()!=0,nonboard:self.word()!=0,ragdoll:self.word()!=0,conflicting:self.word()!=0,impaled:self.word()!=0,has_impulse:self.word()!=0,foot_board:self.word()!=0,material_10:self.word()!=0,material_11:self.word()!=0,material_12:self.word()!=0,any:self.word()!=0}}
 fn specific(&mut self)->SpecificContact{SpecificContact{part:self.word() as usize,local_point:self.floats(),world_point:self.floats(),radius_squared:self.float(),current:self.word()!=0,recent:self.word()!=0}}
 fn seed_feedback(&mut self,a:&mut SkeletonCollisionFeedback){if self.word()==0{return;}a.contact_age=self.floats();a.priority=self.floats();a.compliant=std::array::from_fn(|_|self.word()!=0);a.current=std::array::from_fn(|_|self.word()!=0);a.bones=std::array::from_fn(|_|BoneContact{normal:self.floats(),specific_normal:self.floats(),tangent:self.floats(),specific_tangent:self.floats(),point:self.floats(),force:self.float(),specific_force:self.float(),tag:self.word(),specific_tag:self.word(),groups:std::array::from_fn(|_|self.word()!=0)});a.regions=std::array::from_fn(|_|{let force=self.float();let weighted_force=self.float();let tangent_speed=self.float();let material_flags=self.word();let normal=self.floats();let part=self.word();ContactRegion{force,weighted_force,tangent_speed,material_flags,normal,part:if part==u32::MAX{None}else{Some(part as usize)}}});let n=self.word();a.planes=(0..n).map(|_|ContactPlane{normal:self.floats(),part:self.word() as usize}).collect();a.specific=std::array::from_fn(|_|self.specific());a.highest_normal=self.floats();a.foot_normal=self.floats();a.material_normals=std::array::from_fn(|_|self.floats());a.timer=self.float();a.drive_weight=self.float();a.maximum_priority=self.float();a.wipeout_times=self.floats();a.maximum_skater_force=self.float();a.other_skater=self.word() as i32;a.maximum_group_8_force=self.float();a.maximum_group_11_force=self.float();a.material_12_height=self.float();a.flags=self.flags();}
 fn contact_body(&mut self)->SkeletonContactBody{SkeletonContactBody{state_flags:self.word(),inverse_mass:self.float(),linear_velocity:self.floats()}}
 fn report(&mut self)->SkeletonContactReport{let part=self.word() as usize;let normal=self.floats();let point=self.floats();let tag=self.word();let other_group=self.word();let has_entity=self.word()!=0;let entity=self.word() as i32;SkeletonContactReport{part,normal,point,tag,other_group,other_entity:has_entity.then_some(entity),body_a:self.contact_body(),body_b:self.contact_body(),side_a:self.word()!=0,solved_vector:self.floats()}}
 fn update_feedback(&mut self,a:&mut SkeletonCollisionFeedback){let dt=self.float();let plane_point=self.floats();let plane_normal=self.floats();let reference_velocity=self.floats();let com_velocity=self.floats();let ragdoll=self.word()!=0;let disable_ground_filter=self.word()!=0;let ai_collision_scalar=self.word()!=0;let offboard=self.word()!=0;let entering_offboard=self.word()!=0;let category_600=self.word()!=0;let request_partial_ragdoll=self.word()!=0;let physical=self.physical_record();let part_weights=self.floats();let body_frames=self.matrices();let n=self.word();let reports=(0..n).map(|_|self.report()).collect::<Vec<_>>();let input=SkeletonCollisionInput{dt,plane_point,plane_normal,reference_velocity,com_velocity,ragdoll,disable_ground_filter,ai_collision_scalar,offboard,entering_offboard,category_600,request_partial_ragdoll,physical:&physical,part_weights:&part_weights,body_frames:&body_frames};a.update(&input,&reports);}
 fn errors(&mut self)->SkeletonPoseErrors{SkeletonPoseErrors{parts:std::array::from_fn(|_|self.floats()),extra:std::array::from_fn(|_|self.floats()),targets:std::array::from_fn(|_|self.floats())}}
}
fn collision_settings_out(out:&mut Vec<u32>,s:SkeletonCollisionSettings){out.push(s.enabled as u32);probe_floats(out,[s.normal_material.static_friction,s.normal_material.dynamic_friction,s.normal_material.restitution]);out.extend(s.compliant.map(|v|v as u32));probe_floats(out,s.priority);out.push(s.effect_time.to_bits());}
fn collision_flags(out:&mut Vec<u32>,f:SkeletonContactFlags){out.extend([f.material_6,f.noncompliant,f.compliant,f.recovering,f.group_8,f.nonboard,f.ragdoll,f.conflicting,f.impaled,f.has_impulse,f.foot_board,f.material_10,f.material_11,f.material_12,f.any].map(|v|v as u32));}
fn collision_feedback(out:&mut Vec<u32>,a:&SkeletonCollisionFeedback){probe_floats(out,a.contact_age);probe_floats(out,a.priority);out.extend(a.compliant.map(|v|v as u32));out.extend(a.current.map(|v|v as u32));for b in a.bones{for v in [b.normal,b.specific_normal,b.tangent,b.specific_tangent,b.point]{probe_floats(out,v);}probe_floats(out,[b.force,b.specific_force]);out.extend([b.tag,b.specific_tag]);out.extend(b.groups.map(|v|v as u32));}for r in a.regions{probe_floats(out,[r.force,r.weighted_force,r.tangent_speed]);out.push(r.material_flags);probe_floats(out,r.normal);out.push(r.part.map(|v|v as u32).unwrap_or(u32::MAX));}out.push(a.planes.len() as u32);for p in &a.planes{probe_floats(out,p.normal);out.push(p.part as u32);}for p in a.specific{out.push(p.part as u32);probe_floats(out,p.local_point);probe_floats(out,p.world_point);out.extend([p.radius_squared.to_bits(),p.current as u32,p.recent as u32]);}probe_floats(out,a.highest_normal);probe_floats(out,a.foot_normal);for p in a.material_normals{probe_floats(out,p);}probe_floats(out,[a.timer,a.drive_weight,a.maximum_priority]);probe_floats(out,a.wipeout_times);out.extend([a.maximum_skater_force.to_bits(),a.other_skater as u32,a.maximum_group_8_force.to_bits(),a.maximum_group_11_force.to_bits(),a.material_12_height.to_bits()]);collision_flags(out,a.flags);}
fn collision_errors(out:&mut Vec<u32>,e:&SkeletonPoseErrors){for v in e.parts.into_iter().chain(e.extra).chain(e.targets){probe_floats(out,v);}}
fn collision_response_out(out:&mut Vec<u32>,e:SkeletonNormalError){probe_floats(out,e.impulse);for v in e.extra{probe_floats(out,v);}out.push(e.maximum_error.to_bits());}
fn collision_mode(out:&mut Vec<u32>,m:&SkeletonCollisionMode){for p in m.parts{out.extend([p.enabled as u32,p.volume_group,p.part_group]);probe_floats(out,[p.material.static_friction,p.material.dynamic_friction,p.material.restitution]);}out.extend(m.disable_count);out.extend([m.pending_reenable as u32,m.assembly_group,m.partial_ragdoll as u32,m.is_ragdoll as u32]);for row in m.self_culling{out.extend(row.map(|v|v as u32));}collision_settings_out(out,m.settings);}
fn collision_policy(out:&mut Vec<u32>,body:&SkeletonBody,mode:&SkeletonCollisionMode,feedback:&SkeletonCollisionFeedback){probe_snapshot(out,body);collision_mode(out,mode);collision_feedback(out,feedback);}
fn main(){
 let mut bytes=Vec::new();std::io::stdin().read_to_end(&mut bytes).unwrap();assert_eq!(bytes.len()%4,0);let mut i=ProbeInput{words:bytes.chunks_exact(4).map(|b|u32::from_le_bytes(b.try_into().unwrap())).collect(),at:0};let mut out=Vec::new();let cases=i.word();
 for index in 0..cases{let op=i.word();out.extend([index,op,0]);let size_at=out.len()-1;let start=out.len();match op{
  0=>{let a=i.vector();let b=i.vector();out.push(crate::physics::board_ground::angle_between(a,b).to_bits());},
  1=>{let mut feedback=SkeletonCollisionFeedback::new(i.feedback_settings());i.seed_feedback(&mut feedback);let errors=i.errors();let error=i.floats();let axis=i.floats();probe_floats(&mut out,feedback.filter_error(error,axis));collision_response_out(&mut out,errors.normal_response(&feedback,axis));collision_response_out(&mut out,errors.partial_response());collision_feedback(&mut out,&feedback);},
  2=>{let mut feedback=SkeletonCollisionFeedback::new(i.feedback_settings());i.seed_feedback(&mut feedback);let mut errors=i.errors();collision_feedback(&mut out,&feedback);collision_errors(&mut out,&errors);let n=i.word();out.push(n);for _ in 0..n{let cmd=i.word();out.push(cmd);match cmd{
   0=>feedback.reset(),1=>feedback.set_up_normal(),2=>i.update_feedback(&mut feedback),3=>{let error=i.floats();let axis=i.floats();probe_floats(&mut out,feedback.filter_error(error,axis));},
   4=>{feedback.contact_age=i.floats();feedback.priority=i.floats();feedback.compliant=std::array::from_fn(|_|i.word()!=0);},5=>feedback.specific=std::array::from_fn(|_|i.specific()),6=>feedback.flags.any=i.word()!=0,
   7=>errors.reset_history(),8=>errors.set_targets(ExtraTargetPositions{com:i.floats(),lifted_com:i.floats(),following_com:i.floats()}),9=>{let physical=i.physical_record();let alignment=i.matrix();let frames=i.matrices();errors.update(&physical,alignment,&frames);},10=>{let axis=i.floats();collision_response_out(&mut out,errors.normal_response(&feedback,axis));collision_response_out(&mut out,errors.partial_response());},_=>panic!("feedback command")
  }collision_feedback(&mut out,&feedback);collision_errors(&mut out,&errors);}},
  3=>{let definition=i.definition().unwrap();let authored=i.matrices();let spawn=i.matrix();let simulation=i.simulation();let mut body=SkeletonBody::new(definition,&authored,spawn,simulation);let settings=i.collision_settings();let all=i.word()!=0;let mut mode=SkeletonCollisionMode::new_normal(settings,all);let mut feedback=SkeletonCollisionFeedback::new(i.feedback_settings());i.seed_feedback(&mut feedback);collision_policy(&mut out,&body,&mode,&feedback);let n=i.word();out.push(n);for _ in 0..n{let cmd=i.word();out.push(cmd);match cmd{
   0=>mode.disable_handplant_contacts(i.word()),1=>mode.finish_contact_frame(),2=>{let part=i.word() as usize;mode.normal_bone(part,i.word()!=0);},3=>mode.enable_bone(i.word() as usize),4=>mode.normal_collision(),5=>mode.disable_all(i.word()!=0),
   6=>match mode.select_driven(i.word()){Ok(())=>out.push(1),Err(e)=>{out.push(0);probe_error(&mut out,e);}},
   7=>{let mass=i.word()!=0;let inertia=i.word()!=0;let drag=i.floats();let materials=std::array::from_fn(|_|i.material());mode.apply_ragdoll_properties(&mut body,mass,inertia,drag,materials);},8=>mode.finish_ragdoll_request(i.word()),9=>mode.restore_normal_properties(&mut body),10=>mode.reset_body_state(&mut feedback),
   11=>{let part=i.word() as usize;mode.disable_count[part]=i.word();mode.pending_reenable=i.word()!=0;mode.parts[part].enabled=i.word()!=0;mode.parts[part].volume_group=i.word();mode.parts[part].part_group=i.word();mode.parts[part].material=i.material();},12=>mode.settings.enabled=i.word()!=0,13=>i.update_feedback(&mut feedback),
   14=>{let part=i.word() as usize;let b=&mut body.bodies_mut()[part];b.state_flags=i.word();b.rates.linear_velocity=i.vector();b.rates.angular_velocity=i.vector();b.rates.force_acceleration=i.vector();b.rates.torque_acceleration=i.vector();b.rates.kinetic_energy=i.float();b.rates.cool_down=i.word();},_=>panic!("policy command")
  }collision_policy(&mut out,&body,&mode,&feedback);}},_=>panic!("collision operation")
 }out[size_at]=(out.len()-start) as u32;}
 assert_eq!(i.at,i.words.len());let mut stdout=std::io::BufWriter::new(std::io::stdout().lock());for w in out{stdout.write_all(&w.to_le_bytes()).unwrap();}
}
