// Generated by items/skateboard/ollie.py. Rebuild with run.sh skateboard.
#pragma once
namespace SkateOllieMotion {
struct FKey { float Time, Value; };
template <size_t N> float Sample(const FKey (&Keys)[N],float T) {
  if (T <= Keys[0].Time) return Keys[0].Value;
  for (size_t I=1; I<N; ++I) if (T <= Keys[I].Time) {
    const float U=(T-Keys[I-1].Time)/(Keys[I].Time-Keys[I-1].Time);
    return FMath::Lerp(Keys[I-1].Value,Keys[I].Value,U*U*U*(10.f+U*(-15.f+6.f*U)));
  }
  return Keys[N-1].Value;
}
constexpr float StartDuration = 0.4f;
constexpr FKey StartPitch[] = {{0.0f,0.0f},{0.32f,0.0f},{0.4f,10.0f}};
constexpr FKey StartHeight[] = {{0.0f,0.0f},{0.32f,0.0f},{0.4f,4.5600000000000005f}};
constexpr float AirDuration = 0.7f;
constexpr FKey AirPitch[] = {{0.0f,10.0f},{0.08f,24.0f},{0.24f,0.0f},{0.7f,0.0f}};
constexpr FKey AirHeight[] = {{0.0f,4.5600000000000005f},{0.08f,11.5f},{0.25f,7.5f},{0.49f,0.0f},{0.7f,0.0f}};
constexpr float LandDuration = 0.36f;
constexpr FKey LandPitch[] = {{0.0f,0.0f},{0.36f,0.0f}};
constexpr FKey LandHeight[] = {{0.0f,0.0f},{0.36f,0.0f}};
}
