// Generates src/api/schema.ts from the server's API contract (platform/web/board/api/board-api.schema.json), so the
// app's types are the server's own. `npm run types`; a test checks the committed file is current.
import {readFile, writeFile} from 'node:fs/promises';
import {compile} from 'json-schema-to-typescript';

const schema = JSON.parse(await readFile(new URL('../api/board-api.schema.json', import.meta.url), 'utf8'));
const out = await compile(schema, 'Contract', {
  bannerComment: '// Generated by gen-types.mjs from platform/web/board/api/board-api.schema.json. Do not edit.',
  additionalProperties: false,
  unreachableDefinitions: true,
  strictIndexSignatures: true,
  format: false,
});
const target = new URL('src/api/schema.ts', import.meta.url);
if (process.argv.includes('--check')) {
  const current = await readFile(target, 'utf8').catch(() => '');
  if (current !== out) { console.error('src/api/schema.ts is out of date: run npm run types'); process.exit(1); }
} else await writeFile(target, out);
