#include "GrindForces.h"
#include <cmath>
#include <cstring>
#if defined(__clang__)
#pragma clang fp contract(off)
#endif
namespace atelier::skate
{
namespace
{
float Word(std::uint32_t w){float f;std::memcpy(&f,&w,4);return f;}
Vec4 Scale(Vec4 v,float f){for(auto& x:v)x*=f;return v;}
Vec4 Sub(Vec4 a,Vec4 b){for(unsigned n=0;n<4;++n)a[n]-=b[n];return a;}
Vec4 Cross(Vec4 a,Vec4 b){return {std::fma(-a[2],b[1],a[1]*b[2]),std::fma(-a[0],b[2],a[2]*b[0]),std::fma(-a[1],b[0],a[0]*b[1]),std::fma(-a[3],b[3],a[3]*b[3])};}
Vec4 Signed(Vec4 v,bool positive){return positive?v:Scale(v,-1);}
Vec4 Rotate(Vec4 axis,Vec4 value,float angle){auto sc=SinCos(angle*.5f);auto q=Scale(axis,sc.first),first=Cross(q,value);Vec4 inner;for(unsigned n=0;n<4;++n)inner[n]=std::fma(sc.second,value[n],first[n]);auto second=Cross(q,inner);for(unsigned n=0;n<4;++n)second[n]=std::fma(2.f,second[n],value[n]);return second;}
Mat4 Truck(GrindOrientationInput i){const auto yaw=i.yaw_1504*-.68f;auto forward=i.board[2];if(std::abs(yaw)>0)forward=Rotate(i.normal,forward,yaw);auto right=Cross(i.normal,forward);const auto magnitude=GrindForceLength(right);if(magnitude<=.001f)return i.board;right=Scale(right,GrindRefinedReciprocal(magnitude));auto up=Cross(forward,right);const auto pitch=(i.switched?-i.pitch_1508:i.pitch_1508)*.68f;if(std::abs(pitch)>0){forward=Rotate(right,forward,pitch);up=Cross(forward,right);}return {right,up,forward,i.board[3]};}
Mat4 Orthonormal(Mat4 input){Mat4 output{};for(int axis=2;axis>=0;--axis){auto value=input[std::size_t(axis)];for(int previous=2;previous>axis;--previous)value=Sub(value,Scale(output[std::size_t(previous)],Dot3(output[std::size_t(previous)],input[std::size_t(axis)])));output[std::size_t(axis)]=Scale(value,InverseLengthSquared(Dot3(value,value),2));}return output;}
}
float GrindForceLength(Vec4 v){const auto square=Dot3(v,v);if(square==0)return 0;return square*InverseLengthSquared(square,2);}
float GrindRefinedReciprocal(float v){float inverse=1.0f/v;for(unsigned n=0;n<2;++n){const float correction=std::fma(-inverse,v,1.0f);inverse=std::fma(inverse,correction,inverse);}return inverse;}
float GrindMaterialMultiplier(std::uint32_t m){switch(m){case 2:case 13:return 1.7f;case 3:return 2.6f;case 4:return .6f;case 5:return 4;case 6:return 5;default:return 1.3f;}}
float GrindPinSlope(Vec4 normal,Vec4 upmost,float relief,const PointGraph<4>& graph){return relief>0?1:graph.Evaluate(Dot3(normal,upmost));}
std::optional<Vec4> GrindLateralPin(Mat4 board,Vec4 point,Vec4 across,Vec4 velocity,float strength,float forward,float up,bool selected,float slope){auto direction=selected?board[2]:Scale(board[2],-1);Vec4 reference;for(unsigned n=0;n<4;++n)reference[n]=std::fma(direction[n],forward,board[3][n])-board[1][n]*up;auto force=Scale(across,Dot3(Sub(point,reference),across)*strength);const auto length=GrindForceLength(force);if(!(length>0))return std::nullopt;auto axis=Scale(force,GrindRefinedReciprocal(length));auto damping=Scale(axis,strength*Word(0x3e083127)*Dot3(velocity,axis));return Scale(Sub(force,damping),slope);}
Vec4 GrindFriction(Vec4 velocity,Vec4 normal,Vec4 support,float time,bool flagged,float surface,std::uint32_t kind,std::array<float,3> strengths){auto tangent=Sub(velocity,Scale(normal,Dot3(velocity,normal)));const auto speed=GrindForceLength(tangent);if(speed<=.001f)return {};const auto strength=strengths[kind==0?0:kind==1?1:2];const auto load=VectorMax(support[1],0);const auto flag=flagged?1.9f:1.f;const auto multiplier=load/speed*time*flag*surface*strength*Word(0xbef5c28f);return Scale(tangent,multiplier);}
bool GrindFrictionApplies(Vec4 velocity,Vec4 normal){return GrindForceLength(Sub(velocity,Scale(normal,Dot3(velocity,normal))))>.001f;}
std::vector<Vec4> GrindSlideControl(bool dark,GrindSlideInput i){const auto offset=Dot3(Sub(i.position,i.point),i.across);auto inward=Scale(i.across,offset>0?-1.f:1.f);if(i.preparing_jump){if(std::abs(offset)>.12f)return {Scale(inward,201)};return {};}const auto strength=dark?(1-std::abs(offset)*6.25f)*40:25;auto translate=Scale(i.across,i.translation_2796*strength);if(i.geometry_kind==2)return {translate};auto perpendicular=Sub(i.velocity,Scale(i.direction,Dot3(i.velocity,i.direction)));if(std::abs(offset)>.16f){std::vector<Vec4> forces{Scale(inward,10)};if(Dot3(inward,perpendicular)<0){auto stop=Scale(perpendicular,-(i.total_mass_2660*i.update_frequency));stop[1]=0;forces.push_back(stop);}return forces;}auto damping=Scale(perpendicular,-20);damping[1]=0;return {translate,damping};}
std::optional<Vec4> GrindReleaseForce(GrindReleaseInput i){auto outward=i.force_across||i.geometry_kind==0?Scale(i.across,Dot3(i.across,Sub(i.position,i.point))>0?1.f:-1.f):Scale(i.high_side,-1);if(!(Dot3(i.velocity,outward)<i.speed_limit))return std::nullopt;auto lateral=Scale(outward,i.strength);if(!i.enable_lift)return lateral;const auto upward=VectorMax(i.normal[1],0)*i.lift;for(unsigned n=0;n<4;++n)lateral[n]=std::fma(i.normal[n],upward,lateral[n]);return lateral;}
std::optional<Vec4> GrindSupportPin(Vec4 normal,float relief){if(!(relief>0))return std::nullopt;auto force=Scale(normal,-40);force[1]=0;return force;}
std::optional<Vec4> GrindSupportCoping(Vec4 upmost,Vec4 velocity,float relief){return relief>0&&Dot3(upmost,velocity)<0?std::optional<Vec4>{{0,120,0,0}}:std::nullopt;}
std::optional<Vec4> GrindSupportExitLean(Vec4 high,float angle,const PointGraph<4>& graph){if(!(angle>0))return std::nullopt;return Scale(high,graph.Evaluate(angle)*-65);}
Vec4 GrindTruckCompensation(Vec4 normal,float pitch){return Scale(normal,std::abs(pitch)*-600);}
bool GrindTargetOrientation(std::uint32_t family,GrindOrientationInput i,GrindOrientationTarget& output,std::string& error){Mat4 frame;if(family==0&&std::abs(i.pitch_1508)<=.12f){auto forward=Signed(i.direction,Dot3(i.direction,i.board[2])>0);frame={Cross(i.normal,forward),i.normal,forward,i.board[3]};}else if(family==0||family==3)frame=Truck(i);else if(family==1||family==5){auto right=Signed(i.direction,Dot3(i.direction,i.board[0])>0),up=family==5?Scale(i.normal,-1):i.normal;frame={right,up,Cross(right,up),i.board[3]};}else if(family==2||family==4){auto across=Cross(i.direction,i.normal),axis=Signed(i.direction,!(Dot3(across,Sub(i.board[3],i.point))>0));auto up=Rotate(axis,i.normal,Word(family==4?0x3f3ba866:0x3eb2b8c3)),right=Signed(i.direction,Dot3(i.direction,i.board[0])>0);frame={right,up,Cross(right,up),i.board[3]};}else{error="Unknown physical grind family";return false;}output={frame,family==0?0.f:.09f};return true;}
Mat4 GrindBlendOrientation(Mat4 current,Mat4 target){return InterpolateMatrix(Orthonormal(current),Orthonormal(target),.1f).first;}
std::array<float,3> GrindNoiseAngles(float speed,float amount,std::array<std::uint32_t,3> draws){const auto speed_factor=VectorMin(speed*.5f,1),amplitude=speed_factor*amount*.06f,width=amplitude*2;std::array<float,3> output;for(unsigned n=0;n<3;++n){const auto unit=float(draws[n]%100000)*.00001f;output[n]=std::fma(unit,width,-amplitude);}return output;}
Mat4 ApplyGrindOrientationNoise(Mat4 frame,float speed,float amount,std::array<std::uint32_t,3> draws){auto angles=GrindNoiseAngles(speed,amount,draws);auto x=SinCos(angles[0]),y=SinCos(angles[1]),z=SinCos(angles[2]);const auto sx=x.first,cx=x.second,sy=y.first,cy=y.second,sz=z.first,cz=z.second;const auto sx_cz=sx*cz,cx_sz=cx*sz,cx_cz=cx*cz,sx_sz=sx*sz;std::array<std::array<float,3>,3> columns{{{cy*cz,cy*sz,-sy},{sy*sx_cz-cx_sz,std::fma(sy,sx_sz,cx_cz),cy*sx},{std::fma(sy,cx_cz,sx_sz),sy*cx_sz-sx_cz,cy*cx}}};auto result=frame;for(unsigned c=0;c<3;++c)for(unsigned n=0;n<4;++n)result[c][n]=std::fma(columns[c][2],frame[2][n],std::fma(columns[c][1],frame[1][n],columns[c][0]*frame[0][n]));return result;}
GrindLaunchOutput CalculateGrindLaunch(PlayerGrindJumper jumper,GrindLaunchInput i){auto geometry=jumper.geometry;auto normal=geometry.normal;Vec4 candidate;if(jumper.family==2||jumper.family==4){auto across=Cross(normal,geometry.direction),outward=Dot3(across,Sub(i.position_112,geometry.point))>0?across:Scale(across,-1);const auto amount=jumper.family==4?-.1093f:.291f;for(unsigned n=0;n<4;++n)candidate[n]=normal[n]+outward[n]*amount;}else for(unsigned n=0;n<4;++n)candidate[n]=std::fma(geometry.upmost[n],.5f,normal[n]*.5f);const auto magnitude=GrindForceLength(candidate);if(magnitude>.1f)normal=Scale(candidate,GrindRefinedReciprocal(magnitude));auto planar=Sub(i.velocity_400,Scale(normal,Dot3(i.velocity_400,normal)));const auto vertical=i.vertical_jump*1.03f;Vec4 base;for(unsigned n=0;n<4;++n)base[n]=std::fma(normal[n],vertical,planar[n]);auto across=Cross(geometry.direction,normal);auto balance=i.balance_2800;const auto low=jumper.energy<.31f;if(low){if(balance<0){if(balance- -.42f>=0)balance=-.42f;}else if(balance>0){if(!(balance-.42f>=0))balance=.42f;}else balance=Dot3(Sub(i.position_112,i.current_point_1120),across)>0?.42f:-.42f;jumper.cooldown=10;}const auto side=geometry.geometry_kind!=0?i.geometry_side_jump:0.f;auto lateral=Sub(Scale(across,balance*1.8f),Scale(geometry.high_side,side));const auto length=GrindForceLength(lateral);if(length>1.8f)lateral=Scale(lateral,1.8f/length);Vec4 velocity;for(unsigned n=0;n<4;++n)velocity[n]=base[n]+lateral[n];jumper.launched=true;const auto energy=jumper.energy-.6f;jumper.energy=-energy>=0?0:energy;return {velocity,jumper,low?0x02000000u:0u};}
}
