// Complete immutable lifecycle helper prefix is generated by the checker;
// only actual owner observations and wire readers are reused.
#include "FootplantRuntime.h"
#include "handplant_lifecycle_helpers.inc"
namespace {
Vec4 Decode(RawVector words) {
  Vec4 v;
  for (std::size_t k = 0; k < 4; ++k)
    v[k] = plant_math::Float(words[k]);
  return v;
}
void QueryOut(Output &o, const AirTrajectoryQueryResult &r) {
  o.Floats(r.contact_position);
  o.Floats(r.contact_normal);
  o.Floats(r.landing_normal);
  o.Float(r.contact_time);
  o.Matrix(r.contact_transform);
  o.Word(std::uint32_t(r.contact_frame));
  o.Word(r.surface);
  o.Word(r.geometry);
}
void FootOwnerOut(Output &o, const FootplantRuntime &f) {
  o.Word(f.enabled);
  QueryOut(o, f.result);
  o.Word(f.selected_toe ? std::uint32_t(*f.selected_toe) : 0xffffffffu);
  for (bool v : {f.candidate, f.hit, f.perform, f.flag_627, f.launch_valid,
                 f.lock_valid, f.contact_active, f.requested})
    o.Word(v);
  o.Floats(std::array<float, 6>{f.contact_time, f.scalar_596, f.scalar_600,
                                f.target_blend, f.active_elapsed,
                                f.scalar_612});
  o.Word(f.surface);
  for (auto v : {f.contact, f.adjusted_contact, f.current_up, f.selected_world,
                 f.selected_record, f.leg_direction})
    o.Floats(v);
  for (auto v : f.vectors_352_368)
    o.Floats(v);
  for (auto v : f.curve)
    o.Floats(v);
  for (auto v :
       {f.physical_com, f.animation_com, f.launch_direction, f.locked_target})
    o.Floats(v);
  TrajectoryOut(o, f.request);
  TrajectoryOut(o, f.completed_trajectory);
}
void FootSettingsOut(Output &o, const FootplantSettings &s) {
  o.Floats(s.deck_bounds);
  o.Floats(std::array<float, 4>{s.max_leg_angle_error, s.leg_length_on_landing,
                                s.foot_volume_y_offset,
                                s.deck_bounds_y_offset});
  o.Floats(s.radial_speed_scale.x);
  o.Floats(s.radial_speed_scale.y);
  o.Floats(std::array<float, 9>{s.max_horizontal_speed, s.max_descending_speed,
                                s.release_outward_speed, s.end_handle,
                                s.end_angle, s.end_leg_length, s.start_handle,
                                s.min_duration, s.max_duration});
}
void PublicationOut(Output &o, const AirOutputFields &f) {
  o.Floats(std::array<float, 3>{f.footplant_contact_time_208,
                                f.footplant_duration_212,
                                f.footplant_surface_height_216});
  o.Word(f.footplant_surface_224);
  for (auto v :
       {f.footplant_left_449, f.footplant_right_450, f.flag_447, f.flag_448})
    o.Word(v);
}
void LaunchOut(Output &o, const AirLaunchInfo &v) {
  o.Matrix(v.reckoning_transform);
  o.Matrix(v.reckoning_inverse);
  for (auto a :
       {v.start_velocity, v.com_velocity, v.skeleton_vector_160,
        v.skeleton_vector_176, v.board_position, v.animation_com_position,
        v.start_position_override, v.board_position_override})
    o.Floats(a);
  o.Floats(std::array<float, 3>{v.cone_angle_x, v.cone_angle_z, v.timestep});
  o.Word(v.player_jumped);
  o.Word(v.use_position_override);
  o.Word(v.trajectory_count);
}
void TrajectoryOwnerOut(Output &o, const AirTrajectoryRuntime &a) {
  const auto &s = a.selector;
  for (bool v :
       {s.Pending(), s.Valid(), s.JustChanged(), s.AllPredictionsMissed(),
        s.GrindLockedToMiddle(), s.AdjustedOnVert()})
    o.Word(v);
  o.Word(s.Pass());
  o.Word(s.SelectedIndex() ? std::uint32_t(*s.SelectedIndex()) : 0xffffffffu);
  o.Word(s.LaunchInfo().has_value());
  if (s.LaunchInfo())
    LaunchOut(o, *s.LaunchInfo());
  o.Word(std::uint32_t(s.Requests().size()));
  for (const auto &r : s.Requests()) {
    TrajectoryOut(o, r.trajectory);
    o.Floats(std::array<float, 3>{r.radius, r.start_error, r.end_error});
  }
  o.Word(s.Selection().has_value());
  if (s.Selection()) {
    const auto &v = *s.Selection();
    o.Word(std::uint32_t(v.candidate_index));
    QueryOut(o, v.prediction.result);
    TrajectoryOut(o, v.prediction.request.trajectory);
    o.Floats(std::array<float, 3>{v.prediction.request.radius,
                                  v.prediction.request.start_error,
                                  v.prediction.request.end_error});
    for (auto x : {v.start_velocity, v.landing_normal, v.collision_velocity,
                   v.collision_position})
      o.Floats(x);
    TrajectoryOut(o, v.com_trajectory);
    o.Word(v.surface_category);
    o.Word(v.wall_ride);
    o.Word(v.grind.has_value());
  }
  o.Word(a.PendingResults().has_value());
  if (a.PendingResults()) {
    o.Word(std::uint32_t(a.PendingResults()->size()));
    for (const auto &r : *a.PendingResults())
      QueryOut(o, r);
  }
  o.Word(bool(a.GrindWorld()));
  o.Word(std::uint32_t(a.NearbyGrinds().size()));
  for (auto v : a.NearbyGrinds())
    o.Word(std::uint32_t(v));
}
void FootSnapshot(Output &o, const FootplantRuntime &f,
                  const AirTrajectoryRuntime &trajectory,
                  const AirOutputFields &pub, const WipeoutRequests &wipeout,
                  const SkeletonCollisionMode &collision) {
  o.Word(6);
  Block(o, [&] { FootOwnerOut(o, f); });
  Block(o, [&] { FootSettingsOut(o, f.settings); });
  Block(o, [&] { PublicationOut(o, pub); });
  Block(o, [&] {
    for (bool v : wipeout.reasons)
      o.Word(v);
    o.Floats(wipeout.values);
    o.Word(wipeout.count);
    o.Float(wipeout.cooldown);
    o.Word(std::uint32_t(wipeout.contact_frames));
    o.Float(wipeout.balance);
    o.Word(wipeout.mode);
  });
  Block(o, [&] { TrajectoryOwnerOut(o, trajectory); });
  Block(o, [&] {
    for (const auto &part : collision.parts)
      o.Word(part.volume_group);
  });
}
KnownAirFootplantInput Packet(Input &i) {
  return {Trajectory(i), i.Float(), i.Floats<4>(), i.Floats<4>()};
}
} // namespace
int main(int argc, char **argv) {
  if (argc != 6)
    return 2;
  SettingsDatabase data;
  PhysicsSkeletons skeletons;
  AnimationPoseFrames frames;
  std::string error;
  if (!data.Load(File(argv[1]), error) ||
      !skeletons.Load(File(argv[2]), argv[4], error) ||
      !frames.rig.Load(File(argv[3]), error)) {
    std::cerr << error;
    return 2;
  }
  const auto *definition = skeletons.Find("PHYS_TPOSE");
  if (!definition)
    return 2;
  AnimationPoseEvaluator evaluator(std::move(frames));
  if (!evaluator.LoadAuthoredClips(argv[5], error))
    return 2;
  const auto settings = PhysicalSimulationSettings::Load(
      data, *definition, evaluator.frames.rig, error);
  const auto asettings = AnimatedSkeletonSettings::Load(
      data, *definition, evaluator.frames.rig, false, error);
  if (!settings || !asettings)
    return 2;
  Input i{{std::istreambuf_iterator<char>(std::cin), {}}, 0};
  Output o;
  const auto count = i.Word();
  o.Word(count);
  for (unsigned c = 0; c < count; ++c) {
    auto world = World(i);
    std::vector<PlayerGrindPrimitive> edges;
    const auto n = i.Word();
    for (unsigned e = 0; e < n; ++e) {
      const auto start = i.Floats<4>(), end = i.Floats<4>();
      const auto owner = i.Wide();
      edges.push_back({start, end, owner});
    }
    auto physical = PhysicalSimulationRuntime::Initialize(
        *settings, data, evaluator, std::move(world),
        settings->Spawn({0, -.035f, 0}), error);
    if (!physical)
      return 2;
    auto &p = *physical;
    AnimatedSkeleton animated(*asettings);
    auto ik = FootIk::Load(data, evaluator.frames.rig, animated, error);
    auto input = SkeletonInputRuntime::Load(data, error);
    auto sair = SkeletonAir::Load(data, error);
    PhysicsAnimationInput anim;
    Handplant h;
    AirReckoning air;
    FootplantRuntime f;
    AirStateSettings air_settings;
    AirTrajectoryRuntime trajectory;
    if (!ik || !input || !sair ||
        !anim.Load(data, evaluator.frames.rig, "normal", error) ||
        !h.Load(data, error) || !air.Load(data, error) ||
        !f.Load(data, error) || !air_settings.Load(data, error) ||
        !trajectory.Load(data, error)) {
      std::cerr << error;
      return 2;
    }
    auto provider = PlayerGrindStaticProvider::FromConverted({}, error);
    if (!provider)
      return 2;
    trajectory.BindGrindWorld(
        std::make_shared<PlayerGrindStaticProvider>(std::move(*provider)));
    ProcessedPhysicsInput processed{};
    ResetProcessedPhysicsInput(processed);
    std::uint8_t board_animated = 0;
    std::vector<Mat4> globals;
    const SkeletonInputOwners owners{p, animated, *ik, anim};
    KnownAirFootplantInput packet{};
    AirOutputFields pub{};
    WipeoutRequests wipeout;
    wipeout.InitializePlayer();
    std::optional<BoardToolkit> toolkit;
    const auto rows = i.Word();
    o.Word(rows);
    FootSnapshot(o, f, trajectory, pub, wipeout, p.skeleton_collision);
    Snapshot(o, h, air, *sair, p, animated, *ik, *input, anim, processed,
             board_animated);
    for (unsigned r = 0; r < rows; ++r) {
      const auto op = i.Word();
      o.Word(op);
      bool okay = true;
      std::vector<std::uint32_t> extra;
      error.clear();
      switch (op) {
      case 0:
        Publish(i, processed, p);
        processed.vectors_544_560_592_608[0] = Raw(i.Floats<4>());
        break;
      case 1: {
        const auto kind = i.Word();
        globals.clear();
        if (kind != 4) {
          static const char *names[] = {"RIG_TPOSE", "POSTURE_STIFF_POSE",
                                        "POSTURE_SLOUCH_POSE",
                                        "POSTURE_BUFF_POSE"};
          PoseCommand command;
          command.kind = PoseCommand::Kind::Pose;
          command.name = names[kind == 5 ? 0 : kind];
          std::vector<Sqt> pose;
          if (!evaluator.Evaluate({command}, pose, error) ||
              !evaluator.Hierarchy(pose, globals, error))
            return 2;
          if (kind == 5)
            globals.resize(1);
        }
        const auto deck = p.DeckFrame();
        const LandingInput landing{0,
                                   processed.flags_2468,
                                   processed.flags_2472,
                                   processed.flags_2476,
                                   0,
                                   p.skeleton.record.centre_of_mass_velocity[1],
                                   p.skeleton.record.centre_of_mass[1] -
                                       deck[3][1],
                                   0};
        okay = animated.ProcessPose(
            owners.AnimationOwners(), globals, landing, processed.timestep_2604,
            processed.flags_2468, processed.flags_2472, std::nullopt, error);
        break;
      }
      case 2:
        packet = Packet(i);
        break;
      case 3:
        if (!toolkit)
          std::abort();
        f.UpdateCandidate(packet, {processed, *toolkit, animated, p, edges});
        break;
      case 4:
        f.UpdateLaunch(packet);
        break;
      case 5:
        if (!toolkit)
          std::abort();
        okay = f.ConsumeAndSubmit(packet,
                                  {processed, *toolkit, animated, p, edges},
                                  *ik, p.skeleton_collision, error);
        break;
      case 6:
        okay = f.GroundEnter(p, processed, board_animated, error);
        break;
      case 7: {
        const auto adjust = i.Floats<2>();
        anim.extra.body_adjust = adjust;
        okay = f.GroundUpdate({processed, owners, *input, globals, *sair},
                              toolkit, air_settings, trajectory,
                              anim.extra.body_adjust, error);
        break;
      }
      case 8:
        f.PostPhysics(processed, wipeout);
        break;
      case 9:
        if (i.Word())
          f.FullReset();
        else
          f.Reset();
        break;
      case 10:
        pub.footplant_contact_time_208 = i.Float();
        pub.footplant_duration_212 = i.Float();
        pub.footplant_surface_height_216 = i.Float();
        pub.footplant_surface_224 = i.Word();
        pub.footplant_left_449 = std::uint8_t(i.Word());
        pub.footplant_right_450 = std::uint8_t(i.Word());
        pub.flag_447 = std::uint8_t(i.Word());
        pub.flag_448 = std::uint8_t(i.Word());
        f.Publish(pub);
        break;
      case 11: {
        const auto com = i.Floats<4>(), velocity = i.Floats<4>();
        extra.push_back(f.Start(com, velocity));
        break;
      }
      case 12: {
        const float t = i.Float();
        const auto adjust = i.Floats<2>();
        f.Adjust(t, adjust);
        break;
      }
      case 13: {
        f.selected_toe =
            i.Word() == 0 ? std::nullopt : std::optional<std::size_t>(i.Word());
        break;
      }
      case 14: {
        std::vector<FootplantEdge> e;
        const auto count = i.Word();
        for (unsigned k = 0; k < count; ++k) {
          const auto a = i.Floats<3>(), b = i.Floats<3>();
          e.push_back({{a[0], a[1], a[2]}, {b[0], b[1], b[2]}});
        }
        const auto reference = i.Floats<4>();
        const auto filtered = FootplantFilterEdges(e, reference);
        Output part;
        part.Word(std::uint32_t(filtered.size()));
        for (const auto &x : filtered) {
          part.Floats(std::array<float, 3>{x.start.x, x.start.y, x.start.z});
          part.Floats(std::array<float, 3>{x.end.x, x.end.y, x.end.z});
        }
        extra = std::move(part.words);
        break;
      }
      case 15:
        f.UpdatePose(packet, p.roots, *ik, p.skeleton_collision);
        break;
      case 16:
        if (i.Word())
          toolkit = BoardToolkit::FromBoard(
              p.board, processed.flags_2468, processed.scalar_2612,
              Decode(processed.vectors_464_480_496_512_528[0]), {0, 1, 0, 0});
        else
          toolkit.reset();
        break;
      case 17:
        processed.state_variant_index_2528 = i.Word();
        processed.state_2504 = i.Word();
        processed.external_physics_1616.flags = i.Word();
        processed.transition_2636 = i.Float();
        processed.prepared_jump_704 = Raw(i.Floats<4>());
        break;
      case 18:
        trajectory.selector.Reset();
        break;
      default:
        return 2;
      }
      o.Status(okay, error);
      o.Word(std::uint32_t(extra.size()));
      for (auto w : extra)
        o.Word(w);
      FootSnapshot(o, f, trajectory, pub, wipeout, p.skeleton_collision);
      Snapshot(o, h, air, *sair, p, animated, *ik, *input, anim, processed,
               board_animated);
    }
  }
  if (i.at != i.data.size())
    return 2;
  for (auto w : o.words)
    for (unsigned k = 0; k < 4; ++k)
      std::cout.put(char(w >> (8 * k)));
  return std::cout ? 0 : 2;
}
