// Offline QA transport only. GameplaySession is the sole simulation owner.
#include "GroundSurfaceRuntime.h"
#include "GameplaySession.h"
#include <algorithm>
#include <charconv>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <deque>
#include <fstream>
#include <iostream>
#include <iterator>
#include <limits>
#include <memory>
#include <mutex>
#include <pthread.h>
#include <string>
#include <string_view>
#include <vector>
#if defined(__clang__)
#pragma clang fp contract(off)
#endif

// Generated by build_native_session_cli.py from the existing accepted JSON
// reader. The manifest records its exact source boundaries and hashes.
namespace cli_json {
#include "gameplay_cli_json.inc"
}
namespace {
using namespace atelier::skate;
using cli_json::Json;
using cli_json::Reader;

bool Parse(std::string_view text, Json& result, std::string& error)
{
    Reader reader(text,error);
    if(!reader.Value(result))return false;
    reader.White();
    if(reader.at!=text.size())return reader.Fail("trailing characters",reader.at+1);
    return true;
}
const Json* Field(const Json& object,std::string_view key)
{
    for(std::size_t i=0;i<object.keys.size();++i)
        if(object.keys[i]==key)return &object.children[i];
    return nullptr;
}
bool Fields(const Json& object,std::initializer_list<std::string_view> allowed,
    std::initializer_list<std::string_view> required,std::string& error)
{
    if(object.kind!=Json::Object){error="Expected a command or world object";return false;}
    for(std::size_t i=0;i<object.keys.size();++i)
    {
        const auto& name=object.keys[i];
        if(std::find(allowed.begin(),allowed.end(),name)==allowed.end())
        {error="unknown field `"+name+"`";return false;}
        if(std::find(object.keys.begin(),object.keys.begin()+i,name)!=object.keys.begin()+i)
        {error="duplicate field `"+name+"`";return false;}
    }
    for(const auto name:required)if(!Field(object,name))
    {error="missing field `"+std::string(name)+"`";return false;}
    return true;
}
bool Float(const Json& value,float& result,std::string& error)
{
    if(value.kind!=Json::Number){error="Expected f32";return false;}
    // serde's typed f32 visitor converts fitting integer tokens directly.
    // Going through f64 first can round those tokens twice.
    if(value.text!="-0" && value.text.find_first_of(".eE")==std::string::npos)
    {
        if(!value.text.empty() && value.text.front()=='-')
        {
            std::int64_t integer=0;
            const auto parsed=std::from_chars(value.text.data(),
                value.text.data()+value.text.size(),integer);
            if(parsed.ec==std::errc{} && parsed.ptr==value.text.data()+value.text.size())
            {result=float(integer);return true;}
        }
        else
        {
            std::uint64_t integer=0;
            const auto parsed=std::from_chars(value.text.data(),
                value.text.data()+value.text.size(),integer);
            if(parsed.ec==std::errc{} && parsed.ptr==value.text.data()+value.text.size())
            {result=float(integer);return true;}
        }
    }
    result=cli_json::Number(value.text);return true;
}
bool FloatField(const Json& object,std::string_view key,float& result,std::string& error)
{
    const auto* value=Field(object,key);
    return !value || Float(*value,result,error);
}
// The player's feel (FeelTuning.h) by its field names; fields left out stay stock.
bool Feel(const Json& value,FeelTuning& feel,std::string& error)
{
    if(value.kind!=Json::Object){error="Expected feel object";return false;}
    const std::pair<std::string_view,float FeelTuning::*> fields[]{
        {"flick_radius",&FeelTuning::flick_radius},{"flick_window",&FeelTuning::flick_window},{"flick_pace",&FeelTuning::flick_pace},
        {"gravity",&FeelTuning::gravity},{"boneless",&FeelTuning::boneless},{"hippy",&FeelTuning::hippy},
        {"rail_magnetism",&FeelTuning::rail_magnetism},{"grind_pop",&FeelTuning::grind_pop},{"grind_friction",&FeelTuning::grind_friction},
        {"braking",&FeelTuning::braking},{"steering",&FeelTuning::steering},{"carve",&FeelTuning::carve},{"grip",&FeelTuning::grip},
        {"powerslide",&FeelTuning::powerslide},{"rolling_friction",&FeelTuning::rolling_friction},{"hill_speed",&FeelTuning::hill_speed},
        {"pump",&FeelTuning::pump},{"wobble",&FeelTuning::wobble},{"wobble_onset",&FeelTuning::wobble_onset},
        {"manual_drift",&FeelTuning::manual_drift},{"landing",&FeelTuning::landing},{"impact",&FeelTuning::impact}};
    for(std::size_t i=0;i<value.keys.size();++i)
    {
        const auto& key=value.keys[i];const auto& child=value.children[i];
        if(key=="auto_push" || key=="assisted_air")
        {
            float choice=0;if(!Float(child,choice,error))return false;
            if(!(choice==-1 || choice==0 || choice==1)){error="`"+key+"` is -1, 0 or 1";return false;}
            (key=="auto_push"?feel.auto_push:feel.assisted_air)=std::int8_t(choice);continue;
        }
        if(key=="tight_flicks" || key=="flick_120hz")
        {
            float choice=0;if(!Float(child,choice,error))return false;
            if(!(choice==0 || choice==1)){error="`"+key+"` is 0 or 1";return false;}
            (key=="tight_flicks"?feel.tight_flicks:feel.flick_120hz)=std::int8_t(choice);continue;
        }
        bool known=false;
        for(const auto& [name,field]:fields)if(key==name){if(!Float(child,feel.*field,error))return false;known=true;}
        if(!known){error="unknown feel field `"+key+"`";return false;}
    }
    return true;
}
bool Boolean(const Json& value,bool& result,std::string& error)
{
    if(value.kind!=Json::Bool){error="Expected boolean";return false;}
    result=value.text=="true";return true;
}
bool String(const Json& value,std::string& result,std::string& error)
{
    if(value.kind!=Json::String){error="Expected string";return false;}
    result=value.text;return true;
}
template<class T> bool Integer(const Json& value,T& result,std::string& error)
{
    if(value.kind!=Json::Number || value.text=="-0")
    {error="Expected integer";return false;}
    std::int64_t parsed=0;
    const auto converted=std::from_chars(value.text.data(),value.text.data()+value.text.size(),parsed);
    if(converted.ec!=std::errc{} || converted.ptr!=value.text.data()+value.text.size()
        || parsed<std::int64_t(std::numeric_limits<T>::min())
        || parsed>std::int64_t(std::numeric_limits<T>::max()))
    {error="Controller or generation integer is out of range";return false;}
    result=T(parsed);return true;
}
template<class T,std::size_t N> bool Integers(const Json& value,std::array<T,N>& result,std::string& error)
{
    if(value.kind!=Json::Array || value.children.size()!=N)
    {error="Invalid controller array length";return false;}
    for(std::size_t i=0;i<N;++i)if(!Integer(value.children[i],result[i],error))return false;
    return true;
}
bool Vector(const Json& value,Vec3& result,std::string& error)
{
    if(value.kind!=Json::Array || value.children.size()!=3)
    {error="Expected an array of length 3";return false;}
    return Float(value.children[0],result.x,error) && Float(value.children[1],result.y,error)
        && Float(value.children[2],result.z,error);
}
bool Finite(Vec3 value)
{return std::isfinite(value.x)&&std::isfinite(value.y)&&std::isfinite(value.z);}
struct World
{
    GameplayWorldSnapshot collision;
    Vec3 spawn{};
    float heading=0;
};
bool ReadWorld(const std::string& path,World& result,std::string& error)
{
    std::ifstream input(path,std::ios::binary);
    if(!input){error="Cannot read collision snapshot: "+path;return false;}
    const std::string text{std::istreambuf_iterator<char>(input),std::istreambuf_iterator<char>()};
    if(input.bad()){error="Cannot read collision snapshot: "+path;return false;}
    Json object;
    if(!Parse(text,object,error)
        || !Fields(object,{"triangles","rails","spawn","heading","surfaces"},{"triangles","rails","spawn","heading"},error)
        || !Vector(*Field(object,"spawn"),result.spawn,error)
        || !Float(*Field(object,"heading"),result.heading,error))return false;
    const auto& triangles=*Field(object,"triangles");
    const auto& rails=*Field(object,"rails");
    if(triangles.kind!=Json::Array || rails.kind!=Json::Array)
    {error="Expected triangle and rail arrays";return false;}
    for(const auto& triangle:triangles.children)
    {
        if(triangle.kind!=Json::Array || triangle.children.size()!=3)
        {error="Expected a triangle with 3 vertices";return false;}
        std::array<Vec3,3> vertices;
        for(std::size_t i=0;i<3;++i)if(!Vector(triangle.children[i],vertices[i],error))return false;
        result.collision.triangles.push_back(vertices);
    }
    for(const auto& rail:rails.children)
    {
        if(rail.kind!=Json::Array){error="Expected rail array";return false;}
        std::vector<std::array<float,3>> points;
        for(const auto& point:rail.children)
        {
            Vec3 value;
            if(!Vector(point,value,error))return false;
            points.push_back({value.x,value.y,value.z});
        }
        result.collision.rails.push_back(std::move(points));
    }
    if(const auto* surfaces=Field(object,"surfaces"))
    {
        if(surfaces->kind!=Json::Array || surfaces->children.size()!=result.collision.triangles.size())
        {error="Expected one packed surface per triangle";return false;}
        for(const auto& surface:surfaces->children)
        {
            std::uint16_t value=0;
            if(!Integer(surface,value,error))return false;
            result.collision.surfaces.push_back(value);
        }
    }
    bool valid=!result.collision.triangles.empty() && result.collision.triangles.size()<=500000
        && Finite(result.spawn) && std::isfinite(result.heading);
    for(const auto& triangle:result.collision.triangles)for(Vec3 vertex:triangle)valid=valid&&Finite(vertex);
    for(const auto& rail:result.collision.rails)
    {
        valid=valid&&rail.size()>=2;
        for(const auto& point:rail)for(float lane:point)valid=valid&&std::isfinite(lane);
    }
    if(!valid){error="Invalid collision snapshot";return false;}
    return true;
}

// JSON observations preserve the old QA schema. Nonfinite optional camera,
// score and manual floats serialize to null as serde_json does; pose is checked
// before emission, including the actual animated root used by Session::pose.
void Quoted(std::ostream& out,std::string_view value)
{
    constexpr char hex[]="0123456789abcdef";
    out.put('"');
    for(unsigned char c:value)
    {
        switch(c)
        {
        case '"':out<<"\\\"";break;
        case '\\':out<<"\\\\";break;
        case '\b':out<<"\\b";break;
        case '\f':out<<"\\f";break;
        case '\n':out<<"\\n";break;
        case '\r':out<<"\\r";break;
        case '\t':out<<"\\t";break;
        default:
            if(c<32)out<<"\\u00"<<hex[c>>4]<<hex[c&15];
            else out.put(char(c));
        }
    }
    out.put('"');
}
void Number(std::ostream& out,float value)
{
    if(!std::isfinite(value)){out<<"null";return;}
    char buffer[64];
    // serde_json::Value stores f32 fields as exact promoted f64 values.
    const auto converted=std::to_chars(buffer,buffer+sizeof(buffer),double(value),
        std::chars_format::general,std::numeric_limits<double>::max_digits10);
    out.write(buffer,converted.ptr-buffer);
    if(std::string_view(buffer,std::size_t(converted.ptr-buffer)).find_first_of(".eE")
        ==std::string_view::npos)out<<".0";
}
void Matrix(std::ostream& out,const Mat4& value)
{
    out.put('[');
    for(std::size_t i=0;i<16;++i){if(i)out.put(',');Number(out,value[i/4][i%4]);}
    out.put(']');
}
void Pose(std::ostream& out,const std::vector<Mat4>& values)
{
    out.put('[');
    for(std::size_t i=0;i<values.size();++i){if(i)out.put(',');Matrix(out,values[i]);}
    out.put(']');
}
bool Publish(const GameplaySession& session,bool ready,std::uint32_t generation,std::string& error)
{
    const auto& game=*session.gameplay;
    const auto pose=session.Pose();
    const auto& root=pose.root;
    const auto velocity=pose.velocity;
    if(!session.CheckPublishedPose(error))return false;
    std::vector<Mat4> reference;
    if(ready && !session.ReferencePose(reference,error))return false;
    auto& out=std::cout;
    out<<"{\"type\":\""<<(ready?"ready":"pose")<<"\",\"tick\":"<<pose.tick
        <<",\"generation\":"<<generation<<",\"root\":";
    Matrix(out,root);out<<",\"bones\":";Pose(out,pose.bones);
    out<<",\"velocity\":[";Number(out,velocity.x);out.put(',');Number(out,velocity.y);out.put(',');Number(out,velocity.z);
    out<<"],\"state\":";Quoted(out,pose.state);
    const auto& score=game.scoring.session.holder.State().snapshot;
    out<<",\"score\":";Number(out,score.completed_lines+score.line);
    out<<",\"reward\":";Number(out,score.last_reward);
    out<<",\"trick\":";Quoted(out,game.scoring.CurrentTrick());
    out<<",\"manual\":";Number(out,game.animation_input.fields.balance);
    const auto ground=ReportGroundSurface(game.physical->riding);
    out<<",\"surface\":["<<ground.physics<<','<<ground.sound<<','<<ground.wheels<<']';
    out<<",\"camera\":";
    if(pose.camera)
    {
        const auto& camera=*pose.camera;
        out<<"{\"position\":[";
        for(std::size_t i=0;i<3;++i){if(i)out.put(',');Number(out,camera.position[i]);}
        out<<"],\"basis\":[";
        for(std::size_t i=0;i<9;++i){if(i)out.put(',');Number(out,camera.basis.columns[i/3][i%3]);}
        out<<"],\"fov\":";Number(out,camera.field_of_view_degrees);out.put('}');
    }
    else out<<"null";
    if(ready)
    {
        out<<",\"names\":[";
        for(std::size_t i=0;i<pose.names.size();++i){if(i)out.put(',');Quoted(out,pose.names[i]);}
        out<<"],\"reference\":";Pose(out,reference);
    }
    out<<"}\n";out.flush();
    if(!out){error="Cannot write QA observation";return false;}
    return true;
}

struct BuiltWorld
{
    std::optional<PreparedGameplayWorld> world;
    std::string error;
};
struct WorldQueue
{
    std::mutex mutex;
    std::deque<BuiltWorld> completed;
};
struct WorldWork
{
    std::string path;
    ContactMaterial material;
    std::shared_ptr<WorldQueue> queue;
};
BuiltWorld Build(const std::string& path,ContactMaterial material)
{
    World parsed;BuiltWorld built;
    if(ReadWorld(path,parsed,built.error))
        BuildGameplayWorld(parsed.collision,material,built.world,built.error);
    return built;
}
void* BuildAsync(void* data)
{
    const std::unique_ptr<WorldWork> work(static_cast<WorldWork*>(data));
    auto built=Build(work->path,work->material);
    const std::lock_guard<std::mutex> lock(work->queue->mutex);
    work->queue->completed.push_back(std::move(built));return nullptr;
}
bool StartAsync(std::string path,ContactMaterial material,const std::shared_ptr<WorldQueue>& queue,std::string& error)
{
    auto work=std::make_unique<WorldWork>(WorldWork{std::move(path),material,queue});
    pthread_attr_t attr;
    int status=pthread_attr_init(&attr);
    if(status){error=std::strerror(status);return false;}
    status=pthread_attr_setstacksize(&attr,32*1024*1024);
    pthread_t thread;
    if(!status)status=pthread_create(&thread,&attr,BuildAsync,work.get());
    pthread_attr_destroy(&attr);
    if(status){error=std::strerror(status);return false;}
    work.release();pthread_detach(thread);return true;
}
bool InstallCompleted(GameplaySession& session,const std::shared_ptr<WorldQueue>& queue,std::string& error)
{
    while(true)
    {
        BuiltWorld built;
        {
            const std::lock_guard<std::mutex> lock(queue->mutex);
            if(queue->completed.empty())return true;
            built=std::move(queue->completed.front());queue->completed.pop_front();
        }
        if(!built.error.empty()){error=std::move(built.error);return false;}
        if(!built.world){error="Collision builder returned no world";return false;}
        if(!session.InstallCollision(std::move(*built.world),error))return false;
    }
}

bool Run(int argc,char** argv,std::string& error)
{
    if(argc!=3){error="Usage: gameplay-session-cli NATIVE_PACKAGE COLLISION_JSON";return false;}
    World initial;
    if(!ReadWorld(argv[2],initial,error))return false;
    std::shared_ptr<const GameplayResources> resources;
    if(!LoadGameplayResources(argv[1],resources,error))return false;
    std::unique_ptr<GameplaySession> owner;
    if(!GameplaySession::Create(std::move(resources),initial.collision,initial.spawn,initial.heading,owner,error)
        || !owner->Activate(initial.spawn,initial.heading,error))return false;
    auto& session=*owner;
    std::uint32_t generation=0;
    if(!Publish(session,true,generation,error))return false;
    const auto queue=std::make_shared<WorldQueue>();
    std::string line;
    while(std::getline(std::cin,line))
    {
        if(!line.empty()&&line.back()=='\r')line.pop_back();
        if(line.size()>16384){error="Input packet is too large";return false;}
        Json command;
        if(!Parse(line,command,error))return false;
        const auto* operation=Field(command,"op");
        std::string op;
        if(!operation){error="missing field `op`";return false;}
        if(!String(*operation,op,error))return false;
        if(op=="step")
        {
            if(!Fields(command,{"op","dt","buttons","left","right","triggers","readings"},
                {"op","dt","buttons","left","right","triggers"},error))return false;
            float dt=0;XboxState controls;
            if(!Float(*Field(command,"dt"),dt,error) || !Integer(*Field(command,"buttons"),controls.buttons,error)
                || !Integers(*Field(command,"left"),controls.left,error)
                || !Integers(*Field(command,"right"),controls.right,error)
                || !Integers(*Field(command,"triggers"),controls.triggers,error))return false;
            // The host's 120 Hz stick readings, oldest first: [age, left x, left y, right x, right y] (StickReading).
            std::vector<StickReading> readings;
            if(const auto* list=Field(command,"readings"))
            {
                if(list->kind!=Json::Array){error="Expected readings array";return false;}
                for(const auto& item:list->children)
                {
                    if(item.kind!=Json::Array || item.children.size()!=5){error="Expected [age, lx, ly, rx, ry] reading";return false;}
                    StickReading reading;
                    if(!Float(item.children[0],reading.age,error) || !Integer(item.children[1],reading.left[0],error)
                        || !Integer(item.children[2],reading.left[1],error) || !Integer(item.children[3],reading.right[0],error)
                        || !Integer(item.children[4],reading.right[1],error))return false;
                    if(!std::isfinite(reading.age)||reading.age<0){error="Invalid reading age";return false;}
                    readings.push_back(reading);
                }
            }
            // Source validates dt before consuming any background completion.
            if(!std::isfinite(dt)||dt<0){error="Invalid frame interval";return false;}
            if(!InstallCompleted(session,queue,error) || !session.Step(controls,dt,readings,error)
                || !Publish(session,false,generation,error))return false;
        }
        else if(op=="activate" || op=="configure")
        {
            const bool activate=op=="activate";
            if(activate)
            {
                if(!Fields(command,{"op","spawn","heading","goofy","difficulty","trucks","generation","velocity","pop","spin","push_speed","push_power","vert_assist","feel"},
                    {"op","spawn","heading","goofy","difficulty","trucks"},error))return false;
            }
            else if(!Fields(command,{"op","goofy","difficulty","trucks","pop","spin","push_speed","push_power","vert_assist","feel"},
                {"op","goofy","difficulty","trucks"},error))return false;
            bool goofy=false;std::string difficulty;float trucks=0,pop=1,spin=1,speed=1,power=1,vert_assist=0,heading=0;
            Vec3 spawn{},velocity{};std::uint32_t ride=0;
            if(!Boolean(*Field(command,"goofy"),goofy,error) || !String(*Field(command,"difficulty"),difficulty,error)
                || !Float(*Field(command,"trucks"),trucks,error) || !FloatField(command,"pop",pop,error)
                || !FloatField(command,"spin",spin,error) || !FloatField(command,"push_speed",speed,error)
                || !FloatField(command,"push_power",power,error)
                || !FloatField(command,"vert_assist",vert_assist,error))return false;
            FeelTuning feel;
            if(const auto* v=Field(command,"feel"))if(!Feel(*v,feel,error))return false;
            if(activate)
            {
                if(!Vector(*Field(command,"spawn"),spawn,error) || !Float(*Field(command,"heading"),heading,error))return false;
                if(const auto* v=Field(command,"velocity"))if(!Vector(*v,velocity,error))return false;
                if(const auto* v=Field(command,"generation"))if(!Integer(*v,ride,error))return false;
                if(!Finite(spawn)||!std::isfinite(heading)||!std::isfinite(trucks)||!Finite(velocity))
                {error="Invalid spawn or equipment";return false;}
            }
            else if(!std::isfinite(trucks)){error="Invalid equipment";return false;}
            if(!session.Configure(difficulty,goofy,trucks,error) || !session.Tune(pop,spin,speed,power,vert_assist,error)
                || !session.Feel(feel,error))return false;
            if(activate)
            {
                if(!session.Activate(spawn,heading,error))return false;
                session.Launch(velocity);generation=ride;
                if(!Publish(session,false,generation,error))return false;
            }
        }
        else if(op=="world")
        {
            if(!Fields(command,{"op","path","background"},{"op","path"},error))return false;
            std::string path;bool background=false;
            if(!String(*Field(command,"path"),path,error))return false;
            if(const auto* v=Field(command,"background"))if(!Boolean(*v,background,error))return false;
            const auto material=session.gameplay->physical->settings.board.floor_material;
            if(background){if(!StartAsync(std::move(path),material,queue,error))return false;}
            else
            {
                auto built=Build(path,material);
                if(!built.error.empty()){error=std::move(built.error);return false;}
                if(!built.world){error="Collision builder returned no world";return false;}
                if(!session.InstallCollision(std::move(*built.world),error))return false;
            }
        }
        else if(op=="launch")
        {
            if(!Fields(command,{"op","velocity"},{"op","velocity"},error))return false;
            Vec3 velocity;
            if(!Vector(*Field(command,"velocity"),velocity,error))return false;
            if(!Finite(velocity)){error="Invalid launch velocity";return false;}
            session.Launch(velocity);
        }
        else if(op=="suspend" || op=="quit")
        {
            if(!Fields(command,{"op"},{"op"},error))return false;
            if(op=="quit")return true;
            session.SuspendInput();
        }
        else {error="unknown variant `"+op+"`";return false;}
    }
    if(std::cin.bad()){error="Cannot read QA command";return false;}
    return true;
}
struct RunContext {int argc;char** argv;bool success=false;std::string error;};
void* RunThread(void* data)
{
    atelier::skate::FlushDenormalsToZero();
    auto& context=*static_cast<RunContext*>(data);
    context.success=Run(context.argc,context.argv,context.error);return nullptr;
}
}
int main(int argc,char** argv)
{
    RunContext context{argc,argv,false,{}};
    pthread_attr_t attr;
    int status=pthread_attr_init(&attr);
    if(!status)
    {
        status=pthread_attr_setstacksize(&attr,32*1024*1024);
        pthread_t thread;
        if(!status)status=pthread_create(&thread,&attr,RunThread,&context);
        pthread_attr_destroy(&attr);
        if(!status)status=pthread_join(thread,nullptr);
    }
    if(status)context.error=std::strerror(status);
    if(context.success && !status)return 0;
    std::cout<<"{\"type\":\"error\",\"message\":";
    Quoted(std::cout,context.error);std::cout<<"}\n";std::cout.flush();return 1;
}
