// Accepted physical/adjusted/dispatcher declaration adapters are prepended.
#include "PlayerInputRuntime.h"
#include "PlayerGroundPosition.h"
namespace
{
WorldGeometry ReadInputWorld(ContactMaterial material)
{
    const auto n=Word();std::vector<WorldTriangle> triangles;QueryMetadata metadata;
    std::vector<Vec3> points;
    for(unsigned j=0;j<n;++j){const std::array<Vec3,3> v{Vector(),Vector(),Vector()};const auto fat=Float();const auto flags=Word(),tag=Word();triangles.push_back({TriangleFromVolume(v,fat,{1,1,1},flags),material,tag});metadata.packed_surfaces.push_back(std::uint16_t(Word()));points.insert(points.end(),v.begin(),v.end());}
    const auto pool=Word();const auto group=Word();metadata.island_flags=Word();if(n){QueryMesh mesh;mesh.triangle_range={0,n};mesh.local_bounds=*Bounds::FromPoints(points);mesh.matching_group=std::int32_t(group);mesh.pool=QueryPool(pool);mesh.rejection_flags=0xffffffffu;mesh.geometry=77;metadata.meshes.push_back(mesh);}
    const char* error=nullptr;auto world=WorldGeometry::WithQueryMetadata(std::move(triangles),std::move(metadata),error);if(!world){std::cerr<<error;std::exit(2);}return std::move(*world);
}
struct GlobalTeleportFailure final:PlayerInputTeleportServices
{
    std::vector<Mat4> targets;std::string error="complete global teleport owner is required";
    bool Teleport(PlayerInputOwners,Mat4 target,PlayerInputState&,PhysicalPlayerInput&,ProcessedPhysicsInput&,std::string& out)override{targets.push_back(target);out=error;return false;}
};
// The source's new() selector has no completed grind. The true completion path
// remains explicitly pending the separate actual selector producer comparison.
struct FreshTrajectory final:PlayerTrajectoryGrindOwner{bool GrindLockedToMiddle()const override{return false;}};
void ObserveToolkit(Output& o,const BoardToolkit& t)
{
    for(const auto& m:{t.deck,t.effective,t.inverse_effective})for(const auto& c:m)for(float x:c)o.Float(x);
    for(const auto& v:{t.side,t.up,t.forward,t.horizontal_forward,t.transverse_up,t.forward_velocity,t.travel_direction,t.filtered_normal})for(float x:v)o.Float(x);
    for(float v:{t.absolute_speed,t.control_sign,t.total_mass})o.Float(v);
}
void ObserveInputOwner(const PlayerInputRuntime& r,const GroundRuntime& ground)
{
    Output o{output};Observe(o,r.player);Observe(o,r.physical);Observe(o,r.processed);o.Word(bool(r.toolkit));if(r.toolkit)ObserveToolkit(o,*r.toolkit);
    for(auto v:{r.dynamic_normal.normal,r.dynamic_normal.delta,r.dynamic_normal.acceleration,r.dynamic_normal.last_contact_normal}){o.Float(v.x);o.Float(v.y);o.Float(v.z);}
    const auto& s=r.NormalSettings();for(float v:{s.speed_damping,s.up_vector_damping,s.maximum_delta,s.speed_scale})o.Float(v);for(float v:s.maximum_delta_vs_speed.x)o.Float(v);for(float v:s.maximum_delta_vs_speed.y)o.Float(v);
    o.Word(r.pre_input.pending_geometry);Observe(o,r.pre_input.result);for(auto v:r.pre_input.result_counts)o.Word(v);ObserveState(o,*r.grind);o.Word(bool(r.PendingTeleport()));if(r.PendingTeleport())for(auto v:*r.PendingTeleport())for(float x:v)o.Float(x);
    o.Word(bool(r.pending_grind));if(r.pending_grind)ObservePending(o,*r.pending_grind);o.Word(bool(r.grind_observation));if(r.grind_observation)ObserveObservation(o,*r.grind_observation);Out(ground.retained_board_normal);
}
void ObserveFrame(const PhysicalSimulationRuntime& r,const AnimatedSkeleton& a,const FootIk& ik,const SkeletonInputRuntime& s,const PhysicsAnimationInput& input,const PlayerInputRuntime& owner,const GroundRuntime& ground,const SkeletonWobble& wobble,const Actions& actions)
{
    const auto physical=output.size();Out(0u);Snapshot(r);OutAdjusted(a,ik,s.grind_air,owner.player);ObserveDispatcher(s,input,wobble,false,owner.processed,actions);output[physical]=output.size()-physical-1;
    const auto packet=output.size();Out(0u);ObserveInputOwner(owner,ground);output[packet]=output.size()-packet-1;
}
Mat4 FloatMatrix(const RawMatrix& raw){Mat4 m;for(unsigned j=0;j<4;++j)for(unsigned k=0;k<4;++k)std::memcpy(&m[j][k],&raw[j][k],4);return m;}
void Status(bool ok,const std::string& error){Out(std::uint32_t(ok));Out(error);}
bool InputTick(Input& i,PhysicalSimulationRuntime& r,AnimatedSkeleton& a,FootIk& ik,SkeletonInputRuntime& skeleton,PhysicsAnimationInput& anim,PlayerInputRuntime& owner,GroundRuntime& ground,AnimationPoseEvaluator& evaluator,const PlayerGrindStaticProvider& provider,const PlayerGrindMaterials& materials,Actions& actions,GlobalTeleportFailure& teleport)
{
    const auto state=i.Word(),category=i.Word(),filtered=i.Word(),flags=i.Word();const bool pending=i.Word()!=0,air_target=i.Word()!=0;const auto surface=i.Word(),pose=i.Word();const auto n=i.Word();std::vector<AnimationAttribute> attrs;for(unsigned j=0;j<n;++j)attrs.push_back(i.Attribute());actions.values=i.Floats<18>();actions.calls.clear();auto publication=ReadAnimationPacketFields(i);auto external=ReadExternalPhysicsInput(i);auto packet=ReadPacket(i,publication,external);PlayerInputHostFrame host;host.actor_query_56=i.Word();host.actor_query_44=i.Word();host.input_available=i.Word()!=0;host.transition_action=i.Float();host.published_board_transform=owner.physical.state.flag_61?FloatMatrix(owner.physical.teleport_output->transform):r.DeckFrame();host.air_counter_40=std::int32_t(i.Word());teleport.targets.clear();
    owner.player.flags_1296=flags;owner.pre_input.pending_geometry=pending;auto& physical=owner.physical;physical.state.state_16=state;physical.state.category_12=category;physical.filtered_state_0=filtered;physical.surface_default_mode=surface;physical.state.identifier_8=state+1000;physical.state.surface_height_32=r.skeleton.record.centre_of_mass[1];physical.skeleton.anim_to_world_11920=RawMatrix{};for(unsigned c=0;c<4;++c)physical.skeleton.anim_to_world_11920[c]=Raw(r.skeleton.animation_to_world[c]);physical.reckoning.vector_16=Raw(r.skeleton.record.centre_of_mass_velocity);
    std::string error;SkeletonLineTests lines;if(!r.BeginBoardQueries(error)||!QuerySkeletonLines(r.world,r.skeleton,lines,error)){Status(false,error);return false;}const auto globals=pose==4?std::vector<Mat4>{}:Hierarchy(evaluator,pose);const auto collision=SkeletonInputCollision{r.collision_feedback.flags.compliant,r.collision_feedback.flags.has_impulse,r.collision_pose_error,r.skeleton_collision.partial_ragdoll,r.collision_feedback.drive_weight};const PlayerInputOwners owners{r,ground,skeleton,a,ik,anim,materials};const PlayerInputAnimationFrame animation{{globals,attrs,actions},collision,air_target};std::optional<InputContinuation> continuation;
    const bool start=owner.ProcessStage(owners,r.riding.reckoning_frames.ground,packet,host,animation,teleport,{PlayerInputStage::Kind::ThroughTeleport,{}},provider,continuation,error);Status(start,error);
    bool finish=false;if(start){error.clear();std::optional<InputContinuation> result;finish=owner.ProcessStage(owners,r.riding.reckoning_frames.ground,packet,host,animation,teleport,{PlayerInputStage::Kind::AfterTeleport,*continuation},provider,result,error);Status(finish,error);}else Status(false,"through-teleport input failed");
    std::string query_error;const bool queried=r.FinishBoardQueries(query_error);Status(queried,query_error);lines.Publish(owner.player);if(!finish||!queried)return false;
    error.clear();auto pending_grind=std::move(owner.pending_grind);if(!pending_grind){Status(false,"missing pre result");return false;}const auto& extra=anim.extra;PlayerGrindLiveHost live(r.board,r.settings.board,materials);std::optional<PlayerGrindPostResult> post;const auto deck=r.DeckFrame();const PlayerGrindPostContext context{deck,anim.fields.balance,extra.grind_translation,extra.grind_stability_nudge,extra.grind_up_down,extra.grind_grab_min_height};const bool posted=owner.grind->PostUpdate(owner.processed,r.world,std::move(*pending_grind),context,live,post,error);Status(posted,error);if(!posted)return false;owner.grind_observation=std::make_unique<PlayerGrindObservation>(post->observation);Out(std::uint32_t(post->wipeout_reasons.size()));for(auto v:post->wipeout_reasons)Out(std::uint32_t(v));
    auto& p=owner.processed;const auto saved=p;const auto toolkit=*owner.toolkit;const auto dynamic=r.riding.ground.overall_normal;Vec4 retained;for(unsigned lane=0;lane<4;++lane)std::memcpy(&retained[lane],&p.vectors_464_480_496_512_528[4][lane],4);const PhysicalGroundPacket frame{r.riding.ground.wheel_normal,{retained[0],retained[1],retained[2]},r.riding.motion.speed,r.riding.motion.ground_speed,r.riding.ground.wheel_contact_count};r.processed_flags_2468=p.flags_2468;r.riding.UpdateGroundReckoning(r.board,{r.animation_record.ComToDeck(),anim.fields.spin},p.flags_2468,anim.fields.balance,false,frame);std::array<Mat4,24> drives;
    error.clear();if(!skeleton.GeneralUpdate(p,{r,a,ik,anim},globals,collision,drives,error)){Status(false,error);return false;}if(!r.Solve({0,0},error)){Status(false,error);return false;}Out(std::uint32_t(r.contact_count));Out(std::uint32_t(r.solved_drives?r.solved_drives->rows.size():0));r.FinishBoardOutputs({p.state_2508,frame.wheel_normal,{r.roots.animation_to_world[1][0],r.roots.animation_to_world[1][1],r.roots.animation_to_world[1][2]},{toolkit.deck[3][0],toolkit.deck[3][1],toolkit.deck[3][2]},float(r.ticks)*p.timestep_2604});PhysicalFeedbackInput feedback{p.state_2508,p.category_2512,p.flags_2472,p.flags_2480,{},{}};feedback.vectors_464_480_496_512_528[0]=Four(frame.wheel_normal);feedback.vectors_464_480_496_512_528[1]=feedback.vectors_464_480_496_512_528[2]=Four(r.riding.ground.parts[6].point);feedback.vectors_464_480_496_512_528[4]=Four(dynamic);feedback.vectors_880_896_912_928_944[0]=a.animation_hips[3];feedback.vectors_880_896_912_928_944[1]={0,1,0,0};r.PublishFeedback(feedback);r.skeleton.PublishPhysicalRecord(r.DeckFrame());p=saved;owner.UpdateDynamicNormal(r.riding,{0,-9.81f,0});const bool published=owner.PublishBoard(r.riding,error);Status(published,error);FreshTrajectory selector;error.clear();const bool grind_published=owner.PublishGrindGraphOutputs(r.skeleton.record,r.riding.reckoning_frames.ground[1],selector,error);Status(grind_published,error);error.clear();const bool completed=r.FinishFrame(error);Status(completed,error);return published&&grind_published&&completed;
}
}
int main(int argc,char** argv)
{
    if(argc==3&&std::string_view(argv[2])=="--settings-only"){
        SettingsDatabase data;std::string error;if(!data.Load(FileBytes(argv[1]),error))return 2;auto owner=PlayerInputRuntime::Load(data,error);Status(bool(owner),error);if(owner){GroundRuntime ground;ObserveInputOwner(*owner,ground);}for(auto word:output)for(unsigned j=0;j<4;++j)std::cout.put(static_cast<char>(word>>(j*8)));return 0;
    }
    if(argc!=5)return 2;SettingsDatabase data;PhysicsSkeletons physical;AnimationPoseFrames frames;std::string error;if(!data.Load(FileBytes(argv[1]),error)||!physical.Load(FileBytes(argv[2]),argv[4],error)||!frames.rig.Load(FileBytes(argv[3]),error)){std::cerr<<error;return 2;}const auto* bank=physical.Find("PHYS_TPOSE");if(!bank)return 2;AnimationPoseEvaluator evaluator(std::move(frames));const auto settings=PhysicalSimulationSettings::Load(data,*bank,evaluator.frames.rig,error);const auto animated_settings=AnimatedSkeletonSettings::Load(data,*bank,evaluator.frames.rig,false,error);const auto wobble_settings=SkeletonWobbleSettings::Load(data,error);if(!settings||!animated_settings||!wobble_settings){std::cerr<<error;return 2;}
    Input i;const auto count=i.Word();for(unsigned c=0;c<count;++c){const auto spawn=ReadAffine();auto world=ReadInputWorld(settings->board.floor_material);const auto provider=ReadProvider(i);auto runtime=PhysicalSimulationRuntime::Initialize(*settings,data,evaluator,std::move(world),spawn,error);auto input_runtime=PlayerInputRuntime::Load(data,error);auto skeleton_input=SkeletonInputRuntime::Load(data,error);if(!runtime||!input_runtime||!skeleton_input){std::cerr<<error;return 2;}auto& r=*runtime;auto& owner=*input_runtime;auto& skeleton=*skeleton_input;AnimatedSkeleton animated(*animated_settings);auto feet=FootIk::Load(data,evaluator.frames.rig,animated,error);if(!feet){std::cerr<<error;return 2;}auto ik=*feet;PhysicsAnimationInput anim;if(!anim.Load(data,evaluator.frames.rig,"normal",error)){std::cerr<<error;return 2;}GroundRuntime ground;PlayerGrindMaterials materials(r.settings.board);Actions actions;GlobalTeleportFailure teleport;SkeletonWobble wobble;const auto n=i.Word();Out(c);Out(n);const auto mark=output.size();Out(0u);const auto initial=output.size();Out(0u);ObserveFrame(r,animated,ik,skeleton,anim,owner,ground,wobble,actions);output[initial]=output.size()-initial-1;
        for(unsigned k=0;k<n;++k){const auto op=i.Word();Out(op);const auto at=output.size();Out(0u);const auto effects=output.size();Out(0u);error.clear();switch(op){case 0:{const auto result=output.size();Out(0u);const bool ok=InputTick(i,r,animated,ik,skeleton,anim,owner,ground,evaluator,provider,materials,actions,teleport);output[result]=std::uint32_t(ok);break;}case 1:owner.pre_input.pending_geometry=i.Word()!=0;Status(true,{});break;case 2:{const auto target=i.Floats<16>();Mat4 frame;for(unsigned j=0;j<4;++j)for(unsigned l=0;l<4;++l)frame[j][l]=target[4*j+l];Status(owner.RequestTeleport(frame,error),error);break;}case 3:owner.toolkit.reset();Status(true,{});break;case 4:Status(owner.PublishBoard(r.riding,error),error);break;case 5:{FreshTrajectory selector;Status(owner.PublishGrindGraphOutputs(r.skeleton.record,r.riding.reckoning_frames.ground[1],selector,error),error);break;}case 6:{std::array<Vec4,4> wheels;for(auto& w:wheels)w=i.Floats<4>();Mat4 frame;for(auto& v:frame)v=i.Floats<4>();Out(PlayerWheelGroundPosition(wheels,frame));Status(true,{});break;}case 7:{owner.pre_input.result_counts=i.Words<3>();owner.pre_input.result=ReadPreInputResult(i);Status(owner.pre_input.Prepare(owner.player.manager_1856_counter_320,error),error);break;}case 8:{owner.physical.teleport_output=ReadTeleportOutputFields(i);owner.physical.state.flag_61=owner.physical.teleport_output->state_61;Status(true,{});break;}default:std::abort();}output[effects]=output.size()-effects-1;Out(std::uint32_t(teleport.targets.size()));for(auto target:teleport.targets)Out(target);ObserveFrame(r,animated,ik,skeleton,anim,owner,ground,wobble,actions);output[at]=output.size()-at-1;}output[mark]=output.size()-mark-1;
    }if(std::cin.peek()!=std::char_traits<char>::eof())return 2;for(auto word:output)for(unsigned j=0;j<4;++j)std::cout.put(static_cast<char>(word>>(j*8)));
}
